import { BookRecommendation } from '../types/book';

export const CURATED_MOCK_BOOKS: BookRecommendation[] = [
  // Ages 10-12 (Middle Grade / Tween)
  {
    id: 'mock-1',
    title: 'Percy Jackson & the Olympians: The Lightning Thief',
    author: 'Rick Riordan',
    publishedYear: 2005,
    recommendedAgeMin: 10,
    recommendedAgeMax: 13,
    whyAppropriate: 'High-energy mythological adventure with relatable themes of loyalty, ADHD/dyslexia empowerment, and friendship. Mild fantasy peril with no explicit violence or profanity.',
    interestConnection: 'Greek mythology, fast-paced quest, magical powers, monsters, and humorous hero narrative.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Fantasy mythological monsters', 'Mild perilous situations'],
    readingLevel: 'Grade 5-6 / 740L',
    genre: 'Mythological Fantasy',
    isbn: '9780786838653',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780786838653-M.jpg',
    description: 'Percy Jackson is about to be kicked out of boarding school... again. And that is the least of his troubles. Lately, mythological monsters and the gods of Mount Olympus seem to be walking straight out of the pages of Percy’s Greek mythology textbook and into his life.',
    pageCount: 377,
  },
  {
    id: 'mock-2',
    title: 'Keeper of the Lost Cities',
    author: 'Shannon Messenger',
    publishedYear: 2012,
    recommendedAgeMin: 10,
    recommendedAgeMax: 13,
    whyAppropriate: 'Charming, expansive magical world with an emphasis on empathy, telepathy, and belonging. Wholesome tween relationships and positive ethical choices.',
    interestConnection: 'Hidden magical worlds, telepathy, mythical creatures, school for prodigies, and mysteries.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Mild magical peril', 'Kidnapping threat resolved safely'],
    readingLevel: 'Grade 5-7 / 810L',
    genre: 'Fantasy Adventure',
    isbn: '9781442445949',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781442445949-M.jpg',
    description: 'Sophie Foster has a secret: she is a Telepath, and hears the thoughts of everyone around her. When she meets Fitz, a mysterious boy who appears out of nowhere, she discovers there is a place where she does belong.',
    pageCount: 496,
  },
  {
    id: 'mock-3',
    title: 'The Wild Robot',
    author: 'Peter Brown',
    publishedYear: 2016,
    recommendedAgeMin: 10,
    recommendedAgeMax: 12,
    whyAppropriate: 'Touching exploration of artificial intelligence, animal behavior, ecosystem cooperation, and parenting. Heartfelt and completely wholesome.',
    interestConnection: 'Robots, nature, survival, animal communication, and friendship in the wilderness.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Mild wilderness survival peril', 'Harsh winter elements'],
    readingLevel: 'Grade 4-6 / 740L',
    genre: 'Sci-Fi / Nature',
    isbn: '9780316381994',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780316381994-M.jpg',
    description: 'When robot Roz opens her eyes for the first time, she discovers that she is all alone on a remote, wild island. She has no idea how she got there or what her purpose is—but she knows she needs to survive.',
    pageCount: 288,
  },
  {
    id: 'mock-4',
    title: 'A Wrinkle in Time',
    author: 'Madeleine L\'Engle',
    publishedYear: 1962,
    recommendedAgeMin: 10,
    recommendedAgeMax: 14,
    whyAppropriate: 'Classic Newbery Medal winner introducing tesseract physics, love triumphing over darkness, and individuality versus conformity in an accessible, respectful way.',
    interestConnection: 'Space travel, fifth dimension physics, brave sister saving her father, and cosmic battle of light vs dark.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Mind-control menace (IT)', 'Cosmic darkness'],
    readingLevel: 'Grade 5-7 / 740L',
    genre: 'Science Fiction Classic',
    isbn: '9780312367541',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780312367541-M.jpg',
    description: 'Meg Murry, her small brother Charles Wallace, and their friend Calvin O\'Keefe go on a perilous journey through space and time to rescue Meg\'s father, a gifted scientist who disappeared while experimenting with time travel.',
    pageCount: 256,
  },
  {
    id: 'mock-5',
    title: 'Amari and the Night Brothers',
    author: 'B.B. Alston',
    publishedYear: 2021,
    recommendedAgeMin: 10,
    recommendedAgeMax: 13,
    whyAppropriate: 'Exciting urban fantasy centering perseverance, sisterly loyalty, and breaking stereotypes. Safe, uplifting middle-grade pacing.',
    interestConnection: 'Supernatural bureau, undercover investigation, illegal magic, and sister on a detective mission.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Missing sibling investigation', 'Supernatural competitive trials'],
    readingLevel: 'Grade 5-7 / 790L',
    genre: 'Urban Fantasy / Mystery',
    isbn: '9780062975171',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780062975171-M.jpg',
    description: 'Amari Peters believes her missing brother Quinton is still alive. Her search leads her to a tryout at the secret Bureau of Supernatural Affairs, where she discovers magic is real.',
    pageCount: 416,
  },
  {
    id: 'mock-6',
    title: 'Escape from Mr. Lemoncello\'s Library',
    author: 'Chris Grabenstein',
    publishedYear: 2013,
    recommendedAgeMin: 10,
    recommendedAgeMax: 13,
    whyAppropriate: 'Puzzle-driven adventure celebrating reading, library exploration, lateral thinking, and fair play. Completely clean with zero objectionable content.',
    interestConnection: 'Puzzles, riddles, escape rooms, board games, library adventures, and clever clues.',
    maturityScores: { violence: 'None', language: 'Clean', romance: 'None', themes: 'None' },
    contentWarnings: [],
    readingLevel: 'Grade 4-6 / 720L',
    genre: 'Puzzle Mystery',
    isbn: '9780307931474',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780307931474-M.jpg',
    description: 'When Kyle Keeley learns that the world\'s most famous game maker, Luigi Lemoncello, has designed the town’s new library and is having an invitation-only lock-in on opening night, he\'s determined to be there.',
    pageCount: 320,
  },
  {
    id: 'mock-7',
    title: 'Sal and Gabi Break the Universe',
    author: 'Carlos Hernandez',
    publishedYear: 2019,
    recommendedAgeMin: 10,
    recommendedAgeMax: 13,
    whyAppropriate: 'Warmhearted Cuban-American sci-fi blending sleight-of-hand magic, multiverse wormholes, managing Type 1 diabetes, and healthy coping with grief.',
    interestConnection: 'Multiverse dimensions, stage magic, school comedy, sci-fi gadgets, and friendship.',
    maturityScores: { violence: 'None', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Parental grief in the past', 'Managing chronic health condition'],
    readingLevel: 'Grade 5-7 / 730L',
    genre: 'Sci-Fi Comedy',
    isbn: '9781368022828',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781368022828-M.jpg',
    description: 'Sal Vidon is an illusionist student who accidentally opens tears in the multiverse to pull things through, causing universe-threatening anomalies while trying to help his family.',
    pageCount: 400,
  },
  {
    id: 'mock-8',
    title: 'City of Ghosts',
    author: 'Victoria Schwab',
    publishedYear: 2018,
    recommendedAgeMin: 10,
    recommendedAgeMax: 14,
    whyAppropriate: 'Atmospheric paranormal mystery set in Edinburgh. Spooky and thrilling without ever crossing into graphic horror or mature trauma.',
    interestConnection: 'Ghost hunting, historic castles, Edinburgh legends, photography, and mystery.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Spooky ghost folklore', 'Near-drowning backstory'],
    readingLevel: 'Grade 5-7 / 760L',
    genre: 'Paranormal Mystery',
    isbn: '9781338111002',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781338111002-M.jpg',
    description: 'Ever since Cass almost drowned, she can pull back the Veil that separates the living from the dead. Her best friend is even a ghost. When her parents host a TV show about spooky cities, Cass finds herself in real danger.',
    pageCount: 304,
  },
  {
    id: 'mock-9',
    title: 'Front Desk',
    author: 'Kelly Yang',
    publishedYear: 2018,
    recommendedAgeMin: 10,
    recommendedAgeMax: 13,
    whyAppropriate: 'Inspiring, humorous, and empathetic look at immigrant resilience, community solidarity, and youth enterprise with honest yet age-appropriate handling of social justice.',
    interestConnection: 'Running a motel, secret community activism, writing dreams, family resilience, and friendship.',
    maturityScores: { violence: 'None', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Mild financial anxiety', 'Encounter with biased landlord'],
    readingLevel: 'Grade 4-6 / 640L',
    genre: 'Realistic Contemporary',
    isbn: '9781338157796',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781338157796-M.jpg',
    description: 'Mia Tang has a lot of secrets. Number 1: She lives in a motel, not a big house. Number 2: Her parents hide immigrants in vacant rooms. Number 3: She wants to be a writer, even if English isn\'t her first language.',
    pageCount: 304,
  },
  {
    id: 'mock-10',
    title: 'Space Case',
    author: 'Stuart Gibbs',
    publishedYear: 2014,
    recommendedAgeMin: 10,
    recommendedAgeMax: 13,
    whyAppropriate: 'Engaging, fast-moving lunar base locked-room whodunit. Teaches space physics and scientific deduction with lighthearted humor.',
    interestConnection: 'Moon base, space science, locked-room murder mystery solved by clever tween detective.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Suspicious death on space station investigated deductively'],
    readingLevel: 'Grade 5-7 / 750L',
    genre: 'Sci-Fi Mystery',
    isbn: '9781442494879',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781442494879-M.jpg',
    description: 'Dashiell Gibson is a twelve-year-old living on Moon Base Alpha. When the base\'s top scientist turns up dead, Dash suspects foul play and must crack the case before anyone else gets hurt.',
    pageCount: 352,
  },

  // Ages 12-14 (Middle School / Transition)
  {
    id: 'mock-11',
    title: 'The Giver',
    author: 'Lois Lowry',
    publishedYear: 1993,
    recommendedAgeMin: 12,
    recommendedAgeMax: 15,
    whyAppropriate: 'Thought-provoking dystopian classic exploring memory, empathy, individuality, and societal trade-offs. Fosters high-level ethical discussions with thoughtful literary depth.',
    interestConnection: 'Utopian/dystopian community, assigned life roles, telepathic transmission of world history, and moral rebellion.',
    maturityScores: { violence: 'Moderate', language: 'Clean', romance: 'None', themes: 'Moderate' },
    contentWarnings: ['Infant euthanasia ritual (handled critically and soberly)', 'Emotional gravity'],
    readingLevel: 'Grade 7-9 / 760L',
    genre: 'Dystopian Classic',
    isbn: '9780544336261',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780544336261-M.jpg',
    description: 'Jonas\'s world is perfect. Everything is under control and safe. There is no war or fear or pain. But when Jonas turns twelve, he is chosen to begin training from an elder known only as The Giver.',
    pageCount: 240,
  },
  {
    id: 'mock-12',
    title: 'Scythe',
    author: 'Neal Shusterman',
    publishedYear: 2016,
    recommendedAgeMin: 12,
    recommendedAgeMax: 16,
    whyAppropriate: 'Philosophical speculative fiction examining mortality, ethics, and power in an immortal society controlled by a benevolent AI. High moral integrity.',
    interestConnection: 'Futuristic AI utopia, moral dilemma, apprentice training, philosophical debate on death and duty.',
    maturityScores: { violence: 'Moderate', language: 'Mild', romance: 'Mild', themes: 'Moderate' },
    contentWarnings: ['Gleaning/culling of population mandated by law', 'Apprentice combat training'],
    readingLevel: 'Grade 7-10 / 830L',
    genre: 'Speculative Sci-Fi',
    isbn: '9781442472426',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781442472426-M.jpg',
    description: 'In a world where hunger, disease, and war have been eliminated, humans can only die by being "gleaned" by Scythes. Two teens are apprenticed to a Scythe and must master the art of death.',
    pageCount: 448,
  },
  {
    id: 'mock-13',
    title: 'Cinder (The Lunar Chronicles)',
    author: 'Marissa Meyer',
    publishedYear: 2012,
    recommendedAgeMin: 12,
    recommendedAgeMax: 15,
    whyAppropriate: 'Imaginative sci-fi fairy tale retelling featuring an empowered cyborg mechanic, futuristic geopolitics, and infectious disease cure research.',
    interestConnection: 'Cyborg mechanics, fairy tale reimagining, plague epidemic investigation, futuristic New Beijing.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'Mild', themes: 'Moderate' },
    contentWarnings: ['Futuristic pandemic peril', 'Prejudice against cyborgs'],
    readingLevel: 'Grade 6-9 / 790L',
    genre: 'Sci-Fi Fairy Tale',
    isbn: '9781250007209',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781250007209-M.jpg',
    description: 'A gifted mechanic in futuristic New Beijing, Cinder is a cyborg with a mysterious past. When Prince Kai visits her repair booth, she is thrust into the center of an intergalactic struggle.',
    pageCount: 390,
  },
  {
    id: 'mock-14',
    title: 'Legend',
    author: 'Marie Lu',
    publishedYear: 2011,
    recommendedAgeMin: 12,
    recommendedAgeMax: 15,
    whyAppropriate: 'High-octane dual POV dystopian thriller pitting a military prodigy against a street rebel. Emphasizes truth, critical inquiry, and questioning corrupt authority.',
    interestConnection: 'Futuristic Los Angeles, cat-and-mouse military strategy, rebellion, parkour, and sibling defense.',
    maturityScores: { violence: 'Moderate', language: 'Mild', romance: 'Mild', themes: 'Moderate' },
    contentWarnings: ['Military skirmishes', 'Brother framed for crime'],
    readingLevel: 'Grade 7-9 / 710L',
    genre: 'Dystopian Action',
    isbn: '9780142422076',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780142422076-M.jpg',
    description: 'What was once the western United States is now home to the Republic, a nation perpetually at war with its neighbors. Born into an elite family, fifteen-year-old June is a military prodigy. Day is the country\'s most-wanted criminal.',
    pageCount: 305,
  },
  {
    id: 'mock-15',
    title: 'All Systems Red (The Murderbot Diaries)',
    author: 'Martha Wells',
    publishedYear: 2017,
    recommendedAgeMin: 13,
    recommendedAgeMax: 17,
    whyAppropriate: 'Hugo & Nebula award winner following a sentient security android with social anxiety who wants to watch soap operas but protects its crew. Funny, perceptive, and thought-provoking.',
    interestConnection: 'Sentient AI, security cyborgs, space exploration survey, tech hacking, and humorous inner monologue.',
    maturityScores: { violence: 'Moderate', language: 'Mild', romance: 'None', themes: 'Moderate' },
    contentWarnings: ['Sci-fi security skirmishes with hostile fauna and rogue bots'],
    readingLevel: 'Grade 8-11 / 890L',
    genre: 'Science Fiction / Cyberpunk',
    isbn: '9780765397539',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780765397539-M.jpg',
    description: 'On a distant planet, a team of scientists are conducting surface tests, bound by company-mandated security units. But their security android has hacked its own governor module and self-names Murderbot.',
    pageCount: 144,
  },

  // Ages 14-17 (High School / Young Adult / Emerging Adult)
  {
    id: 'mock-16',
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    publishedYear: 2008,
    recommendedAgeMin: 13,
    recommendedAgeMax: 17,
    whyAppropriate: 'Powerful critique of reality television, totalitarian propaganda, war trauma, and socioeconomic disparity. Katniss is a resource-smart heroine driven by sisterly devotion.',
    interestConnection: 'Survival competition, archery, oppressive regime revolt, tactical strategy, and public spectacle.',
    maturityScores: { violence: 'Moderate', language: 'Mild', romance: 'Mild', themes: 'Moderate' },
    contentWarnings: ['Teens fighting in state-mandated arena', 'Trauma and grief'],
    readingLevel: 'Grade 8-10 / 810L',
    genre: 'Dystopian Thriller',
    isbn: '9780439023481',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780439023481-M.jpg',
    description: 'In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. Sixteen-year-old Katniss Everdeen volunteers in her younger sister’s place for the annual televised death match.',
    pageCount: 374,
  },
  {
    id: 'mock-17',
    title: 'Six of Crows',
    author: 'Leigh Bardugo',
    publishedYear: 2015,
    recommendedAgeMin: 14,
    recommendedAgeMax: 17,
    whyAppropriate: 'Masterclass in intricate heist plotting, ensemble character development, trauma recovery, and found family. Sophisticated YA storytelling.',
    interestConnection: 'Impossible prison break heist, grifter crew, magical elements, strategy, and gritty underworld banter.',
    maturityScores: { violence: 'Moderate', language: 'Moderate', romance: 'Moderate', themes: 'Moderate' },
    contentWarnings: ['Underworld crime syndicate', 'Traumatic pasts referenced'],
    readingLevel: 'Grade 9-12 / 790L',
    genre: 'Fantasy Heist',
    isbn: '9781627792127',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781627792127-M.jpg',
    description: 'Criminal prodigy Kaz Brekker is offered a chance at a deadly heist that could make him rich beyond his wildest dreams. But he can\'t pull it off alone: he needs six dangerous outcasts.',
    pageCount: 465,
  },
  {
    id: 'mock-18',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    publishedYear: 2021,
    recommendedAgeMin: 14,
    recommendedAgeMax: 17,
    whyAppropriate: 'Triumph of scientific optimism, math-based problem solving, linguistics, interspecies friendship, and self-sacrifice for human survival. Engaging for high school science enthusiasts.',
    interestConnection: 'Space survival, hard physics calculations, alien communication, amnesia mystery, and saving Earth from extinction.',
    maturityScores: { violence: 'Mild', language: 'Moderate', romance: 'None', themes: 'Moderate' },
    contentWarnings: ['Extinction threat to biosphere', 'Occasional adult profanity'],
    readingLevel: 'Grade 9-12 / 920L',
    genre: 'Hard Sci-Fi',
    isbn: '9780593135204',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780593135204-M.jpg',
    description: 'Ryland Grace is the sole survivor on a desperate, last-chance mission to save Earth from a dimming sun. He just woke up from a coma, doesn’t remember his name, and must do astrophysics to stay alive.',
    pageCount: 496,
  },
  {
    id: 'mock-19',
    title: 'The Marrow Thieves',
    author: 'Cherie Dimaline',
    publishedYear: 2017,
    recommendedAgeMin: 14,
    recommendedAgeMax: 17,
    whyAppropriate: 'Acclaimed Indigenous dystopian novel about ecological devastation, cultural survival, generational trauma, and collective resilience. Rich in historical allegory and emotional truth.',
    interestConnection: 'Post-apocalyptic wilderness, Indigenous cultural endurance, escaping marrow hunters, and found family.',
    maturityScores: { violence: 'Moderate', language: 'Moderate', romance: 'Mild', themes: 'Mature' },
    contentWarnings: ['Genocidal hunting allegories', 'Loss of loved ones'],
    readingLevel: 'Grade 9-12 / 850L',
    genre: 'Indigenous Dystopian YA',
    isbn: '9781770864863',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781770864863-M.jpg',
    description: 'In a futuristic world ravaged by global warming, people have lost the ability to dream, and the dreamlessness has led to widespread madness. The only people still able to dream are North America\'s Indigenous people.',
    pageCount: 231,
  },
  {
    id: 'mock-20',
    title: 'Ender\'s Game',
    author: 'Orson Scott Card',
    publishedYear: 1985,
    recommendedAgeMin: 12,
    recommendedAgeMax: 16,
    whyAppropriate: 'Classic military science fiction exploring strategic brilliance, isolation, empathy towards enemies, ethics of war games, and leadership burden.',
    interestConnection: 'Space battle school, zero gravity combat simulation, tactical game theory, and super-intelligent youth prodigies.',
    maturityScores: { violence: 'Moderate', language: 'Mild', romance: 'None', themes: 'Moderate' },
    contentWarnings: ['Intense peer bullying encounters', 'Moral devastation of war simulation'],
    readingLevel: 'Grade 7-10 / 780L',
    genre: 'Military Sci-Fi Classic',
    isbn: '9780812550702',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780812550702-M.jpg',
    description: 'In order to develop a secure defense against a hostile alien race\'s next attack, government agencies breed child geniuses and train them as soldiers in zero-gravity battle school.',
    pageCount: 324,
  },
  // Additional backups to ensure dynamic query matching
  {
    id: 'mock-21',
    title: 'Crying in H Mart',
    author: 'Michelle Zauner',
    publishedYear: 2021,
    recommendedAgeMin: 16,
    recommendedAgeMax: 17,
    whyAppropriate: 'Deeply moving, honest memoir about mother-daughter relationships, culinary heritage, grief, and identity. Best for mature high school juniors/seniors.',
    interestConnection: 'Korean food, indie music, coming of age, mother-daughter bond, and navigating grief.',
    maturityScores: { violence: 'None', language: 'Moderate', romance: 'Mild', themes: 'Mature' },
    contentWarnings: ['Cancer illness and death of mother'],
    readingLevel: 'Grade 11-12 / 1020L',
    genre: 'Memoir / Culture',
    isbn: '9780525657743',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780525657743-M.jpg',
    description: 'An unflinching, powerful memoir about growing up Korean American, losing her mother, and forging her own identity through food and music.',
    pageCount: 256,
  },
  {
    id: 'mock-22',
    title: 'A Good Girl\'s Guide to Murder',
    author: 'Holly Jackson',
    publishedYear: 2019,
    recommendedAgeMin: 14,
    recommendedAgeMax: 17,
    whyAppropriate: 'Engaging, modern true-crime podcast-style investigation by an inquisitive high school senior for her capstone project. Excellent deductive puzzles.',
    interestConnection: 'Senior capstone investigation, murder podcast format, interviewing suspects, and uncovering town secrets.',
    maturityScores: { violence: 'Moderate', language: 'Moderate', romance: 'Mild', themes: 'Moderate' },
    contentWarnings: ['Murder investigation details', 'Drug and party references'],
    readingLevel: 'Grade 9-12 / 820L',
    genre: 'YA Mystery Thriller',
    isbn: '9781984896391',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781984896391-M.jpg',
    description: 'Five years ago, schoolgirl Andie Bell was murdered by Sal Singh. Everyone knows he did it. But Pippa Fitz-Amobi isn\'t so sure, and for her senior project, she decides to investigate.',
    pageCount: 433,
  },
  {
    id: 'mock-23',
    title: 'The Hate U Give',
    author: 'Angie Thomas',
    publishedYear: 2017,
    recommendedAgeMin: 14,
    recommendedAgeMax: 17,
    whyAppropriate: 'Monumental contemporary YA exploring systemic inequality, code-switching between private prep school and neighborhood, and finding one\'s activist voice.',
    interestConnection: 'Activism, code-switching, hip-hop culture, family loyalty, and courageous truth-telling.',
    maturityScores: { violence: 'Moderate', language: 'Moderate', romance: 'Mild', themes: 'Mature' },
    contentWarnings: ['Police shooting of an unarmed friend', 'Swearing in context'],
    readingLevel: 'Grade 9-12 / 590L',
    genre: 'Contemporary Social Realism',
    isbn: '9780062498540',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780062498540-M.jpg',
    description: 'Sixteen-year-old Starr Carter moves between two worlds: the poor neighborhood where she lives and the fancy suburban prep school she attends. The uneasy balance is shattered when Starr witnesses the fatal shooting of her childhood best friend.',
    pageCount: 464,
  },
  {
    id: 'mock-24',
    title: 'Ghost',
    author: 'Jason Reynolds',
    publishedYear: 2016,
    recommendedAgeMin: 10,
    recommendedAgeMax: 13,
    whyAppropriate: 'Fast, empathetic story about an athletic kid with trauma channeling his energy onto a track team with mentorship from an Olympic coach.',
    interestConnection: 'Track and field, sprinting, athletic discipline, street resilience, and tough-love coach.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'None', themes: 'Mild' },
    contentWarnings: ['Flashback to father shooting a gun while intoxicated (no blood)'],
    readingLevel: 'Grade 5-7 / 730L',
    genre: 'Sports / Middle Grade',
    isbn: '9781481450157',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781481450157-M.jpg',
    description: 'Castle "Ghost" Cranshaw has been running since he was little, fleeing a violent father. When he challenges an elite sprinter at the local park, Coach Brody recruits him for the Defenders track team.',
    pageCount: 192,
  },
  {
    id: 'mock-25',
    title: 'Nimona',
    author: 'ND Stevenson',
    publishedYear: 2015,
    recommendedAgeMin: 11,
    recommendedAgeMax: 15,
    whyAppropriate: 'Hilarious, heartfelt graphic novel subverting hero and villain tropes, celebrating agency, identity, and self-acceptance with wonderful artwork.',
    interestConnection: 'Shapeshifter sidekick, mad science, knight academy corruption, and irreverent comedy.',
    maturityScores: { violence: 'Mild', language: 'Clean', romance: 'Mild', themes: 'Mild' },
    contentWarnings: ['Cartoon explosions and laser battles'],
    readingLevel: 'Grade 6-9 / 650L',
    genre: 'Graphic Novel / Fantasy',
    isbn: '9780062278227',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780062278227-M.jpg',
    description: 'Nimona is an impulsive young shapeshifter with a knack for villainy. Lord Ballister Blackheart is a villain with a vendetta. Together, they team up to prove that the Institution of Law Enforcement isn\'t as heroic as it claims.',
    pageCount: 272,
  },
];

export function getMockRecommendations(age: number, interest: string): BookRecommendation[] {
  const normalizedInterest = interest.toLowerCase();
  const keywords = normalizedInterest
    .split(/\s+/)
    .filter((k) => k.length > 2 && !['book', 'books', 'about', 'with', 'like', 'for', 'the', 'and'].includes(k));

  // Score books based on age closeness and keyword hits
  const scored = CURATED_MOCK_BOOKS.map((book) => {
    let score = 0;

    // Age suitability score: heavily favor books that enclose or fit the requested age
    if (age >= book.recommendedAgeMin && age <= book.recommendedAgeMax) {
      score += 50;
    } else {
      const dist = Math.min(
        Math.abs(age - book.recommendedAgeMin),
        Math.abs(age - book.recommendedAgeMax)
      );
      score += Math.max(0, 30 - dist * 10);
    }

    // Keyword relevance
    const textCorpus = `${book.title} ${book.genre || ''} ${book.interestConnection} ${book.description || ''}`.toLowerCase();
    for (const kw of keywords) {
      if (textCorpus.includes(kw)) {
        score += 20;
      }
    }

    return { book, score };
  });

  // Sort descending by score
  scored.sort((a, b) => b.score - a.score);

  // Return at least 20 items (taking all available, or recycling with unique IDs if less than 20)
  const results: BookRecommendation[] = [];
  const selected = scored.slice(0, 20);

  selected.forEach(({ book }, idx) => {
    results.push({
      ...book,
      id: `rec-${idx + 1}-${book.id}`,
    });
  });

  // If there are less than 20 due to pool size, pad up to exactly 20
  while (results.length < 20 && CURATED_MOCK_BOOKS.length > 0) {
    const fallbackBook = CURATED_MOCK_BOOKS[results.length % CURATED_MOCK_BOOKS.length];
    results.push({
      ...fallbackBook,
      id: `rec-${results.length + 1}-${fallbackBook.id}`,
    });
  }

  return results.slice(0, 20);
}
