# Group 1 Part B: Books mock-51 to mock-114 (64 books)

GROUP_1_B = [
    {
        "id": "mock-51",
        "title": "Where the Mountain Meets the Moon",
        "author": "Grace Lin",
        "publishedYear": 2009,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Newbery Honor quest weaving Chinese folklore, filial devotion, dragon companions, and grateful contentment.",
        "interestConnection": "Chinese mythology, flying dragon, jade river, Old Man of the Moon quest, and storytelling.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "None" },
        "contentWarnings": [],
        "readingLevel": "Grade 4-6 / 810L",
        "genre": "Folklore Fantasy",
        "isbn": "9780316003568",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316003568-M.jpg",
        "description": "Minli lives in the valley of Fruitless Mountain. Inspired by her father's folktales, she journeys to find the Old Man of the Moon to change her family's fortune, joined by a flightless dragon.",
        "pageCount": 304
    },
    {
        "id": "mock-52",
        "title": "Island of the Blue Dolphins",
        "author": "Scott O'Dell",
        "publishedYear": 1960,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Newbery classic survival tale of a young Indigenous girl who survives alone on a Pacific island with courage, resourcefulness, and animal companionship.",
        "interestConnection": "Island survival, making canoe and weapons, taming wild dog Karana, sea otters, and self-reliance.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Wild dog attack resulting in brother's death", "Isolated solitary living"],
        "readingLevel": "Grade 5-7 / 1000L",
        "genre": "Survival Classic",
        "isbn": "9780547328614",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780547328614-M.jpg",
        "description": "Left stranded on an isolated island off the coast of California, Karana learns to build shelter, craft weapons, forage, and make peace with the wild animals around her for eighteen years.",
        "pageCount": 192
    },
    {
        "id": "mock-53",
        "title": "My Side of the Mountain",
        "author": "Jean Craighead George",
        "publishedYear": 1959,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Newbery Honor classic celebrating wilderness independence, botanical lore, living inside a hollow tree, and falconry.",
        "interestConnection": "Wilderness bushcraft, falconry training, hollow hemlock tree house, foraging, and solitude.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "None" },
        "contentWarnings": [],
        "readingLevel": "Grade 5-7 / 810L",
        "genre": "Nature / Wilderness Classic",
        "isbn": "9780141312422",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780141312422-M.jpg",
        "description": "Sam Gribley runs away from his crowded New York City apartment to live on his great-grandfather's abandoned land in the Catskill Mountains, learning to survive with a trained peregrine falcon.",
        "pageCount": 192
    },
    {
        "id": "mock-54",
        "title": "Tuck Everlasting",
        "author": "Natalie Babbitt",
        "publishedYear": 1975,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Lyrical, philosophical classic exploring the natural circle of life, mortality, and the profound burden of living forever.",
        "interestConnection": "Secret spring of eternal youth, kidnapping mystery, toad friend, moral dilemma, and wheel of time.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Self-defense shooting of blackmailer with shotgun", "Jailbreak escape"],
        "readingLevel": "Grade 5-7 / 770L",
        "genre": "Magical Realism Classic",
        "isbn": "9780312369811",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780312369811-M.jpg",
        "description": "Ten-year-old Winnie Foster stumbles upon the Tuck family and their greatest secret: a hidden woodland spring that grants eternal life to anyone who drinks from it.",
        "pageCount": 160
    },
    {
        "id": "mock-55",
        "title": "The Graveyard Book",
        "author": "Neil Gaiman",
        "publishedYear": 2008,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Newbery and Carnegie winning dark fantasy following a boy raised by benign ghosts, learning lessons about life, courage, and growing up.",
        "interestConnection": "Graveyard upbringing, ghost mentors, werewolf guardian, ghoul gate, and coming-of-age mystery.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Family murdered in prologue (handled with fairy tale distance)", "Ghoul peril"],
        "readingLevel": "Grade 5-8 / 820L",
        "genre": "Dark Fantasy / Coming of Age",
        "isbn": "9780060530945",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780060530945-M.jpg",
        "description": "Nobody Owens, known to his friends as Bod, is a normal boy who would be entirely normal if he didn't live in a graveyard, being raised and educated by ghosts with a guardian from between worlds.",
        "pageCount": 336
    },
    {
        "id": "mock-56",
        "title": "Coraline",
        "author": "Neil Gaiman",
        "publishedYear": 2002,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Masterfully spooky modern fable about true bravery: being terrified yet doing what is right anyway to save loved ones.",
        "interestConnection": "Secret door in flat, sinister Other Mother, button eyes, talking black cat, and bravery test.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Creepy button eyes horror motif", "Entrapped ghost children"],
        "readingLevel": "Grade 4-6 / 740L",
        "genre": "Creepy Fantasy",
        "isbn": "9780380807345",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780380807345-M.jpg",
        "description": "When Coraline steps through a locked door in her new home, she finds an alternate version of her life with an 'Other Mother' who wants to keep her forever and sew buttons into her eyes.",
        "pageCount": 176
    },
    {
        "id": "mock-57",
        "title": "Greenglass House",
        "author": "Kate Milford",
        "publishedYear": 2014,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Cozy, atmospheric winter mystery set in a smugglers' inn, blending roleplaying games, adoption, folklore, and puzzle solving.",
        "interestConnection": "Winter holiday snowstorm, smugglers' inn, tabletop roleplaying quests, stained glass clues, and tea.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Theft at inn", "Adoption identity reflections"],
        "readingLevel": "Grade 5-7 / 800L",
        "genre": "Cozy Mystery",
        "isbn": "9780544552708",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780544552708-M.jpg",
        "description": "Twelve-year-old Milo is spending winter break at his parents' secluded smugglers' inn when unexpected guests arrive during a blinding snowstorm, each carrying secrets connected to the house.",
        "pageCount": 400
    },
    {
        "id": "mock-58",
        "title": "City Spies",
        "author": "James Ponti",
        "publishedYear": 2020,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Fast-paced, high-tech international espionage series featuring an empowered team of diverse kid hackers, codebreakers, and sleuths.",
        "interestConnection": "Teen spy agency, computer hacking, secret code cracking, international travel, and MI6 mentors.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Kid hacker legal jeopardy in opening chapter", "Espionage chase tension"],
        "readingLevel": "Grade 5-7 / 770L",
        "genre": "Spy Adventure",
        "isbn": "9781534414921",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781534414921-M.jpg",
        "description": "Operating out of a secret base in Scotland, five kids from all over the world are recruited by an elite British intelligence agent to infiltrate high-stakes international competitions and stop rogue operatives.",
        "pageCount": 384
    },
    {
        "id": "mock-59",
        "title": "Spy School",
        "author": "Stuart Gibbs",
        "publishedYear": 2012,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Hilarious action-comedy deconstructing spy tropes with a math-whiz protagonist who outsmarts assassins with logic.",
        "interestConnection": "Secret CIA academy, math prodigy, ninja sparring, double agents, and hilarious blunders.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Paintball and martial arts spy academy combat", "Rogue mole threat"],
        "readingLevel": "Grade 4-7 / 740L",
        "genre": "Action Comedy / Spy",
        "isbn": "9781442421820",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781442421820-M.jpg",
        "description": "Ben Ripley may look like an awkward middle schooler, but his math genius gets him recruited to the CIA's top-secret Academy of Espionage, where an assassin targets him on his very first day.",
        "pageCount": 304
    },
    {
        "id": "mock-60",
        "title": "Restart",
        "author": "Gordon Korman",
        "publishedYear": 2017,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Thoughtful, funny exploration of redemption and bullying: an amnesiac middle-school bully gets a blank slate to decide who he truly wants to be.",
        "interestConnection": "Amnesia reset, video club filmmaking, reforming from bully past, nursing home friendships, and humor.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Fall from roof accident", "Past bullying flashbacks"],
        "readingLevel": "Grade 4-6 / 730L",
        "genre": "School Comedy / Realistic",
        "isbn": "9781338053807",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781338053807-M.jpg",
        "description": "Chase doesn't remember falling off the roof or his own name. When he returns to middle school, he discovers he was the school's most notorious bully, and must choose whether to restart his life.",
        "pageCount": 256
    },
    {
        "id": "mock-61",
        "title": "Ungifted",
        "author": "Gordon Korman",
        "publishedYear": 2012,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Laugh-out-loud school comedy showing that intelligence takes many forms, bridging the gap between rule-breakers and robotic geniuses.",
        "interestConnection": "Robotics competition, accidental transfer to academy for the gifted, school pranks, and loyal teamwork.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "None" },
        "contentWarnings": ["School prank property damage (handled humorously)"],
        "readingLevel": "Grade 4-7 / 730L",
        "genre": "School Comedy",
        "isbn": "9780061742675",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780061742675-M.jpg",
        "description": "When a spectacular prank goes disastrously wrong, middle-school troublemaker Donovan Curtis accidentally gets transferred to the Academy for Scholastic Distinction instead of detention.",
        "pageCount": 288
    },
    {
        "id": "mock-62",
        "title": "Swindle",
        "author": "Gordon Korman",
        "publishedYear": 2008,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Fun Ocean's Eleven-style heist for kids, where sixth graders plan an ingenious recovery of a stolen million-dollar baseball card.",
        "interestConnection": "Baseball card heist, guard dog whisperer, tech hacking, kid team roles, and outsmarting swindlers.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "None" },
        "contentWarnings": ["Kids breaking into an antique dealer's house to reclaim stolen property"],
        "readingLevel": "Grade 4-6 / 710L",
        "genre": "Comedy / Heist",
        "isbn": "9780439903448",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780439903448-M.jpg",
        "description": "Griffin Bing finds a rare 1920 Babe Ruth baseball card and gets cheated out of it by an unscrupulous dealer. Griffin rounds up a crack team of classmates to steal it back.",
        "pageCount": 256
    },
    {
        "id": "mock-63",
        "title": "The Fourteenth Goldfish",
        "author": "Jennifer L. Holm",
        "publishedYear": 2014,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Charming scientific comedy about aging, immortality, and curiosity: an eccentric scientist grandpa reverses his age and goes to middle school with his granddaughter.",
        "interestConnection": "Science experiments, reverse aging jellyfish, quirky grandfather, science history, and middle school comedy.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": [],
        "readingLevel": "Grade 4-6 / 550L",
        "genre": "Science Fiction / Family",
        "isbn": "9780375870644",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780375870644-M.jpg",
        "description": "Galileo, Newton, and Salk are Ellie’s grandfather Melvin’s idols. When Melvin discovers a cure for aging using a rare jellyfish, he turns into a grumpy teenager who has to attend middle school with Ellie.",
        "pageCount": 224
    },
    {
        "id": "mock-64",
        "title": "The Last Cuentista",
        "author": "Donna Barba Higuera",
        "publishedYear": 2021,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Newbery Medal and Pura Belpré winning sci-fi triumph celebrating Mexican oral storytelling, memory preservation, and resisting authoritarian conformity on a colony ship.",
        "interestConnection": "Colony starship, Halley's comet earth evacuation, Mexican cuentos folklore, mind purging, and story power.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Earth destroyed by comet in opening", "Memory erasure threat by totalitarian Collective"],
        "readingLevel": "Grade 5-8 / 700L",
        "genre": "Dystopian Sci-Fi / Folklore",
        "isbn": "9781646140893",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781646140893-M.jpg",
        "description": "Petra Peña wants nothing more than to be a cuentista, like her abuelita. But Earth is about to be destroyed by a comet, and only a few hundred people are selected to journey to a new planet.",
        "pageCount": 336
    },
    {
        "id": "mock-65",
        "title": "Roll of Thunder, Hear My Cry",
        "author": "Mildred D. Taylor",
        "publishedYear": 1976,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Newbery Medal classic honoring African American family dignity, land ownership, and moral strength in 1930s Mississippi.",
        "interestConnection": "Historical resistance, family land ownership, Great Depression South, school bus boycotts, and dignity.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Historical racial slurs of 1930s Jim Crow South", "Threat of night riders and lynching"],
        "readingLevel": "Grade 5-8 / 920L",
        "genre": "Historical Fiction Classic",
        "isbn": "9780140384512",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780140384512-M.jpg",
        "description": "Set in Mississippi at the height of the Depression, this is the story of one Black family's struggle to maintain their integrity, pride, and independence in the face of racism and social injustice.",
        "pageCount": 288
    },
    {
        "id": "mock-66",
        "title": "One Crazy Summer",
        "author": "Rita Williams-Garcia",
        "publishedYear": 2010,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Newbery Honor and Coretta Scott King winner following three sisters visiting Oakland in 1968, learning community empowerment and poetry at the Black Panther summer camp.",
        "interestConnection": "1968 Oakland, sisterly responsibility, Black Panther breakfast program, poetry performance, and civil rights history.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Parental emotional distance", "Police raid protest tensions"],
        "readingLevel": "Grade 4-7 / 750L",
        "genre": "Historical Fiction",
        "isbn": "9780060760908",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780060760908-M.jpg",
        "description": "Eleven-year-old Delphine and her younger sisters fly from Brooklyn to Oakland, California, to spend the summer with the mother who abandoned them, spending their days at a local community summer center.",
        "pageCount": 224
    },
    {
        "id": "mock-67",
        "title": "The Thing About Jellyfish",
        "author": "Ali Benjamin",
        "publishedYear": 2015,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "National Book Award finalist on scientific inquiry, marine biology, processing unspoken grief, and coming to terms with mortality.",
        "interestConnection": "Irukandji jellyfish biology, scientific method, quiet friendship, field trips, and processing loss.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Drowning death of childhood friend", "Selective mutism in grief"],
        "readingLevel": "Grade 5-7 / 740L",
        "genre": "Realistic Fiction",
        "isbn": "9780316380867",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316380867-M.jpg",
        "description": "Suzy Swanson is convinced that the tragic drowning of her former best friend was caused by a rare jellyfish sting, and retreats into silent scientific research to prove it to the world.",
        "pageCount": 352
    },
    {
        "id": "mock-68",
        "title": "Out of My Mind",
        "author": "Sharon M. Draper",
        "publishedYear": 2010,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Unforgettable, eye-opening novel from the perspective of an 11-year-old with cerebral palsy who has a photographic memory and finally gets a voice device.",
        "interestConnection": "Cerebral palsy perspective, photographic memory, assistive communication technology, Whiz Kids trivia, and overcoming bias.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Exclusion by peers", "Accidental driveway backing-up scare"],
        "readingLevel": "Grade 4-6 / 700L",
        "genre": "Realistic Fiction / Empathy",
        "isbn": "9781416971719",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781416971719-M.jpg",
        "description": "Eleven-year-old Melody has a photographic memory, but nobody knows it because she cannot speak or write due to cerebral palsy. When she receives a computer communication device, she shocks everyone.",
        "pageCount": 295
    },
    {
        "id": "mock-69",
        "title": "Fish in a Tree",
        "author": "Lynda Mullaly Hunt",
        "publishedYear": 2015,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Inspiring story about dyslexia, student empowerment, creative problem solving, and teachers who see beyond behavioral defense mechanisms.",
        "interestConnection": "Dyslexia discovery, chess strategies, inspiring teacher, overcoming shame, and artistic talent.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Classroom teasing and self-doubt"],
        "readingLevel": "Grade 4-6 / 550L",
        "genre": "Realistic / School Fiction",
        "isbn": "9780399162596",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399162596-M.jpg",
        "description": "Ally has been smart enough to fool a lot of different people by creating clever disruptions to hide her inability to read. But her new teacher Mr. Daniels sees the brilliant creative kid underneath.",
        "pageCount": 288
    },
    {
        "id": "mock-70",
        "title": "Counting by 7s",
        "author": "Holly Goldberg Sloan",
        "publishedYear": 2013,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Quirky, uplifting story of an eccentric genius orphan who finds an unconventional adoptive family through gardening, mathematics, and kindness.",
        "interestConnection": "Neurodiversity, botanical gardening transformation, counting by primes, found family, and resilience.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Car crash passing of adoptive parents"],
        "readingLevel": "Grade 5-7 / 770L",
        "genre": "Realistic Fiction",
        "isbn": "9780142422861",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780142422861-M.jpg",
        "description": "Willow Chance is a twelve-year-old genius obsessed with nature, medical conditions, and counting by 7s. When tragedy strikes, she brings together a misfit group of strangers who help her rebuild her world.",
        "pageCount": 384
    },
    {
        "id": "mock-71",
        "title": "A Long Walk to Water",
        "author": "Linda Sue Park",
        "publishedYear": 2010,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "New York Times bestseller intertwining the true story of Salva Dut, one of the Lost Boys of Sudan, with a modern girl's daily struggle for clean water.",
        "interestConnection": "Sudan civil war, Lost Boys trek to refugee camps, drilling clean water wells, and resilience.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Wartime violence and refugee river crossing peril (crocodiles, gunfire)"],
        "readingLevel": "Grade 5-7 / 720L",
        "genre": "Historical / Biographical Fiction",
        "isbn": "9780547577319",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780547577319-M.jpg",
        "description": "In 1985, Salva flees his school during an attack in Sudan and treks across continent to survive. In 2008, Nya walks eight hours every day to fetch water for her family, until their lives intersect.",
        "pageCount": 128
    },
    {
        "id": "mock-72",
        "title": "When You Reach Me",
        "author": "Rebecca Stead",
        "publishedYear": 2009,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Newbery Medal-winning 1970s New York mystery celebrating friendship, A Wrinkle in Time, time travel, and altruistic sacrifice.",
        "interestConnection": "Time travel letters, 1970s NYC street life, game show prep, friendship rifts, and locked mystery.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Street vehicle accident self-sacrifice moment"],
        "readingLevel": "Grade 5-7 / 750L",
        "genre": "Sci-Fi Mystery Classic",
        "isbn": "9780385737432",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385737432-M.jpg",
        "description": "Miranda is a sixth grader in 1979 New York City who starts receiving mysterious notes from someone who knows things about the future that haven't happened yet.",
        "pageCount": 208
    },
    {
        "id": "mock-73",
        "title": "The Inquisitor's Tale",
        "author": "Adam Gidwitz",
        "publishedYear": 2016,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Newbery Honor medieval Canterbury Tales-style adventure with three diverse children and a resurrected holy dog escaping persecutors in 1242 France.",
        "interestConnection": "Medieval France, holy dog miracles, illuminated manuscripts, knight battles, and interfaith unity.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Medieval religious persecution of books and heretics", "Gargoyle battles"],
        "readingLevel": "Grade 5-8 / 690L",
        "genre": "Historical Fantasy",
        "isbn": "9780525426165",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780525426165-M.jpg",
        "description": "In 1242, an innkeeper gathers travelers to tell the tale of three magical children—a peasant girl, a Jewish boy, and a young monk—fleeing King Louis IX alongside a resurrected greyhound.",
        "pageCount": 384
    },
    {
        "id": "mock-74",
        "title": "A Tale Dark & Grimm",
        "author": "Adam Gidwitz",
        "publishedYear": 2010,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Irreverent, witty retelling of traditional Grimm fairy tales with an engaging narrator helping kids explore morality, fear, and finding home.",
        "interestConnection": "Hansel and Gretel reimagined, dragon battles, humorous narrator warnings, and dark fairy tale adventure.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Classic Grimm bloodiness (handled with humor and caution)"],
        "readingLevel": "Grade 4-7 / 690L",
        "genre": "Dark Fairy Tale Comedy",
        "isbn": "9780142419670",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780142419670-M.jpg",
        "description": "Hansel and Gretel walk out of their own story and into eight other classic Grimm fairy tales, encountering witches, warlocks, and dragons in search of parents who won't try to harm them.",
        "pageCount": 272
    },
    {
        "id": "mock-75",
        "title": "Septimus Heap: Magyk",
        "author": "Angie Sage",
        "publishedYear": 2005,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Cozy, richly detailed English wizarding tale filled with charm, eccentric wizards, magical boggarts, and identity secrets.",
        "interestConnection": "Wizard apprentice, wizard castle, dark necromancer plot, magical creatures, and royal baby secret.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Dark necromancer spells", "Mild magical dungeon peril"],
        "readingLevel": "Grade 4-6 / 890L",
        "genre": "Magical Fantasy",
        "isbn": "9780060577315",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780060577315-M.jpg",
        "description": "The seventh son of a seventh son disappears the night he is born. On the same night, his father finds an abandoned baby girl in the snow, beginning a sweeping magical adventure.",
        "pageCount": 576
    },
    {
        "id": "mock-76",
        "title": "Gregor the Overlander",
        "author": "Suzanne Collins",
        "publishedYear": 2003,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Gripping subterranean fantasy by Suzanne Collins exploring prophecy, duty, underground civilizations, and protecting younger siblings.",
        "interestConnection": "Subterranean world beneath NYC, giant talking bats and bats, sword prophecy, and sibling loyalty.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Underground giant insect battles", "Creepy crawling creatures"],
        "readingLevel": "Grade 5-7 / 680L",
        "genre": "Action Fantasy",
        "isbn": "9780439678131",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780439678131-M.jpg",
        "description": "When eleven-year-old Gregor falls through a grate in the laundry room of his apartment building, he drops into the dark Underland beneath New York City, where giant bats, spiders, and rats rule.",
        "pageCount": 320
    },
    {
        "id": "mock-77",
        "title": "Artemis Fowl",
        "author": "Eoin Colfer",
        "publishedYear": 2001,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Clever sci-fi fantasy caper matching a twelve-year-old criminal mastermind against high-tech fairy law enforcement.",
        "interestConnection": "High-tech fairies, LEPRecon tactical teams, twelve-year-old genius billionaire, gold heist, and tech gadgets.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Troll siege on mansion", "Kidnapping fairy captain for ransom"],
        "readingLevel": "Grade 5-7 / 600L",
        "genre": "Sci-Fi Fantasy Caper",
        "isbn": "9781423124528",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781423124528-M.jpg",
        "description": "Twelve-year-old criminal mastermind Artemis Fowl discovers that fairies are real, armed with dangerous technology, and living underground, so he decides to kidnap one to restore his family fortune.",
        "pageCount": 288
    },
    {
        "id": "mock-78",
        "title": "The Spiderwick Chronicles: The Field Guide",
        "author": "Tony DiTerlizzi & Holly Black",
        "publishedYear": 2003,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Fast, beautifully illustrated portal fantasy about sibling dynamics, Victorian faerie field guides, and hidden wonders.",
        "interestConnection": "Hidden attic library, faerie field guide, boggart pranks, Victorian estate, and brother teamwork.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Mischievous brownie and boggart curses"],
        "readingLevel": "Grade 4-6 / 600L",
        "genre": "Illustrated Fantasy",
        "isbn": "9781442486927",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781442486927-M.jpg",
        "description": "When the Grace children move into the dilapidated Spiderwick Estate, Jared discovers a secret library and Arthur Spiderwick's Field Guide to the Fantastical World Around You.",
        "pageCount": 128
    },
    {
        "id": "mock-79",
        "title": "The Iron Trial",
        "author": "Holly Black & Cassandra Clare",
        "publishedYear": 2014,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Action-packed magic school series with a disabled protagonist (limping leg), turning dark wizard tropes on their head.",
        "interestConnection": "Magical subterranean academy, elemental spellcasting, copper year trials, anti-chosen-one twist, and loyal friends.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Elemental magic combat", "Identity twist danger"],
        "readingLevel": "Grade 4-7 / 800L",
        "genre": "Magic Academy Fantasy",
        "isbn": "9780545522250",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780545522250-M.jpg",
        "description": "Callum Hunt has been warned his whole life to fail the entrance exams to the Magisterium magic school. But despite his best efforts to fail, his magic manifests and he is selected.",
        "pageCount": 304
    },
    {
        "id": "mock-80",
        "title": "Tristan Strong Punches a Hole in the Sky",
        "author": "Kwame Mbalia",
        "publishedYear": 2019,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Coretta Scott King Honor winner celebrating African American folklore and West African mythology, healing from grief through storytelling.",
        "interestConnection": "John Henry, Brer Rabbit, Anansi the Weaver, West African gods, boxing gloves, and repairing the sky.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Passing of childhood friend in bus crash", "Iron monster battles"],
        "readingLevel": "Grade 5-7 / 680L",
        "genre": "Mythological Fantasy",
        "isbn": "9781368039932",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781368039932-M.jpg",
        "description": "Seventh grader Tristan Strong is sent to his grandparents' Alabama farm after a boxing defeat and losing his best friend. When a creature steals his friend's journal, Tristan punches a hole into a magical realm.",
        "pageCount": 496
    },
    {
        "id": "mock-81",
        "title": "Aru Shah and the End of Time",
        "author": "Roshani Chokshi",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Witty Hindu mythology adventure filled with humor, sisterhood, heroic quests, and facing up to one's mistakes.",
        "interestConnection": "Hindu mythology, lighting forbidden lamp, museum adventures, Mahabharata reincarnation, and snarky pigeon guide.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Demon Sleeper threat", "Frozen mother rescue mission"],
        "readingLevel": "Grade 5-7 / 720L",
        "genre": "Mythological Fantasy",
        "isbn": "9781368012355",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781368012355-M.jpg",
        "description": "Twelve-year-old Aru Shah has a habit of stretching the truth. When classmates dare her to light the cursed Lamp of Bharata at her museum home, she accidentally frees an ancient demon.",
        "pageCount": 368
    },
    {
        "id": "mock-82",
        "title": "The Serpent's Secret",
        "author": "Sayantani DasGupta",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Energetic Bengali folklore fantasy celebrating science, storytelling, demon-fighting princesses, and interdimensional flying horses.",
        "interestConnection": "Bengali folktales, demon rakkhosh battles, string theory science, flying horses, and sisterly heroism.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Demon rakkhosh attacks"],
        "readingLevel": "Grade 4-6 / 710L",
        "genre": "Folklore Sci-Fantasy",
        "isbn": "9781338185706",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781338185706-M.jpg",
        "description": "Kiranmala is just an ordinary sixth grader in New Jersey until demon rakkhosh ransack her kitchen on her twelfth birthday, revealing she is secretly an Indian princess from another dimension.",
        "pageCount": 368
    },
    {
        "id": "mock-83",
        "title": "Dragon Pearl",
        "author": "Yoon Ha Lee",
        "publishedYear": 2019,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Edgar Award winner blending Korean mythology (gumiho fox spirits) with space opera, battle cruisers, and sibling loyalty.",
        "interestConnection": "Shapeshifting fox spirit, space battlecruiser cadet, Korean mythology in space, terraforming magic, and mystery.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Space combat", "Brother accused of desertion"],
        "readingLevel": "Grade 5-7 / 760L",
        "genre": "Sci-Fi Space Opera / Mythology",
        "isbn": "9781368013352",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781368013352-M.jpg",
        "description": "Thirteen-year-old Min comes from a family of fox spirits. When word arrives that her older brother has deserted the Space Forces to search for the mythical Dragon Pearl, Min runs away to clear his name.",
        "pageCount": 320
    },
    {
        "id": "mock-84",
        "title": "Paola Santiago and the River of Tears",
        "author": "Tehlor Kay Mejia",
        "publishedYear": 2020,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Science-minded middle-school mystery tackling the La Llorona myth with scientific deduction, ghost-hunting tech, and friendship.",
        "interestConnection": "La Llorona legend, scientific method vs magic, Arizona river mystery, smart flashlights, and best friends.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Missing friend mystery", "Spooky river phantom folklore"],
        "readingLevel": "Grade 5-7 / 740L",
        "genre": "Urban Fantasy / Folklore",
        "isbn": "9781368049177",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781368049177-M.jpg",
        "description": "Space-obsessed Paola Santiago relies on hard science, refusing to believe in her mother's Mexican ghost stories. But when her best friend disappears near the cursed Gila River, Paola must face the mythical River of Tears.",
        "pageCount": 384
    },
    {
        "id": "mock-85",
        "title": "Roller Girl",
        "author": "Victoria Jamieson",
        "publishedYear": 2015,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Newbery Honor graphic novel showing how physical resilience, learning to fall and get back up, and roller derby empower tween self-discovery.",
        "interestConnection": "Graphic novel, roller derby camp, falling down and getting up, changing friendships, and dying hair blue.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "None" },
        "contentWarnings": ["Roller derby sports bruises", "Friend drift"],
        "readingLevel": "Grade 4-6 / 440L",
        "genre": "Graphic Novel / Sports",
        "isbn": "9780525429678",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780525429678-M.jpg",
        "description": "For most of her twelve years, Astrid has done everything with her best friend Nicole. But after Astrid discovers junior roller derby camp, her summer becomes a fierce test of grit, bruises, and independence.",
        "pageCount": 240
    },
    {
        "id": "mock-86",
        "title": "Real Friends",
        "author": "Shannon Hale",
        "publishedYear": 2017,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Empathetic graphic memoir capturing elementary clique politics, anxiety, and learning how to find friends who love you for who you are.",
        "interestConnection": "Graphic novel, elementary school cliques, childhood anxiety, playground politics, and storytelling.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Exclusion by popular group", "Childhood anxiety tic behaviors"],
        "readingLevel": "Grade 3-6 / 350L",
        "genre": "Graphic Novel / Memoir",
        "isbn": "9781626727854",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781626727854-M.jpg",
        "description": "Shannon and Adrienne have been best friends since they were little. But one day Adrienne starts hanging out with the most popular girl in class, and Shannon must navigate shifting playground loyalties.",
        "pageCount": 224
    },
    {
        "id": "mock-87",
        "title": "Sunny Side Up",
        "author": "Jennifer L. Holm & Matthew Holm",
        "publishedYear": 2015,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Warm, sensitive graphic novel about a girl sent to a retirement village in Florida, exploring family substance abuse in a kid-appropriate way.",
        "interestConnection": "Graphic novel, Florida retirement home, alligator sightings, comic book reading, and sibling support.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Older brother substance abuse struggles (addressed with care and empathy)"],
        "readingLevel": "Grade 4-6 / 420L",
        "genre": "Graphic Novel / Family",
        "isbn": "9780545741651",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780545741651-M.jpg",
        "description": "Sunny Lewin is packed off to Florida to spend the summer with her grandfather in his retirement community, wondering why her parents sent her away while her older brother is in trouble back home.",
        "pageCount": 224
    },
    {
        "id": "mock-88",
        "title": "Allergic",
        "author": "Megan Wagner Lloyd & Michelle Mee Nutter",
        "publishedYear": 2021,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Delightful graphic novel about managing severe animal allergies, finding creative alternatives for companionship, and middle child syndrome.",
        "interestConnection": "Graphic novel, severe pet allergies, guinea pig and fish pets, middle child empathy, and neighborhood animal rescue.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "None" },
        "contentWarnings": ["Severe allergic reaction hospital visit"],
        "readingLevel": "Grade 3-6 / 380L",
        "genre": "Graphic Novel / Realistic",
        "isbn": "9781338568905",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781338568905-M.jpg",
        "description": "Maggie is thrilled to finally adopt a puppy of her own for her tenth birthday. But when she breaks out into hives at the shelter, she learns she is severely allergic to anything with fur.",
        "pageCount": 240
    },
    {
        "id": "mock-89",
        "title": "Hooky",
        "author": "Míriam Bonastre Tur",
        "publishedYear": 2021,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Super-popular webtoon graphic novel following twin witches who miss the magic bus and get swept into a conflict between witches and humans.",
        "interestConnection": "Graphic novel, twin witches, missing the bus, magical broomsticks, kingdom politics, and bakery friends.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Magical spell battles", "Kingdom rebellion danger"],
        "readingLevel": "Grade 5-7 / 500L",
        "genre": "Graphic Novel / Fantasy",
        "isbn": "9780358468301",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780358468301-M.jpg",
        "description": "Twin witch prodigies Dani and Dorian miss the bus to the magical academy on their first day, setting off a wild chain of misadventures as they search for an eccentric mentor in the human world.",
        "pageCount": 384
    },
    {
        "id": "mock-90",
        "title": "Lightfall: The Girl & the Galdurian",
        "author": "Tim Probert",
        "publishedYear": 2020,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Lushly illustrated, comforting fantasy adventure touching on generalized anxiety, friendship, and heroic purpose in an ancient world.",
        "interestConnection": "Graphic novel, glowing sun lantern, anxiety representation, giant friendly lizard knight, and ancient magic.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Shadow creature chases", "Anxiety panic feelings"],
        "readingLevel": "Grade 4-6 / 480L",
        "genre": "Graphic Novel / High Fantasy",
        "isbn": "9780062845306",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062845306-M.jpg",
        "description": "Deep in the mystical world of Irpa, Bea lives with her adoptive grandfather, the Pig Wizard. When he vanishes, Bea teams up with Cad, one of the last members of the peaceful Galdurian race.",
        "pageCount": 256
    },
    {
        "id": "mock-91",
        "title": "Bone: Out from Boneville",
        "author": "Jeff Smith",
        "publishedYear": 1995,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Epic graphic novel classic blending classic Disney comic humor (Carl Barks) with grand Lord of the Rings-scale fantasy mythology.",
        "interestConnection": "Graphic novel, quirky cousins, quiche-eating rat creatures, cow races, red dragon, and grand quest.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Cartoon rat creature combat", "Locust lord shadows"],
        "readingLevel": "Grade 4-7 / 420L",
        "genre": "Epic Fantasy / Graphic Novel",
        "isbn": "9780439706407",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780439706407-M.jpg",
        "description": "After being run out of Boneville, the three Bone cousins—Fone Bone, Phoney Bone, and Smiley Bone—get separated in a vast uncharted valley populated by monsters, princesses, and dragons.",
        "pageCount": 144
    },
    {
        "id": "mock-92",
        "title": "The Witch Boy",
        "author": "Molly Knox Ostertag",
        "publishedYear": 2017,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Heartwarming graphic novel subverting gender roles and family expectations: in a magical clan where girls are witches and boys are shapeshifters, Aster embraces magic.",
        "interestConnection": "Graphic novel, subverting family expectations, spellcraft, shapeshifting, demon monster rescue, and identity.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Corrupted shadow beast threat"],
        "readingLevel": "Grade 4-6 / 520L",
        "genre": "Graphic Novel / Fantasy",
        "isbn": "9781338089516",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781338089516-M.jpg",
        "description": "In thirteen-year-old Aster's family, all the girls are raised to be witches while boys are shapeshifters. Aster has not shifted yet, feeling drawn to witchcraft, and uses it when danger strikes his clan.",
        "pageCount": 224
    },
    {
        "id": "mock-93",
        "title": "Lumberjanes: Beware the Kitten Holy",
        "author": "Noelle Stevenson & Shannon Watters",
        "publishedYear": 2014,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Celebrates female friendship, scientific problem solving, and quirky wilderness camping with giant three-eyed foxes and river monsters.",
        "interestConnection": "Graphic novel, summer camp cabin, cryptids, anagram puzzles, girl power, and outdoor badges.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Mild", "themes": "None" },
        "contentWarnings": ["Camp supernatural monster chases"],
        "readingLevel": "Grade 4-6 / 490L",
        "genre": "Graphic Novel / Comedy",
        "isbn": "9781608866878",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781608866878-M.jpg",
        "description": "Five best friends spending the summer at Miss Qiunzella Thiskwin Penniquiqul Thistle Crumpet's Camp for Hardcore Lady-Types encounter supernatural river monsters, puzzles, and secret badges.",
        "pageCount": 128
    },
    {
        "id": "mock-94",
        "title": "Space Boy",
        "author": "Stephen McCranie",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Gentle, lyrical sci-fi graphic novel exploring deep space cryo-travel, synesthesia, grief, and adapting to life on Earth.",
        "interestConnection": "Graphic novel, deep space mining colony, cryo-sleep time jump, synesthesia colors of personalities, and Earth high school.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Leaving childhood home behind due to cryo-travel time dilation"],
        "readingLevel": "Grade 5-7 / 550L",
        "genre": "Graphic Novel / Sci-Fi",
        "isbn": "9781506706481",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781506706481-M.jpg",
        "description": "Amy sees everyone's personality as a unique flavor and color. When her family must relocate from a deep-space mining colony to Earth via a thirty-year cryo-sleep journey, she finds a boy with no flavor at all.",
        "pageCount": 256
    },
    {
        "id": "mock-95",
        "title": "The Boy at the Back of the Class",
        "author": "Onjali Q. Raúf",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Waterstones Prize-winning novel that helps kids understand the Syrian refugee crisis through playground kindness, pomegranate sweets, and standing up to prejudice.",
        "interestConnection": "Refugee welcoming, British classroom, pomegranate snacks, petitioning Queen Elizabeth, and true kindness.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Discussion of war refugee trauma", "Schoolyard bullying"],
        "readingLevel": "Grade 4-6 / 720L",
        "genre": "Realistic / Empathy",
        "isbn": "9781984850782",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781984850782-M.jpg",
        "description": "When a quiet new boy named Ahmet joins their class, four friends find out he is a Syrian refugee who fled war. When they learn he might be separated from his family, they launch a brave rescue plan.",
        "pageCount": 304
    },
    {
        "id": "mock-96",
        "title": "The Remarkable Journey of Coyote Sunrise",
        "author": "Dan Gemeinhart",
        "publishedYear": 2019,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Tender, joyful road trip novel about grief, memory boxes, healing after loss, and collecting eccentric travelers across America in a school bus.",
        "interestConnection": "Cross-country converted school bus, secret memory box retrieval, saved stray kitten, eccentric hitchhikers, and father-daughter bond.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Passing of mother and sisters in past car accident"],
        "readingLevel": "Grade 5-7 / 730L",
        "genre": "Road Trip / Realistic",
        "isbn": "9781250196705",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250196705-M.jpg",
        "description": "Twelve-year-old Coyote and her dad have lived on a converted school bus for five years since a car accident took her mother and sisters. When Coyote learns the park where they buried a memory box is being demolished, she hatches a scheme.",
        "pageCount": 352
    },
    {
        "id": "mock-97",
        "title": "The Honest Truth",
        "author": "Dan Gemeinhart",
        "publishedYear": 2015,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Intense, gripping trek about a boy with cancer climbing Mount Rainier with his loyal dog, emphasizing courage, friendship, and choosing to live.",
        "interestConnection": "Mountain climbing, Mount Rainier blizzard, loyal dog companion Beau, poetry in notebooks, and courage.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Terminal childhood cancer diagnosis journey", "Blizzard frostbite danger"],
        "readingLevel": "Grade 5-7 / 680L",
        "genre": "Adventure / Survival",
        "isbn": "9780545665735",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780545665735-M.jpg",
        "description": "Twelve-year-old Mark is sick of cancer treatments and hospital rooms. Armed with his camera, a notebook, and his faithful dog Beau, Mark runs away to fulfill his dream of summiting Mount Rainier.",
        "pageCount": 240
    },
    {
        "id": "mock-98",
        "title": "Look Both Ways",
        "author": "Jason Reynolds",
        "publishedYear": 2019,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "National Book Award finalist containing ten interconnected vignettes capturing the wild, hilarious, tender ten blocks kids walk home from school.",
        "interestConnection": "Walk home from school, urban neighborhood, school bus falling from sky metaphor, humorous escapades, and heart.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Passing parent illness mentioned", "Pranksters"],
        "readingLevel": "Grade 5-7 / 750L",
        "genre": "Interconnected Short Stories / Realistic",
        "isbn": "9781481438285",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781481438285-M.jpg",
        "description": "What happens after the bell rings? Ten hilarious, poignant stories reveal the secret lives, jokes, fears, and hopes of middle schoolers walking ten blocks home from school.",
        "pageCount": 208
    },
    {
        "id": "mock-99",
        "title": "The Beatryce Prophecy",
        "author": "Kate DiCamillo",
        "publishedYear": 2021,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Lyrical medieval tale about the subversive power of literacy, a girl who can read and write in a kingdom where it is forbidden, and a fiercely loyal goat.",
        "interestConnection": "Medieval kingdom, fierce demon goat Answelica, monk scriptorium, forbidden literacy, and gentle prophecy.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Soldiers hunting a child", "Fierce goat head-butting attacks"],
        "readingLevel": "Grade 4-6 / 640L",
        "genre": "Medieval / Lyrical Fantasy",
        "isbn": "9781536213614",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781536213614-M.jpg",
        "description": "In a time of war, a girl named Beatryce is found in a monastery barn curled next to Answelica, a notoriously ferocious goat. Though girls are forbidden to read, Beatryce knows letters and threatens the king's crown.",
        "pageCount": 256
    },
    {
        "id": "mock-100",
        "title": "Flora & Ulysses",
        "author": "Kate DiCamillo",
        "publishedYear": 2013,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Newbery Medal winner about a cynical girl, an incident with a vacuum cleaner, a flying squirrel who types poetry, and opening your heart to hope.",
        "interestConnection": "Comic book cynicism, superhero squirrel, typing poetry, vacuum cleaner accident, and eccentric neighbors.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "None" },
        "contentWarnings": ["Vacuum cleaner accident with squirrel (resolves into superpower)"],
        "readingLevel": "Grade 4-6 / 520L",
        "genre": "Humorous Fantasy / Graphic Hybrid",
        "isbn": "9780763660406",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780763660406-M.jpg",
        "description": "Flora Belle Buckman is a natural-born cynic who witnesses her neighbor’s runaway vacuum suck up a squirrel. To her surprise, the squirrel emerges with superpowers and begins typing poetry.",
        "pageCount": 240
    },
    {
        "id": "mock-101",
        "title": "The Miraculous Journey of Edward Tulane",
        "author": "Kate DiCamillo",
        "publishedYear": 2006,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Exquisitely written modern fairy tale about a haughty porcelain rabbit who learns empathy, humility, and love through a series of losses.",
        "interestConnection": "Porcelain rabbit toy, ocean voyage shipwreck, tramp campfire, stars, and learning to love.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Sickness and death of young child owner", "Broken porcelain repairs"],
        "readingLevel": "Grade 4-6 / 550L",
        "genre": "Modern Fairy Tale / Classic",
        "isbn": "9780763625894",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780763625894-M.jpg",
        "description": "Edward Tulane is a vain, cold porcelain rabbit owned by a girl who adores him. When he falls overboard on an ocean voyage, he embarks on an extraordinary journey through many hands.",
        "pageCount": 228
    },
    {
        "id": "mock-102",
        "title": "Ghost Boys",
        "author": "Jewell Parker Rhodes",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Empathetic, haunting exploration of police shootings, racial justice, and historical connections between modern boys and Emmett Till.",
        "interestConnection": "Ghost perspective, Emmett Till historical connection, toy gun misunderstanding, healing, and truth.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Police shooting of a 12-year-old holding a toy gun", "Emmett Till history"],
        "readingLevel": "Grade 5-7 / 560L",
        "genre": "Social Realism / Paranormal",
        "isbn": "9780316262286",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316262286-M.jpg",
        "description": "Twelve-year-old Jerome is shot by a police officer who mistakes his toy gun for a threat. As a ghost, Jerome observes the devastation unleashed on his family and community, guided by the spirit of Emmett Till.",
        "pageCount": 224
    },
    {
        "id": "mock-103",
        "title": "Towers Falling",
        "author": "Jewell Parker Rhodes",
        "publishedYear": 2016,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Compassionate, classroom-centered mystery exploring September 11 from the perspective of fifth graders born years after the tragedy.",
        "interestConnection": "September 11 historical classroom study, family homeless shelter resilience, Brooklyn neighborhoods, and unity.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["9/11 historical footage classroom discussions", "PTSD in veteran parent"],
        "readingLevel": "Grade 4-6 / 630L",
        "genre": "Historical / Contemporary",
        "isbn": "9780316262224",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316262224-M.jpg",
        "description": "Fifth grader Deja lives in a homeless shelter with her family. When her teacher starts a unit about the two towers that used to stand across the river, Deja discovers how history touches her own family.",
        "pageCount": 240
    },
    {
        "id": "mock-104",
        "title": "Stella by Starlight",
        "author": "Sharon M. Draper",
        "publishedYear": 2015,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Evocative, courage-filled historical novel about a young Black girl finding her voice and learning to write during the Depression-era Jim Crow South.",
        "interestConnection": "Jim Crow North Carolina, night writing under stars, typewriter dreams, community resistance, and bravery.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Ku Klux Klan cross-burning incident in opening", "Voter suppression intimidation"],
        "readingLevel": "Grade 5-7 / 740L",
        "genre": "Historical Fiction",
        "isbn": "9781442425309",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781442425309-M.jpg",
        "description": "Stella lives in the segregated town of Bumblebee, North Carolina. When the Ku Klux Klan burns a cross across the pond, Stella's community rallies together while she writes the truth under the stars.",
        "pageCount": 352
    },
    {
        "id": "mock-105",
        "title": "Blended",
        "author": "Sharon M. Draper",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Nuanced, musical exploration of mixed-race identity, split parents, classical piano, and police traffic stop trauma.",
        "interestConnection": "Classical piano competition, biracial identity, divorced parents switching weekly, and family love.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Police traffic stop incident with injury to family member"],
        "readingLevel": "Grade 5-7 / 610L",
        "genre": "Realistic Fiction",
        "isbn": "9781442495005",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781442495005-M.jpg",
        "description": "Eleven-year-old Isabella feels torn between two families, spending alternating weeks with her white mother in a modest home and her Black father in an opulent mansion, finding peace at the piano.",
        "pageCount": 336
    },
    {
        "id": "mock-106",
        "title": "The Epic Fail of Arturo Zamora",
        "author": "Pablo Cartaya",
        "publishedYear": 2017,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Joyous Pura Belpré Honor book about Cuban-American family solidarity, community activism, food, poetry, and defending neighborhood heritage from gentrification.",
        "interestConnection": "Cuban restaurant family, Jose Marti poetry, community city council activism, summer romance, and food.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "Mild", "themes": "None" },
        "contentWarnings": ["Abuela illness in hospital"],
        "readingLevel": "Grade 5-7 / 750L",
        "genre": "Realistic / Humor",
        "isbn": "9781101997239",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781101997239-M.jpg",
        "description": "Thirteen-year-old Arturo looks forward to spending the summer washing dishes at his abuela's Miami restaurant and playing basketball. But when a ruthless land developer threatens the restaurant, Arturo fights back.",
        "pageCount": 256
    },
    {
        "id": "mock-107",
        "title": "Merci Suárez Changes Gears",
        "author": "Meg Medina",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Newbery Medal-winning masterpiece depicting multigenerational Cuban-American family life, Alzheimer's compassion, and sixth-grade social complexities.",
        "interestConnection": "Multigenerational family compound, grandfather Alzheimer's care, private school scholarship, and bike riding.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Beloved grandfather's dementia symptoms progressing"],
        "readingLevel": "Grade 4-7 / 700L",
        "genre": "Realistic Fiction",
        "isbn": "9780763690496",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780763690496-M.jpg",
        "description": "Merci Suárez is a sixth-grade scholarship student at an elite private school in Florida who doesn't have the fancy clothes or vacations of her peers. At home, her beloved grandfather is starting to act strangely.",
        "pageCount": 384
    },
    {
        "id": "mock-108",
        "title": "When Stars Are Scattered",
        "author": "Victoria Jamieson & Omar Mohamed",
        "publishedYear": 2020,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "National Book Award Finalist graphic memoir about growing up in Dadaab refugee camp in Kenya, brotherly devotion, and the life-changing power of education.",
        "interestConnection": "Graphic novel, Dadaab refugee camp, caring for non-verbal brother Hassan, school dreams, and UN resettlement.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Refugee camp rationing and grief over missing mother"],
        "readingLevel": "Grade 4-7 / 530L",
        "genre": "Graphic Memoir / Nonfiction",
        "isbn": "9780525553908",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780525553908-M.jpg",
        "description": "Omar and his younger brother Hassan have spent most of their lives in Dadaab, a refugee camp in Kenya. When Omar gets the chance to attend school, he knows it's an opportunity to change their future.",
        "pageCount": 264
    },
    {
        "id": "mock-109",
        "title": "Clean Getaway",
        "author": "Nic Stone",
        "publishedYear": 2020,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Entertaining, educational road trip novel pairing an 11-year-old with his grandmother using the historic Green Book to explore Civil Rights milestones.",
        "interestConnection": "RV road trip, Green Book history, Civil Rights landmarks, treasure hunting, and grandmother secrets.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Grandmother dementia confusion", "Historical segregation discussions"],
        "readingLevel": "Grade 4-6 / 780L",
        "genre": "Road Trip / Historical Contemporary",
        "isbn": "9781984893017",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781984893017-M.jpg",
        "description": "William 'Scoob' Lamar takes off on an impromptu road trip in an RV with his eccentric grandmother G'ma, retracing a route through the American South she took decades earlier using the Green Book.",
        "pageCount": 240
    },
    {
        "id": "mock-110",
        "title": "From the Desk of Zoe Washington",
        "author": "Janae Marks",
        "publishedYear": 2020,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Empowering mystery blending baking dreams, justice reform, and an inquisitive twelve-year-old investigating her incarcerated biological father's innocence.",
        "interestConnection": "Cupcake baking bakery internship, criminal justice innocence investigation, letters to prison, and detective sleuthing.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Father wrongfully convicted of crime", "Secret letter correspondence"],
        "readingLevel": "Grade 4-6 / 660L",
        "genre": "Mystery / Contemporary",
        "isbn": "9780062875853",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062875853-M.jpg",
        "description": "On her twelfth birthday, aspiring baker Zoe Washington receives a letter from her biological father who has been in prison all her life. When he claims he is innocent, Zoe investigates the truth.",
        "pageCount": 304
    },
    {
        "id": "mock-111",
        "title": "The Parker Inheritance",
        "author": "Varian Johnson",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Coretta Scott King Author Honor mystery intertwining a modern treasure hunt with 1950s Jim Crow history, tennis champions, and restorative justice.",
        "interestConnection": "Hidden attic letter, municipal treasure hunt, tennis history, civil rights injustice mystery, and friendship.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Historical racial assault incident in 1950s flashback"],
        "readingLevel": "Grade 5-7 / 610L",
        "genre": "Mystery / Historical",
        "isbn": "9780545946179",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780545946179-M.jpg",
        "description": "When Candice finds a mysterious letter in an old attic in Lambert, South Carolina, she and her bookish neighbor Brandon set out to solve a riddle that could clear her grandmother's name and yield a fortune.",
        "pageCount": 352
    },
    {
        "id": "mock-112",
        "title": "Some Kind of Courage",
        "author": "Dan Gemeinhart",
        "publishedYear": 2016,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Heart-pounding historical Western adventure about a twelve-year-old orphan tracking down his beloved pony across the dangerous 1890 Washington wilderness.",
        "interestConnection": "Historical American frontier, horse trek, wilderness survival, Chinese-American friendship, and outlaw showdown.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Frontier outlaw peril and grizzly bear encounter"],
        "readingLevel": "Grade 5-7 / 720L",
        "genre": "Historical Western / Adventure",
        "isbn": "9780545753128",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780545753128-M.jpg",
        "description": "In 1890 Washington state, twelve-year-old Joseph Johnson has lost his entire family to typhoid fever. When his beloved pony is sold out from under him, Joseph sets off on an epic journey to get her back.",
        "pageCount": 256
    },
    {
        "id": "mock-113",
        "title": "The Vanderbeekers of 141st Street",
        "author": "Karina Yan Glaser",
        "publishedYear": 2017,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Delightful, cozy holiday family classic about five biracial siblings in Harlem working together with community charm to win over a grumpy landlord.",
        "interestConnection": "Harlem brownstone neighborhood, five inventive siblings, dog and bunny pets, music, and holiday baking.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "None" },
        "contentWarnings": ["Threat of lease eviction"],
        "readingLevel": "Grade 4-6 / 810L",
        "genre": "Family / Cozy Realistic",
        "isbn": "9780544876392",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780544876392-M.jpg",
        "description": "The Vanderbeekers have always lived in their beloved brownstone on 141st Street in Harlem. But just days before Christmas, their reclusive landlord refuses to renew their lease, prompting an elaborate charm offensive.",
        "pageCount": 304
    },
    {
        "id": "mock-114",
        "title": "Winterhouse",
        "author": "Ben Guterson",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Atmospheric, puzzle-filled winter mystery set in an opulent mountain hotel filled with an enormous library, anagrams, and cryptic history.",
        "interestConnection": "Grand winter hotel, anagram ciphers, secret library book, indoor ski hill, and sinister lineage.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Sinister occult book plot", "Mild suspense peril"],
        "readingLevel": "Grade 4-7 / 780L",
        "genre": "Mystery / Atmospheric",
        "isbn": "9781250123886",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250123886-M.jpg",
        "description": "Orphan Elizabeth Somers is unexpectedly sent to the enchanting Winterhouse Hotel for Christmas break, where she uncovers a secret cipher book in the library connected to the hotel’s sinister origins.",
        "pageCount": 384
    }
]

print(f"Group 1 complete: {len(GROUP_1_B)} books in part B")
