# Group 3 Part B: High School YA & Classics (Ages 14-17) - Books mock-254 to mock-300 (47 books)

GROUP_3_B = [
    {
        "id": "mock-254",
        "title": "I Must Betray You",
        "author": "Ruta Sepetys",
        "publishedYear": 2022,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Heart-stopping historical thriller set during the 1989 Romanian Revolution, exploring Communist surveillance, secret police coercion, and teenage courage to speak truth.",
        "interestConnection": "1989 Romanian Revolution, secret police informants, underground rock music, radio broadcast rebellion, and courage.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Secret police interrogation and torture intimidation", "Street protests and regime gunfire"],
        "readingLevel": "Grade 9-12 / 820L",
        "genre": "Historical Thriller",
        "isbn": "9781984836038",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781984836038-M.jpg",
        "description": "Romania, 1989. Seventeen-year-old Cristian Florescu is blackmailed by the Securitate into becoming an informant. Instead, Cristian decides to secretly use his position to drain the regime from within.",
        "pageCount": 336
    },
    {
        "id": "mock-255",
        "title": "Between Shades of Gray",
        "author": "Ruta Sepetys",
        "publishedYear": 2011,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Haunting, Carnegie Medal-nominated historical novel about a Lithuanian artist girl surviving Stalin's Siberian labor camps through art and quiet dignity.",
        "interestConnection": "Lithuanian history, Siberian labor camp survival, secret drawings on bark, family endurance, and hope.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Soviet NKVD deportation in cattle cars", "Starvation and disease in Siberian labor camp"],
        "readingLevel": "Grade 8-11 / 490L",
        "genre": "Historical Fiction",
        "isbn": "9780142420591",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780142420591-M.jpg",
        "description": "In 1941, fifteen-year-old Lina is arrested by Soviet secret police and deported with her mother and brother to an Arctic labor camp. Lina embeds secret messages in her art to reach her father’s camp.",
        "pageCount": 352
    },
    {
        "id": "mock-256",
        "title": "Salt to the Sea",
        "author": "Ruta Sepetys",
        "publishedYear": 2016,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Carnegie Medal-winning masterpiece illuminating the worst maritime disaster in history (the sinking of the Wilhelm Gustloff), tracking four diverse refugees fleeing Soviet advance.",
        "interestConnection": "WWII Baltic evacuation, Wilhelm Gustloff torpedo sinking, amber room art secret, and multi-perspective refugee resilience.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Submarine torpedo sinking of passenger ship with heavy casualties", "Wartime civilian trek hardships"],
        "readingLevel": "Grade 8-11 / 560L",
        "genre": "Historical Fiction",
        "isbn": "9780142423622",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780142423622-M.jpg",
        "description": "In 1945, thousands of refugees trek toward the Baltic coast to board the Wilhelm Gustloff for safety. When tragedy strikes in the icy sea, four young survivors must pull together to stay alive.",
        "pageCount": 400
    },
    {
        "id": "mock-257",
        "title": "The Fountains of Silence",
        "author": "Ruta Sepetys",
        "publishedYear": 2019,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Atmospheric, deeply researched historical novel set in Madrid under Franco's dictatorship in 1957, following an American photojournalist and a Spanish hotel maid uncovering stolen babies.",
        "interestConnection": "1957 Madrid under Franco, photojournalism through camera lens, stolen babies historical scandal, and secret police danger.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Dictatorship secret police intimidation", "Stolen infants historical reality"],
        "readingLevel": "Grade 9-12 / 670L",
        "genre": "Historical Drama",
        "isbn": "9780399160318",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399160318-M.jpg",
        "description": "Madrid, 1957. Eighteen-year-old Daniel Matheson arrives in Spain hoping to connect with his mother's homeland through photography. He meets Ana, whose family lives in the shadows of the Spanish Civil War.",
        "pageCount": 512
    },
    {
        "id": "mock-258",
        "title": "The Book Thief",
        "author": "Markus Zusak",
        "publishedYear": 2005,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Poetic, unforgettable literary classic narrated by Death, about a foster girl in Nazi Germany who steals books to share with her neighbors and the Jewish man hidden in her basement.",
        "interestConnection": "Narrated by Death, accordion music, stealing books from mayor's library, hiding a Jewish fist-fighter in basement, and power of words.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["WWII Allied bombing of residential street with casualties", "Holocaust death march in town"],
        "readingLevel": "Grade 8-12 / 730L",
        "genre": "Historical Fiction Masterpiece",
        "isbn": "9780375842207",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780375842207-M.jpg",
        "description": "Narrated by Death, this is the story of Liesel Meminger, a foster girl living outside Munich in 1939 who steals books to feed her soul, sharing them with the Jewish boxer hiding in her basement.",
        "pageCount": 552
    },
    {
        "id": "mock-259",
        "title": "I Am the Messenger",
        "author": "Markus Zusak",
        "publishedYear": 2002,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Printz Honor mystery following an underage cab driver who stops a bank robbery and starts receiving playing cards with cryptic addresses to help strangers.",
        "interestConnection": "Playing cards with cryptic clues, suburban taxi driving, random acts of intervention, moral awakening, and coffee-drinking dog.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Confronting abusive husband with empty gun", "Occasional mature profanity"],
        "readingLevel": "Grade 9-12 / 640L",
        "genre": "Contemporary Mystery / Philosophy",
        "isbn": "9780375836671",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780375836671-M.jpg",
        "description": "Ed Kennedy is an underage cabdriver with no prospects until he accidentally foils a bank robbery. Then the first playing card arrives in the mail, sending him on a mission to change lives.",
        "pageCount": 360
    },
    {
        "id": "mock-260",
        "title": "Night",
        "author": "Elie Wiesel",
        "publishedYear": 1956,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Nobel Laureate's essential, devastating memoir of surviving Auschwitz and Buchenwald, exploring the loss of innocence, faith, and the responsibility to bear witness.",
        "interestConnection": "Firsthand Holocaust testimony, father-son bond in camp, bearing witness to history, Nobel Peace Prize author, and human dignity.",
        "maturityScores": { "violence": "Mature", "language": "Clean", "romance": "None", "themes": "Mature" },
        "contentWarnings": ["Firsthand Holocaust concentration camp genocide and starvation"],
        "readingLevel": "Grade 9-12 / 570L",
        "genre": "Memoir Classic / Holocaust",
        "isbn": "9780374500016",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780374500016-M.jpg",
        "description": "An unforgettable record of a terrified young boy as he enters a world of absolute horror, losing his mother, sister, and father in the Nazi death camps, and fighting to retain his humanity.",
        "pageCount": 120
    },
    {
        "id": "mock-261",
        "title": "Born a Crime: Stories from a South African Childhood",
        "author": "Trevor Noah",
        "publishedYear": 2016,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Hilarious, sharp, and moving autobiography detailing childhood in apartheid South Africa, linguistic chameleon skills, and his fearless, fiercely devout mother.",
        "interestConnection": "Apartheid South Africa history, languages and cultural chameleon skills, DJ party hustle, and heroic mother.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Apartheid racial segregation and violence", "Domestic abuse by stepfather"],
        "readingLevel": "Grade 9-12 / 780L",
        "genre": "Autobiography / Humor",
        "isbn": "9780399588174",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399588174-M.jpg",
        "description": "Trevor Noah’s unlikely path from apartheid South Africa to The Daily Show began with a criminal act: his birth to a white Swiss father and Black Xhosa mother, punishable by five years in prison.",
        "pageCount": 304
    },
    {
        "id": "mock-262",
        "title": "Educated: A Memoir",
        "author": "Tara Westover",
        "publishedYear": 2018,
        "recommendedAgeMin": 15,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Extraordinary memoir of an isolated survivalist upbringing in the Idaho mountains, teaching herself advanced math and grammar to enter college at seventeen.",
        "interestConnection": "Idaho mountain scrap yard, survivalist family, self-taught education breakthrough, Cambridge and Harvard studies, and independence.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "None", "themes": "Mature" },
        "contentWarnings": ["Severe family domestic abuse by older brother", "Severe scrap yard industrial injuries"],
        "readingLevel": "Grade 10-12 / 830L",
        "genre": "Memoir Masterpiece",
        "isbn": "9780399590504",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399590504-M.jpg",
        "description": "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her quest for knowledge transformed her, leading to a PhD from Cambridge.",
        "pageCount": 352
    },
    {
        "id": "mock-263",
        "title": "I Am Malala",
        "author": "Malala Yousafzai",
        "publishedYear": 2013,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Inspiring memoir of the youngest Nobel Peace Prize laureate who stood up to the Taliban for girls' education rights in Pakistan's Swat Valley.",
        "interestConnection": "Swat Valley Pakistan, school championing, Taliban resistance, speech to United Nations, and girls' education empowerment.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Taliban bus assassination attempt and critical gunshot injury recovery"],
        "readingLevel": "Grade 7-10 / 1000L",
        "genre": "Memoir / Human Rights",
        "isbn": "9780316322409",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316322409-M.jpg",
        "description": "When the Taliban took control of the Swat Valley in Pakistan, one girl spoke out. Malala refused to be silenced and fought for her right to an education, surviving a point-blank gunshot.",
        "pageCount": 352
    },
    {
        "id": "mock-264",
        "title": "Persepolis: The Story of a Childhood",
        "author": "Marjane Satrapi",
        "publishedYear": 2000,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Brilliant, candid graphic memoir of growing up in Tehran during the 1979 Islamic Revolution and the Iran-Iraq War with rebellious humor and punk rock spirit.",
        "interestConnection": "Graphic novel, Tehran punk rock cassettes, 1979 Iranian Revolution, family resistance, and teenage defiance.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Wartime missile bombing of neighborhood", "Execution of political dissidents"],
        "readingLevel": "Grade 8-11 / 740L",
        "genre": "Graphic Memoir / History",
        "isbn": "9780375714573",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780375714573-M.jpg",
        "description": "Marjane Satrapi's graphic memoir tells the story of her life in Tehran from ages six to fourteen, years that saw the overthrow of the Shah's regime, the triumph of the Islamic Revolution, and war with Iraq.",
        "pageCount": 160
    },
    {
        "id": "mock-265",
        "title": "Persepolis 2: The Story of a Return",
        "author": "Marjane Satrapi",
        "publishedYear": 2004,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Honest, poignant sequel tracing high school years in Vienna as an expatriate, homelessness, culture shock, and returning to university in Tehran.",
        "interestConnection": "Graphic novel, Austrian boarding school expatriate, identity crisis, art school student, and independence.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Moderate", "themes": "Mature" },
        "contentWarnings": ["Depression and temporary homelessness in Vienna", "Moral police harassment at university"],
        "readingLevel": "Grade 9-12 / 760L",
        "genre": "Graphic Memoir / Coming of Age",
        "isbn": "9780375714665",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780375714665-M.jpg",
        "description": "Sent to Vienna to escape the war in Iran, Marjane navigates the teenage hurdles of boarding school, heartbreak, and culture shock before returning home to attend art school.",
        "pageCount": 192
    },
    {
        "id": "mock-266",
        "title": "Just Mercy (Adapted for Young Adults)",
        "author": "Bryan Stevenson",
        "publishedYear": 2018,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Inspiring, transformative account of Equal Justice Initiative founder Bryan Stevenson defending the wrongfully convicted, juvenile lifers, and death row prisoners.",
        "interestConnection": "Civil rights legal defense, Walter McMillian innocence case, ending juvenile life without parole, and compassionate justice.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Death row executions discussed historically", "Wrongful incarceration and systemic bias"],
        "readingLevel": "Grade 7-10 / 920L",
        "genre": "Memoir / Legal Nonfiction",
        "isbn": "9780525580034",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780525580034-M.jpg",
        "description": "Bryan Stevenson was a young lawyer when he founded the Equal Justice Initiative, a legal practice dedicated to defending those most in need. This is the inspiring story of his fight for justice.",
        "pageCount": 288
    },
    {
        "id": "mock-267",
        "title": "The 57 Bus",
        "author": "Dashka Slater",
        "publishedYear": 2017,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Stonewall Book Award winner exploring a real-life hate crime on an Oakland bus, restorative justice, juvenile sentencing, and forgiveness between two teenagers.",
        "interestConnection": "True story on Oakland 57 bus, agender teen Sasha, restorative justice letters, and juvenile sentencing reform.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Skirting burned with lighter resulting in severe hospital burn treatments"],
        "readingLevel": "Grade 8-11 / 930L",
        "genre": "Narrative Nonfiction / True Crime",
        "isbn": "9780374303235",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780374303235-M.jpg",
        "description": "One afternoon in Oakland, California, two high school students who lived in vastly different worlds crossed paths on the 57 bus. A single reckless prank left one burned and the other facing life in prison.",
        "pageCount": 320
    },
    {
        "id": "mock-268",
        "title": "All American Boys",
        "author": "Jason Reynolds & Brendan Kiely",
        "publishedYear": 2015,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Coretta Scott King Author Honor dual-perspective novel about a Black teen beaten by police for a mistaken shoplifting accusation and his white classmate who witnesses it.",
        "interestConnection": "Dual perspective, high school basketball, street art murals, student protest march, and allyship.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Police beating assault of teenager outside bodega", "Hospital recovery"],
        "readingLevel": "Grade 8-11 / 770L",
        "genre": "Contemporary Social Realism",
        "isbn": "9781481463331",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781481463331-M.jpg",
        "description": "Rashad is brutally assaulted by a police officer who mistakes him for a shoplifter. Quinn, a varsity basketball teammate of Rashad's, witnesses the beating, committed by his best friend's older brother.",
        "pageCount": 320
    },
    {
        "id": "mock-269",
        "title": "Dear Edward",
        "author": "Ann Napolitano",
        "publishedYear": 2020,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Profound, heart-healing novel about a twelve-year-old boy who is the sole survivor of a commercial plane crash, learning how to carry grief and live for others.",
        "interestConnection": "Commercial flight tragedy survivor, secret passenger letter storage in garage, roller derby friend, and healing.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Commercial airline crash catastrophe with mass casualties", "Sole survivor grief"],
        "readingLevel": "Grade 9-12 / 810L",
        "genre": "Contemporary Fiction / Grief",
        "isbn": "9781984854780",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781984854780-M.jpg",
        "description": "Twelve-year-old Edward Adler boards a flight to Los Angeles with his parents and brother. When the plane crashes, Edward is the sole survivor, struggling to find his place in a world where everyone else is gone.",
        "pageCount": 352
    },
    {
        "id": "mock-270",
        "title": "Dune",
        "author": "Frank Herbert",
        "publishedYear": 1965,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Monumental sci-fi epic exploring desert ecology, political statecraft, religious messianism, resource exploitation (spice), and human willpower.",
        "interestConnection": "Desert planet Arrakis, giant sandworms, spice melange, Bene Gesserit mental discipline, and Fremen ecology.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Political assassinations and Harkonnen brutality", "Crysknife ritual combat"],
        "readingLevel": "Grade 9-12 / 800L",
        "genre": "Sci-Fi Epic Masterpiece",
        "isbn": "9780441172719",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780441172719-M.jpg",
        "description": "Set on the desert planet Arrakis, Dune is the story of Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only commodity of value is the spice melange.",
        "pageCount": 688
    },
    {
        "id": "mock-271",
        "title": "Dune Messiah",
        "author": "Frank Herbert",
        "publishedYear": 1969,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Fascinating deconstruction of the 'hero's journey', showing the tragic collateral damage of uncontrolled jihad and absolute prophetic vision.",
        "interestConnection": "Prophetic prescience, Face Dancer shapeshifters, ghola resurrection, Arrakis palace conspiracy, and moral reckoning.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Stone burner atomic blinding hazard", "Palace assassination plots"],
        "readingLevel": "Grade 9-12 / 820L",
        "genre": "Sci-Fi Philosophical Epic",
        "isbn": "9780441172696",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780441172696-M.jpg",
        "description": "Twelve years after seizing the imperial throne, Paul Atreides is worshipped as a messiah. Facing conspiracies from the Spacing Guild and Bene Gesserit, Paul navigates the terrifying visions of his prescience.",
        "pageCount": 336
    },
    {
        "id": "mock-272",
        "title": "Fahrenheit 451",
        "author": "Ray Bradbury",
        "publishedYear": 1953,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Essential dystopian classic about book burning, state censorship, screen addiction, and individuals who memorize literature to preserve human memory.",
        "interestConnection": "Firemen burning books, mechanical hound, seashell radio ear thimbles, parlor television walls, and walking books.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Flamethrower destruction of homes and books", "Mechanical hound venom needle"],
        "readingLevel": "Grade 8-11 / 890L",
        "genre": "Dystopian Classic",
        "isbn": "9781451673319",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781451673319-M.jpg",
        "description": "Guy Montag is a fireman whose job is to start fires: burning books, which are forbidden. But when he meets an eccentric young neighbor who loves ideas, Montag begins questioning everything.",
        "pageCount": 256
    },
    {
        "id": "mock-273",
        "title": "The Martian Chronicles",
        "author": "Ray Bradbury",
        "publishedYear": 1950,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Lyrical, haunting suite of interconnected science-fiction stories examining American colonization, displacement, nostalgia, and nuclear self-destruction.",
        "interestConnection": "Martian canal cities, crystal houses, telepathic Martians, rocket expeditions, and poetic reflections on humanity.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Extinction of Martian race by chicken pox virus", "Nuclear war on Earth seen from Mars"],
        "readingLevel": "Grade 8-11 / 740L",
        "genre": "Sci-Fi Classic / Short Stories",
        "isbn": "9781451678192",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781451678192-M.jpg",
        "description": "A poetic masterpiece tracking humanity’s repeated attempts to colonize Mars, fleeing a war-threatened Earth only to find Martian canal cities haunted by dreams, music, and echoes of their own flaws.",
        "pageCount": 256
    },
    {
        "id": "mock-274",
        "title": "1984",
        "author": "George Orwell",
        "publishedYear": 1949,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Defining masterpiece on totalitarian surveillance, doublethink, alteration of historical records, newspeak, and preserving objective truth.",
        "interestConnection": "Big Brother, telescreen surveillance, Ministry of Truth record altering, thought police, and fighting for individual thought.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Psychological re-education and torture in Ministry of Love (Room 101 rats)"],
        "readingLevel": "Grade 9-12 / 1090L",
        "genre": "Dystopian Classic Masterpiece",
        "isbn": "9780451524935",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780451524935-M.jpg",
        "description": "Winston Smith works for the Ministry of Truth in London, rewriting history to satisfy the Party. Yearning for truth and freedom, he begins a forbidden diary and love affair under the gaze of Big Brother.",
        "pageCount": 328
    },
    {
        "id": "mock-275",
        "title": "Animal Farm",
        "author": "George Orwell",
        "publishedYear": 1945,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Accessible, brilliant political beast fable allegorizing the Russian Revolution, showing how totalitarian corruption subverts egalitarian ideals.",
        "interestConnection": "Animal rebellion on farm, commandment alterations, pig leadership corruption, Boxer the horse loyalty, and satire.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Farm animals purge and execution of confessors", "Betrayal of loyal cart-horse Boxer"],
        "readingLevel": "Grade 7-10 / 1170L",
        "genre": "Political Satire / Beast Fable",
        "isbn": "9780451526342",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780451526342-M.jpg",
        "description": "Tired of human mistreatment, the animals of Manor Farm revolt and establish Animal Farm, where all animals are equal. But the cunning pigs slowly alter the rules until some become more equal than others.",
        "pageCount": 144
    },
    {
        "id": "mock-276",
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "publishedYear": 1932,
        "recommendedAgeMin": 15,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Visionary classic warning against technocratic pleasure-control, genetic predetermination, state consumerism, and exchanging pain for superficial euphoria.",
        "interestConnection": "Hatchery genetic castes (Alpha to Epsilon), soma mood drugs, feelies consumerism, and Shakespearean moral rebellion.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Moderate", "themes": "Mature" },
        "contentWarnings": ["State conditioning of human embryos", "Hedonistic social programming"],
        "readingLevel": "Grade 10-12 / 870L",
        "genre": "Dystopian Classic Masterpiece",
        "isbn": "9780060850524",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780060850524-M.jpg",
        "description": "In a futuristic World State, citizens are engineered into castes, conditioned to consume, and pacified with the drug soma. When John the Savage is brought to London, he rejects the synthetic utopia.",
        "pageCount": 288
    },
    {
        "id": "mock-277",
        "title": "Lord of the Flies",
        "author": "William Golding",
        "publishedYear": 1954,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Nobel Prize classic exploring the fragility of democratic civilization, the descent into primal tribalism, mob mentality, and the loss of innocence.",
        "interestConnection": "Deserted tropical island, conch shell order, signal fire atop mountain, beast paranoia, and spear hunting.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Brutal mob killing of Simon and boulder murder of Piggy"],
        "readingLevel": "Grade 8-11 / 770L",
        "genre": "Allegorical Classic",
        "isbn": "9780399501487",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399501487-M.jpg",
        "description": "When a plane crashes on an uninhabited island, a group of stranded British schoolboys attempt to govern themselves. Order unravels into savage tribalism under the influence of fear and cruelty.",
        "pageCount": 224
    },
    {
        "id": "mock-278",
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "publishedYear": 1960,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Pulitzer Prize classic exploring childhood empathy, racial injustice in 1930s Alabama, moral courage in the courtroom, and understanding others by walking in their shoes.",
        "interestConnection": "Scout Finch perspective, Boo Radley mystery, Atticus Finch courtroom defense, tree hollow treasures, and courage.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Trial of false rape accusation against Tom Robinson", "Historical racial slurs of 1930s South"],
        "readingLevel": "Grade 8-11 / 870L",
        "genre": "Southern Gothic / American Classic",
        "isbn": "9780060935467",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780060935467-M.jpg",
        "description": "Growing up in Maycomb, Alabama, six-year-old Scout Finch learns about justice, prejudice, and empathy as her attorney father Atticus defends an innocent Black man accused of a terrible crime.",
        "pageCount": 336
    },
    {
        "id": "mock-279",
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "publishedYear": 1951,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Iconic coming-of-age portrait of adolescent alienation, grief over a deceased sibling, protecting childhood innocence, and longing for authentic connection.",
        "interestConnection": "Holden Caulfield red hunting hat, NYC wandering, Central Park ducks in winter, museum exhibits, and little sister Phoebe.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Cigarette smoking and underage drinking", "Mental exhaustion and grief breakdown"],
        "readingLevel": "Grade 9-12 / 790L",
        "genre": "Coming of Age Classic",
        "isbn": "9780316769488",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316769488-M.jpg",
        "description": "After being expelled from prep school, sixteen-year-old Holden Caulfield spends three solitary days wandering New York City, wrestling with phoniness, grief, and the loss of innocence.",
        "pageCount": 277
    },
    {
        "id": "mock-280",
        "title": "Of Mice and Men",
        "author": "John Steinbeck",
        "publishedYear": 1937,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Devastatingly moving tragedy about the brotherhood between migrant farmworkers, the pursuit of the American dream, loneliness, and intellectual disability.",
        "interestConnection": "Great Depression migrant labor, dreaming of rabbit farm, George and Lennie brotherhood, Salinas Valley, and tragedy.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "None", "themes": "Mature" },
        "contentWarnings": ["Accidental crushing death of puppy and woman", "Mercy killing finale"],
        "readingLevel": "Grade 8-11 / 630L",
        "genre": "American Literary Tragedy",
        "isbn": "9780140177398",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780140177398-M.jpg",
        "description": "George Milton and Lennie Small are two migrant workers during the Great Depression who dream of owning a piece of land. But Lennie's gentle childlike mind combined with immense physical strength leads to heartbreak.",
        "pageCount": 107
    },
    {
        "id": "mock-281",
        "title": "The Pearl",
        "author": "John Steinbeck",
        "publishedYear": 1947,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Compact, powerful parable examining how sudden wealth corrupts human relationships, colonial exploitation, and the destructive nature of greed.",
        "interestConnection": "Pearl diving in Baja California, scorpions, colonial doctor refusal, canoe chase, and returning the pearl to sea.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Scorpion sting of baby", "Gunfire confrontation resulting in infant casualty"],
        "readingLevel": "Grade 7-10 / 1010L",
        "genre": "Parable / Classic Novella",
        "isbn": "9780140177374",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780140177374-M.jpg",
        "description": "Kino, an impoverished Mexican pearl diver, finds the greatest pearl in the world. Instead of bringing salvation and healing for his baby, the pearl attracts greed, betrayal, and violence.",
        "pageCount": 96
    },
    {
        "id": "mock-282",
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "publishedYear": 1925,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Masterpiece of poetic prose dissecting the Roaring Twenties, the mirage of the American dream, social class snobbery, and romantic obsession.",
        "interestConnection": "Jazz Age Long Island, lavish Gatsby mansion parties, green light at dock, yellow Rolls-Royce, and tragic obsession.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Moderate", "themes": "Moderate" },
        "contentWarnings": ["Car hit-and-run fatal accident", "Pool murder-suicide ending"],
        "readingLevel": "Grade 9-12 / 1070L",
        "genre": "Jazz Age Classic Masterpiece",
        "isbn": "9780743273565",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780743273565-M.jpg",
        "description": "Narrated by Nick Carraway, this is the story of enigmatic millionaire Jay Gatsby and his quixotic passion for Daisy Buchanan amidst the glamour and hollow illusion of the Jazz Age.",
        "pageCount": 180
    },
    {
        "id": "mock-283",
        "title": "Frankenstein",
        "author": "Mary Shelley",
        "publishedYear": 1818,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Foundational science-fiction masterpiece written by an 18-year-old woman, examining scientific hubris, the ethical responsibility of creators, societal prejudice, and loneliness.",
        "interestConnection": "Galvanism science experiments, creature yearning for empathy, Arctic ice chase, Gothic atmosphere, and ethics.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Creature vengeance strangling murders", "Grave-robbing for anatomical parts"],
        "readingLevel": "Grade 8-12 / 1170L",
        "genre": "Gothic Science Fiction Classic",
        "isbn": "9780486282114",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780486282114-M.jpg",
        "description": "Obsessed with unlocking the secret of life, Victor Frankenstein animates a creature fashioned from human remains. Horrified by what he made, Victor abandons the creature, sparking a tragic cycle of revenge.",
        "pageCount": 280
    },
    {
        "id": "mock-284",
        "title": "Dracula",
        "author": "Bram Stoker",
        "publishedYear": 1897,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Epistolary Gothic classic contrasting Victorian technological progress (shorthand, phonographs, blood transfusions) with ancient folklore and teamwork against evil.",
        "interestConnection": "Transylvania castle, phonograph journals, vampire hunter Van Helsing, garlic and stakes, and Victorian science.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Vampiric blood-drinking attacks", "Mental asylum Renfield behavior"],
        "readingLevel": "Grade 9-12 / 1060L",
        "genre": "Gothic Horror Classic",
        "isbn": "9780486411095",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780486411095-M.jpg",
        "description": "Told through letters and diaries, Count Dracula travels from Transylvania to London in search of new blood, pursued by a band of courageous friends led by Professor Van Helsing.",
        "pageCount": 418
    },
    {
        "id": "mock-285",
        "title": "Jane Eyre",
        "author": "Charlotte Brontë",
        "publishedYear": 1847,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Fiercely feminist Victorian classic celebrating female moral integrity, intellectual independence, overcoming orphan abuse, and true spiritual equality.",
        "interestConnection": "Gothic manor Thornfield Hall, resilient orphan heroine, moral independence, attic secret mystery, and love.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Moderate", "themes": "Moderate" },
        "contentWarnings": ["Lowood school typhoid epidemic and child mortality", "Attic madwoman Bertha Mason fires"],
        "readingLevel": "Grade 8-12 / 890L",
        "genre": "Victorian Gothic Romance Classic",
        "isbn": "9780141441146",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780141441146-M.jpg",
        "description": "Orphaned Jane Eyre endures a harsh boarding school before becoming governess at mysterious Thornfield Hall, where her fierce moral independence is tested by the enigmatic Edward Rochester.",
        "pageCount": 507
    },
    {
        "id": "mock-286",
        "title": "Wuthering Heights",
        "author": "Emily Brontë",
        "publishedYear": 1847,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Stormy, wild masterpiece exploring generational vengeance, wild Yorkshire moors, the destructive nature of obsessive passion, and ultimate forgiveness.",
        "interestConnection": "Yorkshire moors blizzard, Heathcliff revenge saga, Gothic estate ghosts, wild nature, and generational healing.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Moderate", "themes": "Mature" },
        "contentWarnings": ["Cruelty and emotional abuse across generations", "Ghostly manifestations"],
        "readingLevel": "Grade 9-12 / 880L",
        "genre": "Gothic Literary Classic",
        "isbn": "9780141439556",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780141439556-M.jpg",
        "description": "Set on the windswept Yorkshire moors, this is the tumultuous story of foundling Heathcliff, his consumed love for Catherine Earnshaw, and the vengeance that consumes two generations.",
        "pageCount": 416
    },
    {
        "id": "mock-287",
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "publishedYear": 1813,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Sparkling romantic comedy of manners championing female wit, seeing past first impressions, acknowledging personal pride, and marrying for genuine respect.",
        "interestConnection": "Regency England ballrooms, sharp banter between Elizabeth and Darcy, overcoming pride, sisterly affection, and wit.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "Mild", "themes": "None" },
        "contentWarnings": ["Elopement scandal resolved through financial negotiation"],
        "readingLevel": "Grade 7-12 / 1060L",
        "genre": "Romantic Comedy / Regency Classic",
        "isbn": "9780141439518",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780141439518-M.jpg",
        "description": "Spirited Elizabeth Bennet and haughty aristocrat Fitzwilliam Darcy clash upon meeting. As family dramas unfold, both must overcome their personal pride and prejudice to recognize their love.",
        "pageCount": 432
    },
    {
        "id": "mock-288",
        "title": "Emma",
        "author": "Jane Austen",
        "publishedYear": 1815,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Masterclass in irony and self-delusion: a wealthy, well-meaning young woman meddles in others' romantic lives until she realizes how blind she has been to her own heart.",
        "interestConnection": "Matchmaking blunders, small English village social dynamics, clever word riddles, picnic arguments, and moral growth.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "Mild", "themes": "None" },
        "contentWarnings": [],
        "readingLevel": "Grade 7-12 / 1040L",
        "genre": "Comedy of Manners Classic",
        "isbn": "9780141439587",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780141439587-M.jpg",
        "description": "Clever, handsome, and rich, Emma Woodhouse fancies herself an expert matchmaker. But her misguided interventions in village romances force her to confront her own blind spots.",
        "pageCount": 474
    },
    {
        "id": "mock-289",
        "title": "The Picture of Dorian Gray",
        "author": "Oscar Wilde",
        "publishedYear": 1890,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Dazzling philosophical cautionary tale of aestheticism, moral vanity, the decay of the soul behind a portrait, and the consequences of hedonism.",
        "interestConnection": "Supernatural aging portrait in attic, Faustian bargain for eternal youth, Victorian salons, aphorisms, and moral corruption.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Murder of portrait painter Basil Hallward", "Opium den visits"],
        "readingLevel": "Grade 9-12 / 900L",
        "genre": "Philosophical Gothic Classic",
        "isbn": "9780141439570",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780141439570-M.jpg",
        "description": "Enthralled by his own youth, Dorian Gray wishes his portrait would age while he stays forever young. His wish is granted, but while his face stays innocent, the portrait registers his moral decay.",
        "pageCount": 254
    },
    {
        "id": "mock-290",
        "title": "The Strange Case of Dr. Jekyll and Mr. Hyde",
        "author": "Robert Louis Stevenson",
        "publishedYear": 1886,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Fascinating psychological mystery exploring the dual nature of man, hypocrisy, scientific hubris, and the battle between moral restraint and base impulses.",
        "interestConnection": "Victorian London foggy cobblestones, laboratory potion transformation, split personality duality, and detective mystery.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Hyde trampling a child in street", "Cane beating murder of MP"],
        "readingLevel": "Grade 7-10 / 990L",
        "genre": "Psychological Horror Classic",
        "isbn": "9780486266886",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780486266886-M.jpg",
        "description": "Lawyer Utterson investigates the strange link between his respectable friend Dr. Henry Jekyll and the loathsome Edward Hyde, uncovering a horrifying scientific breakthrough in human duality.",
        "pageCount": 96
    },
    {
        "id": "mock-291",
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "publishedYear": 1937,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Timeless, cozy yet thrilling high fantasy masterwork celebrating ordinary domestic courage, riddles in the dark, and preferring peace to gold.",
        "interestConnection": "Baggins hobbit hole, riddle contest with Gollum, dragon Smaug conversation, dwarven quest, and magical ring.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Giant spider battles in Mirkwood", "Battle of Five Armies combat"],
        "readingLevel": "Grade 5-8 / 1000L",
        "genre": "High Fantasy Masterpiece",
        "isbn": "9780547928227",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780547928227-M.jpg",
        "description": "Bilbo Baggins is a hobbit who enjoys a comfortable life. His contentment is interrupted when Gandalf the wizard and thirteen dwarves arrive to enlist him as a burglar to reclaim their mountain treasure from Smaug.",
        "pageCount": 366
    },
    {
        "id": "mock-292",
        "title": "The Fellowship of the Ring",
        "author": "J.R.R. Tolkien",
        "publishedYear": 1954,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 17,
        "whyAppropriate": "The gold standard of world-building, friendship, resistance against corruption, and the profound truth that even the smallest person can alter the course of history.",
        "interestConnection": "The One Ring, Ringwraith pursuit, Council of Elrond, Mines of Moria Balrog battle, and heroic fellowship.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Moria subterranean orc and troll combat", "Sacrifice of Gandalf at bridge"],
        "readingLevel": "Grade 7-12 / 860L",
        "genre": "High Epic Fantasy Masterpiece",
        "isbn": "9780547928210",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780547928210-M.jpg",
        "description": "Frodo Baggins inherits the Master Ring of Power from Bilbo. To save Middle-earth from the Dark Lord Sauron, Frodo must journey to Mount Doom to destroy the Ring, guarded by eight companions.",
        "pageCount": 432
    },
    {
        "id": "mock-293",
        "title": "The Two Towers",
        "author": "J.R.R. Tolkien",
        "publishedYear": 1954,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Epic middle chapter featuring the defense of Helm's Deep, the awakening of the ancient Ents, and Frodo and Sam's fragile alliance with Gollum.",
        "interestConnection": "Helm's Deep siege, Ents marching on Isengard, Dead Marshes crossing, Gollum psychological struggle, and loyalty.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Orc warfare and Helm's Deep fortress battle", "Shelob spider cavern peril"],
        "readingLevel": "Grade 7-12 / 870L",
        "genre": "High Epic Fantasy Masterpiece",
        "isbn": "9780547928203",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780547928203-M.jpg",
        "description": "The Fellowship is scattered. Aragorn, Legolas, and Gimli race across Rohan to rescue their friends, while Frodo and Sam traverse the Dead Marshes toward Mordor with Gollum as their untrustworthy guide.",
        "pageCount": 352
    },
    {
        "id": "mock-294",
        "title": "The Return of the King",
        "author": "J.R.R. Tolkien",
        "publishedYear": 1955,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Triumphant, emotionally devastating conclusion to the epic, examining the burden of leadership, the cost of war, and returning home changed forever.",
        "interestConnection": "Battle of Pelennor Fields, Ride of the Rohirrim, Mount Doom eruption, Aragorn coronation, and Grey Havens farewell.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Siege of Minas Tirith and Pelennor war casualties"],
        "readingLevel": "Grade 7-12 / 890L",
        "genre": "High Epic Fantasy Masterpiece",
        "isbn": "9780547928197",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780547928197-M.jpg",
        "description": "As the dark armies of Sauron besiege the white city of Minas Tirith, Frodo and Sam reach the slopes of Mount Doom to cast the Ring into the fire, concluding the War of the Ring.",
        "pageCount": 448
    },
    {
        "id": "mock-295",
        "title": "A Wizard of Earthsea",
        "author": "Ursula K. Le Guin",
        "publishedYear": 1968,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Sublime, poetic fantasy foundational classic: a prideful wizard prodigy accidentally releases a shadow beast and learns that true power lies in balance and self-knowledge.",
        "interestConnection": "Wizard school Roke, True Names magic system, releasing shadow monster, dragon negotiations, and conquering pride.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Shadow creature summoned through pride"],
        "readingLevel": "Grade 6-9 / 1150L",
        "genre": "High Fantasy Classic",
        "isbn": "9780547773742",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780547773742-M.jpg",
        "description": "Ged is the greatest sorcerer in Earthsea, but in his youth he was headstrong. Pride leads him to unleash an ancient shadow into the world, which he must pursue across islands to restore balance.",
        "pageCount": 208
    },
    {
        "id": "mock-296",
        "title": "The Tombs of Atuan",
        "author": "Ursula K. Le Guin",
        "publishedYear": 1971,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Newbery Honor classic exploring the psychological liberation of a young high priestess trapped in a dark underground labyrinth of dead gods.",
        "interestConnection": "Underground labyrinth without light, high priestess Tenar, dark Nameless Ones, Ged labyrinth infiltration, and liberation.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Underground sensory deprivation labyrinth", "Religious zealotry conditioning"],
        "readingLevel": "Grade 6-9 / 840L",
        "genre": "High Fantasy Classic",
        "isbn": "9780547773735",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780547773735-M.jpg",
        "description": "Taken from her family as a child, Tenar is renamed Arha, the high priestess to the ancient Nameless Ones in the pitch-black subterranean Tombs of Atuan, until a wizard enters the labyrinth.",
        "pageCount": 160
    },
    {
        "id": "mock-297",
        "title": "The Left Hand of Darkness",
        "author": "Ursula K. Le Guin",
        "publishedYear": 1969,
        "recommendedAgeMin": 15,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Hugo and Nebula-winning sci-fi philosophical masterpiece examining gender, diplomacy, loyalty, and crossing an Arctic ice sheet with a former rival.",
        "interestConnection": "Ice planet Gethen, ambisexual society without fixed gender, planetary diplomacy, glacier trek survival, and deep friendship.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Sub-zero Arctic glacier trek starvation peril", "Political prison farm"],
        "readingLevel": "Grade 10-12 / 930L",
        "genre": "Sci-Fi Masterpiece / Philosophy",
        "isbn": "9780441478125",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780441478125-M.jpg",
        "description": "Genly Ai is an envoy sent to the icy planet of Gethen to persuade its leaders to join an intergalactic coalition. To bridge the divide, Genly must cross an 800-mile glacier with an outcast politician.",
        "pageCount": 304
    },
    {
        "id": "mock-298",
        "title": "Mistborn: The Final Empire",
        "author": "Brandon Sanderson",
        "publishedYear": 2006,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Action fantasy heist masterpiece with an intricate metallic magic system (Allomancy), examining rebellion against an immortal tyrant, trust, and hope.",
        "interestConnection": "Allomancy burning metals, ash falling from sky, thief crew planning grand rebellion, noble ball espionage, and hope.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Steel Inquisitor eye spikes brutality", "Skaa peasant oppression"],
        "readingLevel": "Grade 8-11 / 810L",
        "genre": "High Epic Fantasy Heist",
        "isbn": "9780765350381",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780765350381-M.jpg",
        "description": "For a thousand years, ash has fallen from the sky and the immortal Lord Ruler has ruled with iron will. When street thief Vin discovers she is a Mistborn who can ingest metals for magic, she joins a crew to steal the empire.",
        "pageCount": 541
    },
    {
        "id": "mock-299",
        "title": "The Well of Ascension (Mistborn)",
        "author": "Brandon Sanderson",
        "publishedYear": 2007,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Nuanced political fantasy sequel about what happens AFTER you overthrow the dark lord: defending a city under siege and governing fairly.",
        "interestConnection": "City siege defense, parliamentary democracy creation, kandra shapeshifter spy, Deepness prophecy, and sword battles.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Siege warfare with koloss brutes", "Spies and assassinations"],
        "readingLevel": "Grade 8-11 / 820L",
        "genre": "High Epic Fantasy",
        "isbn": "9780765356130",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780765356130-M.jpg",
        "description": "Overthrowing the Lord Ruler was the easy part; now Vin and Elend must govern. As three armies lay siege to Luthadel, Vin races to discover the mystery of the Well of Ascension before an ancient terror wakes.",
        "pageCount": 590
    },
    {
        "id": "mock-300",
        "title": "The Priory of the Orange Tree",
        "author": "Samantha Shannon",
        "publishedYear": 2019,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Magnificent, feminist epic high fantasy weaving East and West dragon lore, secret mages, court politics, and a matriarchal priory defending the realm.",
        "interestConnection": "Water dragons vs fire dragons, secret priory mages, court intrigue, diverse female leaders, and epic world-building.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Dragon warfare and plague epidemic (red sickness)", "Court intrigue executions"],
        "readingLevel": "Grade 9-12 / 850L",
        "genre": "High Epic Fantasy Masterpiece",
        "isbn": "9781635570298",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781635570298-M.jpg",
        "description": "An unmarried queen must conceive a daughter to protect her realm from destruction. Divided by religion and geography, four women in East and West must unite to stop the Nameless One from rising.",
        "pageCount": 848
    }
]

print(f"Group 3 complete: {len(GROUP_3_B)} books in part B")
