# Group 2 Part A: Transition / Early YA (Ages 12-15) - Books mock-115 to mock-160 (46 books)

GROUP_2_A = [
    {
        "id": "mock-115",
        "title": "The Outsiders",
        "author": "S.E. Hinton",
        "publishedYear": 1967,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Foundational YA classic exploring class conflict, brotherhood, empathy, and staying gold in the face of hardship.",
        "interestConnection": "Greasers vs Socs, brotherhood, classic cars, drive-in movies, Robert Frost poetry, and loyalty.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Gang switchblade fighting", "Accidental stabbing in self-defense", "Cigarette smoking historical context"],
        "readingLevel": "Grade 7-9 / 750L",
        "genre": "Classic Coming of Age",
        "isbn": "9780142407332",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780142407332-M.jpg",
        "description": "Fourteen-year-old Ponyboy Curtis is a Greaser on the poor side of town. When a brawl with the wealthy Socs turns deadly, Ponyboy and his sensitive friend Johnny go on the run.",
        "pageCount": 192
    },
    {
        "id": "mock-116",
        "title": "The Maze Runner",
        "author": "James Dashner",
        "publishedYear": 2009,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "High-octane dystopian thriller emphasizing teamwork, courage under pressure, problem-solving, and defying oppressive systems.",
        "interestConnection": "Giant shifting labyrinth, memory loss mystery, bio-mechanical monsters, survival rules, and rebellion.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Mechanical Griever monster attacks", "Intense peril in changing maze"],
        "readingLevel": "Grade 7-10 / 770L",
        "genre": "Dystopian Sci-Fi",
        "isbn": "9780385737951",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385737951-M.jpg",
        "description": "When Thomas wakes up in the Glade with no memory of his past, he finds himself trapped with a group of teenage boys inside an enormous, ever-changing stone maze patrolled by lethal creatures.",
        "pageCount": 384
    },
    {
        "id": "mock-117",
        "title": "Divergent",
        "author": "Veronica Roth",
        "publishedYear": 2011,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Fast-paced dystopian action novel exploring virtue ethics, resisting societal pigeonholing, bravery, and personal integrity.",
        "interestConnection": "Post-apocalyptic Chicago, faction aptitude simulation, combat training, fear landscape trials, and rebellion.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Intense combat initiation trials", "Simulated mind-control serum assault"],
        "readingLevel": "Grade 7-10 / 700L",
        "genre": "Dystopian Action",
        "isbn": "9780062024039",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062024039-M.jpg",
        "description": "In a futuristic Chicago divided into five factions based on virtue, Beatrice Prior makes a choice that surprises everyone, discovering she is Divergent and will never fit into just one category.",
        "pageCount": 487
    },
    {
        "id": "mock-118",
        "title": "The City of Ember",
        "author": "Jeanne DuPrau",
        "publishedYear": 2003,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Inventive, suspenseful sci-fi mystery about young people deciphering ancient municipal engineering instructions to save their failing subterranean city.",
        "interestConnection": "Underground city, flickering generator failure, secret ancient instructions, deciphering damaged text, and escape.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Blackouts and electrical grid panic", "Corrupt mayor hoarding supplies"],
        "readingLevel": "Grade 5-7 / 680L",
        "genre": "Dystopian Sci-Fi",
        "isbn": "9780375822742",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780375822742-M.jpg",
        "description": "The city of Ember was built as a refuge for humanity, but after two centuries its great generator is failing. Two twelve-year-olds discover a chewed-up secret box containing instructions to leave.",
        "pageCount": 288
    },
    {
        "id": "mock-119",
        "title": "Uglies",
        "author": "Scott Westerfeld",
        "publishedYear": 2005,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Prescient critique of extreme aesthetic standards, superficial conformity, cosmetic surgery culture, and adolescent body dysmorphia.",
        "interestConnection": "Hoverboards, beauty surgery dystopia, wilderness rebel colony Smoke, wire-guided tricks, and individuality.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Government mandatory cosmetic brain surgery (lesions)", "Extreme hoverboard stunts"],
        "readingLevel": "Grade 7-9 / 730L",
        "genre": "Dystopian Sci-Fi",
        "isbn": "9780689865381",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780689865381-M.jpg",
        "description": "In Tally Youngblood’s world, turning sixteen means undergoing surgical transformation from an 'Ugly' to a flawless 'Pretty'. But her new friend Shay prefers freedom, leading Tally to discover the sinister price of perfection.",
        "pageCount": 425
    },
    {
        "id": "mock-120",
        "title": "Unwind",
        "author": "Neal Shusterman",
        "publishedYear": 2007,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Gripping, morally complex bioethics thriller challenging readers on bodily autonomy, legal compromise, and human value.",
        "interestConnection": "Underground runaway network, bioethics legal dilemma, junkyard graveyard sanctuary, clapper rebellion, and moral conviction.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Unwinding harvesting procedure depicted soberly in one chapter", "Terrorist clapper bombings"],
        "readingLevel": "Grade 8-11 / 740L",
        "genre": "Dystopian Bioethics Thriller",
        "isbn": "9781416912040",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781416912040-M.jpg",
        "description": "After a civil war over reproductive rights, the Heartland War ends with the Unwind Accord: parents can choose to retroactively 'unwind' troublesome teens, harvesting their organs for others.",
        "pageCount": 335
    },
    {
        "id": "mock-121",
        "title": "Thunderhead",
        "author": "Neal Shusterman",
        "publishedYear": 2018,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Masterful sequel deepening questions of artificial intelligence governance, justice versus retribution, and systemic societal corruption.",
        "interestConnection": "All-knowing benevolent AI Thunderhead, scythe political corruption, vigilante justice, and technological ethics.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Political assassinations in Scythedom", "Submersion disaster"],
        "readingLevel": "Grade 7-10 / 800L",
        "genre": "Speculative Sci-Fi",
        "isbn": "9781442472457",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781442472457-M.jpg",
        "description": "The Thunderhead is a sentient cloud AI that manages everything on Earth perfectly—except for the Scythedom. As corruption spreads among the scythes, Citra and Rowan fight on opposite sides of the law.",
        "pageCount": 512
    },
    {
        "id": "mock-122",
        "title": "The Toll",
        "author": "Neal Shusterman",
        "publishedYear": 2019,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Epic conclusion to the Scythe trilogy exploring the rebirth of religion, artificial intelligence communication, space colonization, and human redemption.",
        "interestConnection": "AI silence, Tonist prophetic resonance, space ark colonization, high-stakes diplomacy, and human survival.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Naval battle bombardments", "Mass gleaning attempts thwarted"],
        "readingLevel": "Grade 7-11 / 820L",
        "genre": "Speculative Sci-Fi Finale",
        "isbn": "9781442472488",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781442472488-M.jpg",
        "description": "In the dramatic conclusion to the Arc of a Scythe series, the Thunderhead has cut off all communication with humanity except for one individual: a former apprentice known as the Toll.",
        "pageCount": 640
    },
    {
        "id": "mock-123",
        "title": "Scarlet (The Lunar Chronicles)",
        "author": "Marissa Meyer",
        "publishedYear": 2013,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Thrilling Little Red Riding Hood sci-fi remix exploring genetically altered soldiers, grandmother rescue, piloting spaceships, and cross-species loyalty.",
        "interestConnection": "Little Red Riding Hood sci-fi remix, underground fight clubs, bio-engineered street fighter, French countryside, and space pilots.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Underground cage fighting", "Kidnapped grandmother peril"],
        "readingLevel": "Grade 6-9 / 750L",
        "genre": "Sci-Fi Fairy Tale",
        "isbn": "9780312642969",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780312642969-M.jpg",
        "description": "Scarlet Benoit is determined to find her missing grandmother. Her only lead is Wolf, a street fighter who may have ties to the shadowy Lunar operatives searching for Cinder.",
        "pageCount": 452
    },
    {
        "id": "mock-124",
        "title": "Cress (The Lunar Chronicles)",
        "author": "Marissa Meyer",
        "publishedYear": 2014,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Clever Rapunzel sci-fi adaptation featuring an expert hacker trapped on a satellite, space rescues, desert survival, and overthrowing tyranny.",
        "interestConnection": "Rapunzel satellite hacker, orbital spy surveillance, desert crash survival, blind pilot escort, and grand heist.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Orbital satellite sabotage", "Desert dehydration survival"],
        "readingLevel": "Grade 6-9 / 760L",
        "genre": "Sci-Fi Fairy Tale",
        "isbn": "9780312642976",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780312642976-M.jpg",
        "description": "Cress has been trapped on a satellite in orbit since childhood, forced to hack and spy for Queen Levana. When Cinder’s crew mounts a daring rescue, things go disastrously wrong.",
        "pageCount": 550
    },
    {
        "id": "mock-125",
        "title": "Winter (The Lunar Chronicles)",
        "author": "Marissa Meyer",
        "publishedYear": 2015,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Epic Snow White finale delivering satisfying payoffs for all eight characters, celebrating peaceful resistance, mental resilience, and mutual sacrifice.",
        "interestConnection": "Snow White reimagined, Lunar palace revolution, palace guard romance, hallucinatory visions, and epic finale.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Revolutionary military clashes", "Poisoned apple bio-weapon attempt"],
        "readingLevel": "Grade 6-9 / 770L",
        "genre": "Sci-Fi Fairy Tale Finale",
        "isbn": "9780312642983",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780312642983-M.jpg",
        "description": "Princess Winter is beloved by the Lunar people for her grace, though her refusal to use her mind-controlling gift has led to hallucinations. Alongside Cinder's crew, she leads the revolution.",
        "pageCount": 824
    },
    {
        "id": "mock-126",
        "title": "Prodigy",
        "author": "Marie Lu",
        "publishedYear": 2013,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Tense political action sequel dissecting the difference between reforming a broken nation and blind rebel allegiance.",
        "interestConnection": "Vegas rebel underground, assassination plot, political double-agents, airship battles, and shifting trust.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Rebel militia assassinations and military counter-tactics"],
        "readingLevel": "Grade 7-9 / 710L",
        "genre": "Dystopian Action",
        "isbn": "9780399256769",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399256769-M.jpg",
        "description": "Injured and on the run in Las Vegas, June and Day join the Patriot rebels. In exchange for rescuing Day’s little brother, the rebels demand they assassinate the new Republic Elector Primo.",
        "pageCount": 374
    },
    {
        "id": "mock-127",
        "title": "Champion",
        "author": "Marie Lu",
        "publishedYear": 2013,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Emotional, pulse-pounding conclusion to the Legend trilogy highlighting diplomatic compromise, personal sacrifice, and peace.",
        "interestConnection": "Antarctica superpower treaty, bioweapons cure race, dogfighting jets, military strategy, and selfless loyalty.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Wartime plague epidemic casualties", "Battlefield aviation skirmishes"],
        "readingLevel": "Grade 7-10 / 720L",
        "genre": "Dystopian Action Finale",
        "isbn": "9780399256776",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399256776-M.jpg",
        "description": "When a deadly plague outbreak threatens a border war between the Republic and the Colonies, June and Day must reunite to make the ultimate sacrifice for their people.",
        "pageCount": 369
    },
    {
        "id": "mock-128",
        "title": "Steelheart",
        "author": "Brandon Sanderson",
        "publishedYear": 2013,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Action-packed superhero subversion exploring gun engineering, tactical weakness discovery, and ordinary people fighting invincible supervillains.",
        "interestConnection": "Evil superheroes, urban guerrilla tactics, steel city Chicago, tactical weakness investigation, and gadgets.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Supervillain urban destruction", "Guerrilla firefights with high-tech weaponry"],
        "readingLevel": "Grade 6-9 / 680L",
        "genre": "Superhero Sci-Fi",
        "isbn": "9780385743563",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385743563-M.jpg",
        "description": "Ten years ago, the comet Calamity gave ordinary people superpowers, turning them into tyrannical villains called Epics. Nobody fights back except the Reckoners, and David knows how to kill Steelheart.",
        "pageCount": 386
    },
    {
        "id": "mock-129",
        "title": "Firefight",
        "author": "Brandon Sanderson",
        "publishedYear": 2015,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Compelling sequel examining the psychology of fear, why power corrupts, and whether superpowered tyrants can be redeemed.",
        "interestConnection": "Flooded Manhattan ruins, bioluminescent creatures, high-tech sniper battles, power source origins, and redemption.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["High-tech urban combat skirmishes"],
        "readingLevel": "Grade 6-9 / 700L",
        "genre": "Superhero Sci-Fi",
        "isbn": "9780385743587",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385743587-M.jpg",
        "description": "David and the Reckoners travel to the flooded ruins of Babylon Restored (former Manhattan), ruled by the enigmatic High Epic Regalia, where David searches for answers about Firefight.",
        "pageCount": 422
    },
    {
        "id": "mock-130",
        "title": "Skyward",
        "author": "Brandon Sanderson",
        "publishedYear": 2018,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Top Gun meets Ender's Game: an outcast girl repairs a quirky sentient starfighter AI to defend her subterranean human enclave from alien onslaughts.",
        "interestConnection": "Starfighter flight school, snarky sentient ship AI M-Bot, alien dogfights, clearing father's name, and heroic courage.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Starfighter dogfight combat", "Classmate pilot casualties"],
        "readingLevel": "Grade 6-9 / 740L",
        "genre": "Military Sci-Fi / Space",
        "isbn": "9780399555770",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399555770-M.jpg",
        "description": "Spensa’s world has been under alien attack for decades. Defeated pilots are branded cowards, including her father. Spensa is determined to become a pilot and clear his name.",
        "pageCount": 513
    },
    {
        "id": "mock-131",
        "title": "Starsight",
        "author": "Brandon Sanderson",
        "publishedYear": 2019,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Imaginative space adventure where the protagonist goes undercover among diverse alien species, learning about prejudice, empathy, and cosmic alliances.",
        "interestConnection": "Infiltrating alien space station, telepathic cytonic powers, alien flight team, interspecies diplomacy, and grand space mystery.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Cosmic delver dimension threat", "Space dogfighting"],
        "readingLevel": "Grade 6-9 / 750L",
        "genre": "Space Opera",
        "isbn": "9780399555817",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399555817-M.jpg",
        "description": "Spensa has proven her flying skills, but to save her planet, she must infiltrate the galactic alien government itself by posing as an alien pilot on their massive orbital platform.",
        "pageCount": 480
    },
    {
        "id": "mock-132",
        "title": "The Crossover",
        "author": "Kwame Alexander",
        "publishedYear": 2014,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Newbery Medal and Coretta Scott King winner in rhythmic verse capturing basketball energy, twin brotherhood, family health, and growing up.",
        "interestConnection": "Basketball court poetry, twin brothers, jazz and hip-hop rhythms, school championship, and family love.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Father heart attack medical emergency"],
        "readingLevel": "Grade 5-8 / 750L",
        "genre": "Sports Novel in Verse",
        "isbn": "9780544107717",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780544107717-M.jpg",
        "description": "Fourteen-year-old twin brothers Josh and Jordan Bell are kings of the court with basketball in their blood. But Josh learns that growing up means making tough calls off the court.",
        "pageCount": 240
    },
    {
        "id": "mock-133",
        "title": "Rebound",
        "author": "Kwame Alexander",
        "publishedYear": 2018,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Prequel to The Crossover in dynamic verse, exploring 1988 summertime, comic books, grief, grandparents, and how basketball heals a broken heart.",
        "interestConnection": "1988 retro summer, comic book superheroes, grandfather mentorship, street basketball, and overcoming grief.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Father passing in hospital from illness"],
        "readingLevel": "Grade 5-8 / 760L",
        "genre": "Sports Novel in Verse",
        "isbn": "9780544868137",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780544868137-M.jpg",
        "description": "In 1988, Charlie Bell is reeling from his father's death. When he is sent to spend the summer with his grandparents, his cousin Roxy introduces him to the healing rhythm of basketball.",
        "pageCount": 416
    },
    {
        "id": "mock-134",
        "title": "Long Way Down",
        "author": "Jason Reynolds",
        "publishedYear": 2017,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Newbery and Printz Honor verse masterpiece set entirely during a 60-second elevator ride, confronting gun violence and the cycle of revenge.",
        "interestConnection": "Sixty-second elevator ride, ghosts of gun violence, verse poetry, breaking the cycle of revenge, and moral choice.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "None", "themes": "Mature" },
        "contentWarnings": ["Gun in waistband contemplation of revenge", "Ghosts recounting shooting deaths"],
        "readingLevel": "Grade 7-10 / 720L",
        "genre": "Novel in Verse / Social Realism",
        "isbn": "9781481438254",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781481438254-M.jpg",
        "description": "Will’s older brother Shawn has just been murdered. Following 'The Rules', Will takes Shawn's gun into an elevator to get revenge. On every floor down, a ghost of someone killed by gun violence steps in.",
        "pageCount": 320
    },
    {
        "id": "mock-135",
        "title": "Patina",
        "author": "Jason Reynolds",
        "publishedYear": 2017,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Dynamic, empowering look at competitive running, 800m teamwork, diabetes, co-parenting with aunts, and learning to share the baton.",
        "interestConnection": "Track and field relay, 800-meter training, caring for diabetic mother, competitive drive, and female friendship.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Mother diabetes leg amputation backstory"],
        "readingLevel": "Grade 5-7 / 710L",
        "genre": "Sports / Middle Grade",
        "isbn": "9781481450188",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781481450188-M.jpg",
        "description": "Patina 'Patty' Jones is lightning fast on the track, but running the 800-meter relay means learning to trust her teammates and pass the baton, while helping raise her little sister at home.",
        "pageCount": 240
    },
    {
        "id": "mock-136",
        "title": "Sunny",
        "author": "Jason Reynolds",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Tender, rhythmic diary novel about letting go of expectations, trading running for the discus, dance moves, and speaking your truth to parents.",
        "interestConnection": "Discus throwing, modern dance choreography, audio diary format, homeschool rhythm, and father expectations.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Mother died during childbirth, father grief"],
        "readingLevel": "Grade 5-7 / 720L",
        "genre": "Sports / Middle Grade",
        "isbn": "9781481450218",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781481450218-M.jpg",
        "description": "Sunny doesn't run track because he loves it; he runs because his father wants him to win medals to make up for his mother dying giving birth. Sunny wants to stop running and dance.",
        "pageCount": 176
    },
    {
        "id": "mock-137",
        "title": "Lu",
        "author": "Jason Reynolds",
        "publishedYear": 2018,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Triumphant Track series conclusion about albino hurdles champion Lu, confronting parental past mistakes, integrity, and sportsmanship.",
        "interestConnection": "Track hurdles champion, albinism representation, championship meet, parental redemption, and sports ethics.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Parent's former drug dealing history discussed and forgiven"],
        "readingLevel": "Grade 5-7 / 740L",
        "genre": "Sports / Middle Grade",
        "isbn": "9781481450249",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781481450249-M.jpg",
        "description": "Lu is an albino track star who loves running hurdles and swaggering across the finish line. When his father's past threatens Coach Brody, Lu must learn what real leadership means.",
        "pageCount": 224
    },
    {
        "id": "mock-138",
        "title": "Refugee",
        "author": "Alan Gratz",
        "publishedYear": 2017,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Massive bestseller connecting three gripping refugee stories across history: 1930s Nazi Germany, 1990s Cuba, and modern Syria with empathy and hope.",
        "interestConnection": "Historical refugee journeys, SS St. Louis ship, raft to Florida, Mediterranean refugee crossing, and mutual humanity.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Persecution by Nazi patrol", "Raft sinking in ocean storm", "Syrian airstrike evacuation"],
        "readingLevel": "Grade 5-8 / 800L",
        "genre": "Historical Fiction",
        "isbn": "9780545880831",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780545880831-M.jpg",
        "description": "Three children—Josef in 1930s Nazi Germany, Isabel in 1994 Cuba, and Mahmoud in 2015 Syria—undertake harrowing journeys across land and sea in search of refuge and freedom.",
        "pageCount": 352
    },
    {
        "id": "mock-139",
        "title": "Grenade",
        "author": "Alan Gratz",
        "publishedYear": 2018,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Riveting dual-perspective WWII novel set during the Battle of Okinawa between a drafted Okinawan boy and a young American Marine.",
        "interestConnection": "Battle of Okinawa, dual perspective enemies, cave shelters, moral choice, and brotherhood.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Hand grenade conscription of schoolboys", "Combat explosions and cave warfare"],
        "readingLevel": "Grade 5-8 / 790L",
        "genre": "Historical Military Fiction",
        "isbn": "9781338245691",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781338245691-M.jpg",
        "description": "On Okinawa in 1945, Hideki is handed two grenades and ordered to kill an American soldier. Ray is an American Marine arriving on the beach. Their paths cross in the smoke of battle.",
        "pageCount": 272
    },
    {
        "id": "mock-140",
        "title": "Allies",
        "author": "Alan Gratz",
        "publishedYear": 2019,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Masterful D-Day narrative following multiple Allied soldiers, French resistance fighters, and tank crews working together to liberate Europe.",
        "interestConnection": "D-Day Normandy invasion, French resistance sabotage, Sherman tanks, paratroopers, and multinational cooperation.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["D-Day beach landing warfare and mortar explosions"],
        "readingLevel": "Grade 5-8 / 780L",
        "genre": "Historical Military Fiction",
        "isbn": "9781338245721",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781338245721-M.jpg",
        "description": "June 6, 1944: D-Day. Dee is a young American soldier storming Omaha Beach. Samira is a French girl working for the Resistance. Together with allies from around the globe, they fight to liberate Europe.",
        "pageCount": 336
    },
    {
        "id": "mock-141",
        "title": "Ground Zero",
        "author": "Alan Gratz",
        "publishedYear": 2021,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Intertwines the terror of a boy inside the World Trade Center on 9/11 with an Afghan girl in 2019 protecting a wounded soldier from the Taliban.",
        "interestConnection": "September 11 Twin Towers escape, Afghanistan mountain village, Pashtunwali code of hospitality, and courage.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Twin towers airplane strike evacuation", "Taliban armed encounters"],
        "readingLevel": "Grade 5-8 / 730L",
        "genre": "Historical / Contemporary",
        "isbn": "9781338245752",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781338245752-M.jpg",
        "description": "Brandon is visiting his father at Windows on the World on September 11, 2001. Eighteen years later, Reshmina shelters an American soldier in her Afghan village, challenging cycles of conflict.",
        "pageCount": 336
    },
    {
        "id": "mock-142",
        "title": "Prisoner B-3087",
        "author": "Alan Gratz",
        "publishedYear": 2013,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Inspiring true story of Yanek Gruener, who survived ten different Nazi concentration camps through indomitable willpower and resilience.",
        "interestConnection": "True Holocaust survival, concentration camp prisoner endurance, hidden attic bunkers, and human spirit.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Concentration camp brutal historical realities"],
        "readingLevel": "Grade 5-8 / 730L",
        "genre": "Historical Biography / Survival",
        "isbn": "9780545459013",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780545459013-M.jpg",
        "description": "As a boy in 1930s Poland, Yanek Gruener watches his world collapse. Over the next six years, he survives ten Nazi concentration camps, death marches, and cruelty to reclaim his name.",
        "pageCount": 272
    },
    {
        "id": "mock-143",
        "title": "Two Degrees",
        "author": "Alan Gratz",
        "publishedYear": 2022,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "High-stakes climate adventure following four kids fighting for survival in California wildfires, Arctic polar bear territory, and Florida hurricanes.",
        "interestConnection": "Wildfire escape, polar bear confrontation, category five hurricane, climate science, and youth environmental activism.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Extreme natural disaster survival peril (fire, flood, animal attack)"],
        "readingLevel": "Grade 5-8 / 750L",
        "genre": "Ecological Survival Thriller",
        "isbn": "9781338735673",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781338735673-M.jpg",
        "description": "Three kids across the globe face immediate climate crises: fleeing a catastrophic California wildfire, facing hungry polar bears in Churchill, and surviving a Category 5 hurricane in Miami.",
        "pageCount": 384
    },
    {
        "id": "mock-144",
        "title": "Fever 1793",
        "author": "Laurie Halse Anderson",
        "publishedYear": 2000,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Historically rich depiction of the 1793 Philadelphia yellow fever epidemic, female entrepreneurship, and mutual racial aid via the Free African Society.",
        "interestConnection": "1793 Philadelphia yellow fever epidemic, coffeehouse business, medical history of bloodletting, and courageous teenage heroine.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Epidemic illness descriptions and burier carts", "Burglary of coffeehouse"],
        "readingLevel": "Grade 5-8 / 580L",
        "genre": "Historical Fiction",
        "isbn": "9780689848919",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780689848919-M.jpg",
        "description": "Sixteen-year-old Mattie Cook helps run her family's coffeehouse in Philadelphia, the nation's capital. When the yellow fever epidemic hits the city, Mattie must fight to keep herself and her business alive.",
        "pageCount": 256
    },
    {
        "id": "mock-145",
        "title": "Chains (Seeds of America)",
        "author": "Laurie Halse Anderson",
        "publishedYear": 2008,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "National Book Award finalist following an enslaved girl in Revolutionary War New York who becomes a spy, exposing the hypocrisy of patriots fighting for liberty.",
        "interestConnection": "Revolutionary War espionage, enslaved girl fighting for freedom, secret messages, British vs Patriot intrigue, and sister devotion.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Physical abuse of enslaved individuals (branding with letter I)"],
        "readingLevel": "Grade 6-9 / 780L",
        "genre": "Historical Fiction",
        "isbn": "9781416905868",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781416905868-M.jpg",
        "description": "As the Revolutionary War begins, thirteen-year-old Isabel is sold to cruel Loyalist owners in New York. She is recruited by Patriots to spy on her owners in exchange for her and her sister’s freedom.",
        "pageCount": 316
    },
    {
        "id": "mock-146",
        "title": "Forge (Seeds of America)",
        "author": "Laurie Halse Anderson",
        "publishedYear": 2010,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Riveting sequel following Curzon escaping slavery by enlisting in the Continental Army during the bitter, frozen winter at Valley Forge.",
        "interestConnection": "Valley Forge winter encampment, Continental Army soldiering, log cabin construction, and freedom struggle.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Brutal winter starvation at Valley Forge", "Recapture into slavery peril"],
        "readingLevel": "Grade 6-9 / 790L",
        "genre": "Historical Military Fiction",
        "isbn": "9781416961444",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781416961444-M.jpg",
        "description": "Curzon enlists in George Washington's army to secure his freedom, enduring the brutal, starving winter encampment at Valley Forge before crossing paths again with Isabel.",
        "pageCount": 304
    },
    {
        "id": "mock-147",
        "title": "The House of the Scorpion",
        "author": "Nancy Farmer",
        "publishedYear": 2002,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Newbery Honor and National Book Award-winning sci-fi classic exploring human cloning, bioethics, cartels, and individual human dignity.",
        "interestConnection": "Clone of drug lord El Patrón, opium kingdom Opium, bodyguard bodyguard mentorship, escape across border, and identity.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Prejudice against clones", "Organ harvesting intent", "Border patrol work camps"],
        "readingLevel": "Grade 6-9 / 660L",
        "genre": "Dystopian Sci-Fi Classic",
        "isbn": "9780689852237",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780689852237-M.jpg",
        "description": "Matt has lived his entire life in a small cottage, knowing only his caretaker Celia. He discovers he is a clone of El Patrón, the 140-year-old ruler of the nation of Opium, created to provide replacement organs.",
        "pageCount": 380
    },
    {
        "id": "mock-148",
        "title": "Eragon (The Inheritance Cycle)",
        "author": "Christopher Paolini",
        "publishedYear": 2002,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Epic high fantasy classic written by a teenage author, following a farm boy who hatches a blue dragon and restores the legendary Dragon Riders.",
        "interestConnection": "Dragon bonding, telepathic connection with Saphira, ancient magic language, sword fighting, and rebel Varden.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Urgal and Ra'zac monster battles", "Uncle killed by empire agents"],
        "readingLevel": "Grade 6-9 / 710L",
        "genre": "High Epic Fantasy",
        "isbn": "9780375826696",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780375826696-M.jpg",
        "description": "Fifteen-year-old farm boy Eragon finds a polished blue stone in the forest. When it hatches into a sapphire dragon he names Saphira, Eragon is swept into an ancient destiny as a legendary Dragon Rider.",
        "pageCount": 509
    },
    {
        "id": "mock-149",
        "title": "Eldest (The Inheritance Cycle)",
        "author": "Christopher Paolini",
        "publishedYear": 2005,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Expansive fantasy sequel exploring elven philosophy, vegetarianism, sword mastery, and sibling wartime paths.",
        "interestConnection": "Elven forest city Ellesméra, dragon rider training, elven magic arts, dwarven politics, and battle of Burning Plains.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Large-scale fantasy army battles", "Brother identity revelation shock"],
        "readingLevel": "Grade 6-9 / 780L",
        "genre": "High Epic Fantasy",
        "isbn": "9780375826702",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780375826702-M.jpg",
        "description": "Eragon and Saphira travel to the enchanted elven city of Ellesméra to further their training in magic and swordsmanship, while Eragon's cousin Roran defends their home village of Carvahall.",
        "pageCount": 681
    },
    {
        "id": "mock-150",
        "title": "Shadow and Bone (The Grishaverse)",
        "author": "Leigh Bardugo",
        "publishedYear": 2012,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Tsarist Russia-inspired fantasy introducing the magical Grisha orders, the dangerous allure of absolute power, and the courage of an ordinary soldier.",
        "interestConnection": "Tsarist fantasy Ravka, Sun Summoner light magic, shadow monsters in the Fold, Little Palace intrigue, and Darkling villain.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Shadow monster volcra attacks in Fold", "Villainous betrayal and manipulation"],
        "readingLevel": "Grade 7-9 / 790L",
        "genre": "Fantasy YA",
        "isbn": "9781250027436",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250027436-M.jpg",
        "description": "Surrounded by enemies, the once-great nation of Ravka has been severed in two by the Shadow Fold. When her regiment is attacked, humble mapmaker Alina Starkov unleashes dormant magic.",
        "pageCount": 358
    },
    {
        "id": "mock-151",
        "title": "Siege and Storm (The Grishaverse)",
        "author": "Leigh Bardugo",
        "publishedYear": 2013,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Thrilling high-seas and sky-faring sequel featuring privateers, mechanical engineering, magical amplification, and leadership burdens.",
        "interestConnection": "Privateer Sturmhond sky ship, sea dragon amplifier, Ravkan palace civil war, and leadership resolve.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Naval artillery and shadow soldier combat"],
        "readingLevel": "Grade 7-9 / 780L",
        "genre": "Fantasy YA",
        "isbn": "9781250044433",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250044433-M.jpg",
        "description": "Hunted across the True Sea, Alina and Mal try to build a life in an unfamiliar land. But Alina cannot outrun her destiny as the Sun Summoner, allying with an infamous privateer to save Ravka.",
        "pageCount": 435
    },
    {
        "id": "mock-152",
        "title": "Ruin and Rising (The Grishaverse)",
        "author": "Leigh Bardugo",
        "publishedYear": 2014,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Satisfying conclusion to Alina's journey exploring sacrifice, the true cost of wielding divine power, and choosing peace over godhood.",
        "interestConnection": "Underground zealot tunnels, firebird amplifier quest, final showdown with Darkling, and sacrifice.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Subterranean isolation peril", "Climactic magical war casualties"],
        "readingLevel": "Grade 7-10 / 800L",
        "genre": "Fantasy YA Finale",
        "isbn": "9781250063168",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250063168-M.jpg",
        "description": "The capital has fallen. The Darkling rules from his shadow throne. Alina must rally a fractured coalition of rebels and search for the elusive third amplifier, the firebird, to reclaim Ravka.",
        "pageCount": 422
    },
    {
        "id": "mock-153",
        "title": "Children of Blood and Bone",
        "author": "Tomi Adeyemi",
        "publishedYear": 2018,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Instant classic West African fantasy exploring state oppression, police brutality analogies, restoring heritage magic, and courage.",
        "interestConnection": "West African mythology, giant horned lion mounts, restoring forbidden magic, sword combat, and sisterhood.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Monarchist raid killings of maji in backstory", "Gladiator style arena combat"],
        "readingLevel": "Grade 7-10 / 670L",
        "genre": "West African Epic Fantasy",
        "isbn": "9781250170972",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250170972-M.jpg",
        "description": "Zélie Adebola remembers when the soil of Orïsha hummed with magic. But the ruthless king ordered all maji killed. With the help of a rogue princess, Zélie must outrun the crown prince to restore magic.",
        "pageCount": 544
    },
    {
        "id": "mock-154",
        "title": "Children of Virtue and Vengeance",
        "author": "Tomi Adeyemi",
        "publishedYear": 2019,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Complex sequel exploring how military power corrupts both oppressors and revolutionaries, examining the challenge of achieving peace.",
        "interestConnection": "Civil war, military monarch titans, divine power unleashed, rebel alliances, and seeking peace.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Civil war casualties", "Magical weapon strikes"],
        "readingLevel": "Grade 7-10 / 690L",
        "genre": "West African Epic Fantasy",
        "isbn": "9781250170996",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250170996-M.jpg",
        "description": "After a monumental ritual, magic has returned to Orïsha. But the ritual brought back magic not only to the maji, but also to nobles with magical bloodlines, sparking an apocalyptic civil war.",
        "pageCount": 416
    },
    {
        "id": "mock-155",
        "title": "Red Queen",
        "author": "Victoria Aveyard",
        "publishedYear": 2015,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Fast-paced dystopian fantasy examining social caste hierarchies (Silver elite vs Red commoners), propaganda, and undercover rebel intrigue.",
        "interestConnection": "Electric lightning power, arena demonstration, masquerading as lost noble, Scarlet Guard rebel alliance, and betrayal.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Gladiator arena power clashes", "Betrayal execution threats"],
        "readingLevel": "Grade 7-10 / 740L",
        "genre": "Dystopian Fantasy",
        "isbn": "9780062310637",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062310637-M.jpg",
        "description": "In Mare Barrow's world, society is divided by blood: common Reds and godlike, silver-blooded elites with superpowers. Working in the royal palace, Mare discovers she possesses deadly powers of her own.",
        "pageCount": 383
    },
    {
        "id": "mock-156",
        "title": "Glass Sword",
        "author": "Victoria Aveyard",
        "publishedYear": 2016,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Darker, tactical sequel dealing with the burden of recruiting newblood soldiers, propaganda warfare, and the psychological cost of leadership.",
        "interestConnection": "Recruiting newbloods with superpowers, stealth airship missions, hunting list, prison break, and leadership burdens.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Military skirmishes and execution attempts"],
        "readingLevel": "Grade 7-10 / 760L",
        "genre": "Dystopian Fantasy",
        "isbn": "9780062310668",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062310668-M.jpg",
        "description": "Mare Barrow’s blood is red, but her silver ability to control lightning has turned her into a weapon. Pursued by Maven, the boy king who betrayed her, Mare sets out to rescue other newbloods.",
        "pageCount": 444
    },
    {
        "id": "mock-157",
        "title": "Ash Princess",
        "author": "Laura Sebastian",
        "publishedYear": 2018,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tense court intrigue novel about a captive princess biding her time, playing the docile pawn while secretly organizing a revolution to liberate her people.",
        "interestConnection": "Captive princess, court deception, gem magic mines, secret rebel alliance, and reclaiming throne.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Public palace flogging in opening", "Colonizer oppression"],
        "readingLevel": "Grade 7-10 / 730L",
        "genre": "Fantasy YA",
        "isbn": "9781524767068",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781524767068-M.jpg",
        "description": "Theodosia was six when her country was invaded and her mother, the Fire Queen, was murdered. For ten years, Theo has been a prisoner in her own palace, wearing a crown of ashes until she decides to fight back.",
        "pageCount": 448
    },
    {
        "id": "mock-158",
        "title": "An Ember in the Ashes",
        "author": "Sabaa Tahir",
        "publishedYear": 2015,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Brutally gripping ancient Roman-inspired fantasy contrasting an undercover slave spy with a military mask cadet seeking freedom from tyranny.",
        "interestConnection": "Ancient Roman-style empire, undercover spy at military academy, silver masked warriors, trials for emperor, and rebellion.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Cruel military school hazing", "Threats of execution and corporal punishment"],
        "readingLevel": "Grade 8-11 / 760L",
        "genre": "High Fantasy YA",
        "isbn": "9781595148032",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781595148032-M.jpg",
        "description": "Under the Martial Empire, defiance is met with death. When Laia's brother is arrested for treason, she agrees to spy for the resistance inside the Empire’s greatest military academy, where she meets Elias.",
        "pageCount": 446
    },
    {
        "id": "mock-159",
        "title": "A Torch Against the Night",
        "author": "Sabaa Tahir",
        "publishedYear": 2016,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Pulse-pounding prison escape quest testing loyalty, medical healing in the field, psychological warfare, and fighting against insurmountable odds.",
        "interestConnection": "Prison break from Kauf fortress, mountain wilderness chase, ancient jinn spirits, and sacrifice.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Brutal conditions in Kauf prison", "Combat injuries"],
        "readingLevel": "Grade 8-11 / 780L",
        "genre": "High Fantasy YA",
        "isbn": "9781595148056",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781595148056-M.jpg",
        "description": "Elias and Laia are running for their lives from the Martial Empire, heading north to infiltrate the most secure prison in the realm to rescue Laia's brother, pursued by Elias's former best friend.",
        "pageCount": 464
    },
    {
        "id": "mock-160",
        "title": "Truly Devious",
        "author": "Maureen Johnson",
        "publishedYear": 2018,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Sophisticated modern whodunit set at an eccentric Vermont boarding school, alternating between a 1930s unsolved kidnapping and a present-day murder.",
        "interestConnection": "Boarding school for prodigies, cold case kidnapping riddle, true-crime teen sleuth, mountain snowstorm, and secret tunnels.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Mysterious death on campus", "Anxiety disorder depiction"],
        "readingLevel": "Grade 7-10 / 710L",
        "genre": "Boarding School Mystery",
        "isbn": "9780062338051",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062338051-M.jpg",
        "description": "Ellingham Academy is a famous private school founded by an eccentric tycoon whose wife and daughter were kidnapped in 1936. When true-crime buff Stevie Bell arrives, the Truly Devious murderer strikes again.",
        "pageCount": 432
    }
]

print(f"Group 2 Part A loaded: {len(GROUP_2_A)} books")
