# Group 3 Part A: High School YA & Classics (Ages 14-17) - Books mock-208 to mock-253 (46 books)

GROUP_3_A = [
    {
        "id": "mock-208",
        "title": "Catching Fire (The Hunger Games)",
        "author": "Suzanne Collins",
        "publishedYear": 2009,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tense political thriller exploring rebellion sparks, totalitarian victory tours, PTSD trauma, and the Quarter Quell arena trap.",
        "interestConnection": "Quarter Quell arena clock puzzle, sparks of revolution, mockingjay symbol, political defiance, and allied tributes.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Quarter Quell arena combat", "Capitol execution of protestors", "Floggings in District 12"],
        "readingLevel": "Grade 8-11 / 820L",
        "genre": "Dystopian Thriller",
        "isbn": "9780439023498",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780439023498-M.jpg",
        "description": "Against all odds, Katniss Everdeen has survived the Hunger Games. But President Snow warns her that her defiance has ignited whispers of rebellion, forcing her back into the deadly Quarter Quell arena.",
        "pageCount": 391
    },
    {
        "id": "mock-209",
        "title": "Mockingjay (The Hunger Games)",
        "author": "Suzanne Collins",
        "publishedYear": 2010,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Unflinching, honest exploration of the cost of total war, propaganda manipulation on both sides, war crimes, and postwar recovery.",
        "interestConnection": "District 13 underground rebellion, propo broadcast filming, military urban assault on Capitol, and rebuilding peace.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Urban warfare civilian casualties", "Bombing of child medics", "PTSD grief and trauma"],
        "readingLevel": "Grade 8-11 / 800L",
        "genre": "Dystopian War Finale",
        "isbn": "9780439023511",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780439023511-M.jpg",
        "description": "Katniss Everdeen has survived, though District 12 has been destroyed. Taking up the mantle of the Mockingjay, she becomes the face of the revolution against the Capitol while questioning the rebel leaders.",
        "pageCount": 390
    },
    {
        "id": "mock-210",
        "title": "Crooked Kingdom (Six of Crows)",
        "author": "Leigh Bardugo",
        "publishedYear": 2016,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Spectacular conclusion to the Six of Crows duology: an intricate urban counter-heist exploring redemption, standing by found family, and outmaneuvering corrupt merchant councils.",
        "interestConnection": "Ketterdam street cons, auction counter-heist, chemical antidote fabrication, revenge against Pekka Rollins, and loyalty.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Moderate", "themes": "Moderate" },
        "contentWarnings": ["Underworld gang turf shootouts", "Jurda parem drug withdrawal"],
        "readingLevel": "Grade 9-12 / 790L",
        "genre": "Fantasy Heist Finale",
        "isbn": "9781627792134",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781627792134-M.jpg",
        "description": "Double-crossed and down one crew member, Kaz Brekker and his outcasts fight across the streets of Ketterdam to rescue Inej, settle old scores, and bring down the Merchant Council.",
        "pageCount": 546
    },
    {
        "id": "mock-211",
        "title": "Hunting by Stars",
        "author": "Cherie Dimaline",
        "publishedYear": 2021,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Heart-pounding Indigenous dystopian sequel following Frenchie trapped in a residential school-style marrow harvesting facility, exploring resistance, identity, and courage.",
        "interestConnection": "Undercover in marrow school facility, Indigenous language resistance, wilderness scouting, and brotherly rescue.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Forced marrow harvesting medical facility", "Historical residential school trauma allegories"],
        "readingLevel": "Grade 9-12 / 860L",
        "genre": "Indigenous Dystopian YA",
        "isbn": "9781419753473",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781419753473-M.jpg",
        "description": "Years into a dystopian world where Indigenous people are hunted for their bone marrow to restore dreaming, Frenchie wakes up captured inside a sinister residential harvesting school.",
        "pageCount": 400
    },
    {
        "id": "mock-212",
        "title": "Good Girl, Bad Blood",
        "author": "Holly Jackson",
        "publishedYear": 2020,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Gripping true-crime podcast sequel where Pip vows she's done sleuthing, until a friend's brother vanishes on memorial night and the police refuse to look.",
        "interestConnection": "True-crime podcast recording, missing person countdown, catfishing online investigation, and town secrets.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Missing teenager investigation", "Catfishing identity theft reveal"],
        "readingLevel": "Grade 9-12 / 810L",
        "genre": "YA Mystery Thriller",
        "isbn": "9781984896438",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781984896438-M.jpg",
        "description": "Pip Fitz-Amobi released a viral podcast about the murder case she solved. She promises never to investigate again, until Jamie Reynolds disappears and Pip launches an emergency podcast search.",
        "pageCount": 416
    },
    {
        "id": "mock-213",
        "title": "On the Come Up",
        "author": "Angie Thomas",
        "publishedYear": 2019,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Electrifying, honest story of a sixteen-year-old aspiring hip-hop MC navigating family poverty, viral media mischaracterization, and artistic integrity.",
        "interestConnection": "Rap battle arenas, hip-hop lyricism, underground mixtape, viral media stereotyping, and family love.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["School security aggressive pat-down incident", "Poverty stress and utility shutoffs"],
        "readingLevel": "Grade 8-11 / 570L",
        "genre": "Contemporary YA / Hip-Hop",
        "isbn": "9780062498564",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062498564-M.jpg",
        "description": "Sixteen-year-old Bri wants to be one of the greatest rappers of all time. But when her mom loses her job and an incident with school security makes Bri viral as a threat, she must rap her truth.",
        "pageCount": 448
    },
    {
        "id": "mock-214",
        "title": "Concrete Rose",
        "author": "Angie Thomas",
        "publishedYear": 2021,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tender, powerful prequel following Maverick Carter at seventeen, navigating teenage fatherhood, stepping away from gang life, and gardening with his mentor.",
        "interestConnection": "Teen fatherhood responsibility, gardening mentorship, 1990s Garden Heights, breaking street cycles, and manhood.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Gang drug trade involvement", "Fatal shooting of cousin"],
        "readingLevel": "Grade 8-11 / 620L",
        "genre": "Contemporary Social Realism",
        "isbn": "9780062846716",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062846716-M.jpg",
        "description": "Set seventeen years before The Hate U Give, Maverick Carter is a seventeen-year-old trying to balance gang ties until he discovers he is a father, forcing him to choose the man he wants to be.",
        "pageCount": 320
    },
    {
        "id": "mock-215",
        "title": "The Martian",
        "author": "Andy Weir",
        "publishedYear": 2014,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Celebration of human ingenuity, botany, chemistry, and humorous resilience: an astronaut stranded on Mars 'sciences the heck' out of survival.",
        "interestConnection": "Mars surface survival, potato botany in Hab, rover modification, chemistry calculations, and NASA rescue coordination.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Frequent profanity in astronaut log entries", "Hab airlock depressurization hazard"],
        "readingLevel": "Grade 9-12 / 890L",
        "genre": "Hard Sci-Fi Classic",
        "isbn": "9780553418026",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780553418026-M.jpg",
        "description": "Six days into an expedition on Mars, astronaut Mark Watney is stranded by a dust storm and presumed dead. With no way to signal Earth, he must use his botantical genius to stay alive.",
        "pageCount": 384
    },
    {
        "id": "mock-216",
        "title": "Artemis",
        "author": "Andy Weir",
        "publishedYear": 2017,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Fast-moving lunar colony heist novel featuring a brilliant young Saudi woman smuggler navigating vacuum physics, welding, and aluminum plant sabotage.",
        "interestConnection": "Lunar city Artemis, vacuum welding science, zero-gravity smuggling caper, industrial sabotage, and oxygen chemistry.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Lunar vacuum suit asphyxiation peril", "Organized crime syndicate threats"],
        "readingLevel": "Grade 9-12 / 870L",
        "genre": "Hard Sci-Fi Heist",
        "isbn": "9780553448122",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780553448122-M.jpg",
        "description": "Jazz Bashara is a porter and petty smuggler in Artemis, the only city on the moon. Offered a fortune to sabotage an industrial aluminum smelter, she stumbles into a conspiracy for control of the lunar city.",
        "pageCount": 320
    },
    {
        "id": "mock-217",
        "title": "Ready Player One",
        "author": "Ernest Cline",
        "publishedYear": 2011,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Action-packed celebration of 1980s pop culture, computer coding, video game history, and resisting evil corporate monopolization of virtual worlds.",
        "interestConnection": "Virtual reality OASIS, 80s arcade gaming, Easter egg billionaire contest, DeLorean starship, and corporate resistance.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Corporate drone bombing of trailer park", "Occasional mature profanity"],
        "readingLevel": "Grade 8-11 / 980L",
        "genre": "Cyberpunk VR Adventure",
        "isbn": "9780307887436",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780307887436-M.jpg",
        "description": "In the year 2045, reality is an ugly place. Teenage Wade Watts finds solace in the OASIS, an expansive virtual universe whose dying creator hid an Easter egg worth hundreds of billions.",
        "pageCount": 384
    },
    {
        "id": "mock-218",
        "title": "Ready Player Two",
        "author": "Ernest Cline",
        "publishedYear": 2020,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "High-concept sci-fi sequel exploring direct neural interface technology, digital consciousness replication, and AI alignment ethics.",
        "interestConnection": "Neural VR headset ONI, seven shards quest, rogue AI Anorak, digital afterlife ethics, and pop culture simulations.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Hostage crisis with neural implants locking users online", "Digital death peril"],
        "readingLevel": "Grade 9-12 / 990L",
        "genre": "Cyberpunk VR Adventure",
        "isbn": "9781524761332",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781524761332-M.jpg",
        "description": "Days after winning the contest, Wade discovers a breakthrough technology that allows users to experience the OASIS with all five senses, unleashing a brand-new quest and an unstoppable rogue AI.",
        "pageCount": 384
    },
    {
        "id": "mock-219",
        "title": "They Both Die at the End",
        "author": "Adam Silvera",
        "publishedYear": 2017,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Emotional philosophical YA exploring what it means to truly live, overcoming anxiety, and making a single final day meaningful through connection.",
        "interestConnection": "Death-Cast phone call, Last Friend app, VR skydiving, living life to the fullest, and poignant romance.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Impending mortality awareness (characters notified they will die within 24 hours)"],
        "readingLevel": "Grade 8-11 / 760L",
        "genre": "Speculative YA / Contemporary",
        "isbn": "9780062457790",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062457790-M.jpg",
        "description": "On September 5, a little after midnight, Death-Cast calls Mateo Torrez and Rufus Emeterio to give them bad news: they're going to die today. Through the Last Friend app, they meet up to live a lifetime in a day.",
        "pageCount": 384
    },
    {
        "id": "mock-220",
        "title": "The First to Die at the End",
        "author": "Adam Silvera",
        "publishedYear": 2022,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tender prequel set on the eve of Death-Cast's launch, exploring skepticism, heart conditions, sudden connection, and courage in the face of fate.",
        "interestConnection": "Death-Cast premiere night, Times Square countdown, heart transplant recipient, street photography, and connection.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Chronic heart condition peril", "Premonitions of mortality"],
        "readingLevel": "Grade 8-11 / 770L",
        "genre": "Speculative YA",
        "isbn": "9780063240803",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780063240803-M.jpg",
        "description": "On the night Death-Cast first goes live in 2010, Orion and Valentino cross paths in Times Square. When only one of them receives the call, their night becomes an unforgettable journey of love and courage.",
        "pageCount": 560
    },
    {
        "id": "mock-221",
        "title": "More Happy Than Not",
        "author": "Adam Silvera",
        "publishedYear": 2015,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Heart-wrenching speculative exploration of grief, Bronx street life, coming out, and the seductive danger of memory-erasing technology.",
        "interestConnection": "Memory-alteration Leteo procedure, Bronx summer, coming of age, comics, and emotional authenticity.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Past suicide attempt in family history", "Homophobic assault by peers", "Memory alteration distress"],
        "readingLevel": "Grade 9-12 / 780L",
        "genre": "Speculative YA / LGBTQ+",
        "isbn": "9781616955601",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781616955601-M.jpg",
        "description": "In the months following his father's suicide, sixteen-year-old Aaron Soto considers turning to the Leteo Institute, a memory-erasing procedure, to forget who he is after falling for a new boy in his neighborhood.",
        "pageCount": 304
    },
    {
        "id": "mock-222",
        "title": "History Is All You Left Me",
        "author": "Adam Silvera",
        "publishedYear": 2017,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tender, perceptive novel about obsessive-compulsive disorder, processing complicated first loves, and mourning with empathy.",
        "interestConnection": "OCD rituals and coping mechanisms, non-linear timeline, processing accidental drowning, and healing.",
        "maturityScores": { "violence": "None", "language": "Moderate", "romance": "Moderate", "themes": "Mature" },
        "contentWarnings": ["Drowning death of first love", "Severe OCD counting rituals depicted realistically"],
        "readingLevel": "Grade 9-12 / 790L",
        "genre": "Contemporary YA / Mental Health",
        "isbn": "9781616956929",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781616956929-M.jpg",
        "description": "When Griffin’s first love and ex-boyfriend Theo dies in a drowning accident, Griffin’s universe implodes. To stop his spiraling OCD and grief, he must open up to Theo's college boyfriend Jackson.",
        "pageCount": 304
    },
    {
        "id": "mock-223",
        "title": "We Were Liars",
        "author": "E. Lockhart",
        "publishedYear": 2014,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Hypnotic, atmospheric psychological suspense about privilege, family greed on a private Massachusetts island, and an unforgettable plot twist.",
        "interestConnection": "Private island summer estate, Sinclair family wealth, amnesia after mysterious head injury, and shocking truth.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Severe head injury and amnesia", "Arson with tragic consequences revealed"],
        "readingLevel": "Grade 8-11 / 600L",
        "genre": "Psychological Suspense YA",
        "isbn": "9780385741262",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385741262-M.jpg",
        "description": "Cadence Sinclair Easton spends every summer on her wealthy family’s private island off Cape Cod with her cousins and a boy she loves. After a mysterious accident leaves her with amnesia, she returns to uncover what happened.",
        "pageCount": 240
    },
    {
        "id": "mock-224",
        "title": "Family of Liars",
        "author": "E. Lockhart",
        "publishedYear": 2022,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tense 1980s prequel revealing the roots of the Sinclair family’s obsession with appearances, perfectionism, and covering up tragedies.",
        "interestConnection": "1987 summer on private island, tennis matches, painkiller addiction recovery, sailing secrets, and tragedy.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Substance misuse of prescription painkillers", "Accidental death cover-up"],
        "readingLevel": "Grade 8-11 / 630L",
        "genre": "Psychological Suspense YA",
        "isbn": "9780593485859",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780593485859-M.jpg",
        "description": "A generation before We Were Liars, seventeen-year-old Carrie Sinclair is reeling from the drowning of her sister and an addiction to painkillers when unexpected visitors bring dark secrets to Beechwood Island.",
        "pageCount": 320
    },
    {
        "id": "mock-225",
        "title": "Genuine Fraud",
        "author": "E. Lockhart",
        "publishedYear": 2017,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Talented Mr. Ripley-inspired feminist thriller told in reverse chronological order about identity theft, sociopathic deception, and survival.",
        "interestConnection": "Reverse timeline mystery, identity theft con artist, luxury penthouses, martial arts conditioning, and dark psychological twists.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Murder and identity theft", "Toxic obsessive friendship"],
        "readingLevel": "Grade 9-12 / 720L",
        "genre": "Psychological Thriller",
        "isbn": "9780385744775",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385744775-M.jpg",
        "description": "Told in reverse, Genuine Fraud is the story of Jule, an athletic orphan with a gift for impersonation, and her obsessive, deadly friendship with glamorous heiress Imogen Sokoloff.",
        "pageCount": 272
    },
    {
        "id": "mock-226",
        "title": "The Disreputable History of Frankie Landau-Banks",
        "author": "E. Lockhart",
        "publishedYear": 2008,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Printz Honor boarding school satire: a sharp sophomore infiltrates her boyfriend's all-male secret society and masterminds elaborate, subversive campus pranks.",
        "interestConnection": "Boarding school secret society, feminist mastermind pranks, statues with brassieres, wordplay, and dismantling old-boys clubs.",
        "maturityScores": { "violence": "None", "language": "Mild", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["School disciplinary infractions for elaborate campus pranks"],
        "readingLevel": "Grade 7-10 / 890L",
        "genre": "Boarding School / Feminist Satire",
        "isbn": "9780786838189",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780786838189-M.jpg",
        "description": "Frankie Landau-Banks is a sophomore at the prestigious Alabaster Academy. When she discovers an all-male secret society called the Loyal Order of the Basset Hounds, Frankie hacks in and secretly commands them.",
        "pageCount": 352
    },
    {
        "id": "mock-227",
        "title": "Clap When You Land",
        "author": "Elizabeth Acevedo",
        "publishedYear": 2020,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Exquisite novel in verse about two half-sisters who discover each other's existence following the tragic crash of Flight AA587, examining grief, Dominican diaspora, and sisterhood.",
        "interestConnection": "Novel in verse, Dominican Republic diaspora, NYC and Santo Domingo, plane crash AA587, and sister discovery.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Father killed in plane crash", "Sexual harassment on street rebuffed"],
        "readingLevel": "Grade 8-11 / 750L",
        "genre": "Novel in Verse / Contemporary",
        "isbn": "9780062882769",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062882769-M.jpg",
        "description": "Camino lives in the Dominican Republic waiting for her father's summer visits. Yahaira lives in New York City. When their father's plane crashes, both girls uncover the secret sister they never knew existed.",
        "pageCount": 432
    },
    {
        "id": "mock-228",
        "title": "The Poet X",
        "author": "Elizabeth Acevedo",
        "publishedYear": 2018,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "National Book Award and Printz Medal-winning powerhouse in verse celebrating slam poetry, female body autonomy, religious questioning, and finding your voice.",
        "interestConnection": "Slam poetry club, Harlem streets, strict Catholic mother clash, journal writing, and spoken-word triumph.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Physical punishment by deeply religious mother (kneeling on rice)", "Street catcalling"],
        "readingLevel": "Grade 8-11 / 800L",
        "genre": "Novel in Verse / Coming of Age",
        "isbn": "9780062662804",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062662804-M.jpg",
        "description": "Xiomara Batista feels unheard and unable to hide in her Harlem neighborhood. She pours all her frustration and passion onto the pages of a notebook, finding salvation when invited to join her school’s slam poetry club.",
        "pageCount": 368
    },
    {
        "id": "mock-229",
        "title": "With the Fire on High",
        "author": "Elizabeth Acevedo",
        "publishedYear": 2019,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Warm, inspiring celebration of culinary talent, teenage motherhood responsibility, loving grandmother bonds, and chasing chef dreams with discipline.",
        "interestConnection": "Culinary arts class, cooking magic with spices, teenage motherhood dedication, Spanish culinary trip, and ambition.",
        "maturityScores": { "violence": "None", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Balancing teen motherhood and high school"],
        "readingLevel": "Grade 8-11 / 760L",
        "genre": "Contemporary YA / Culinary",
        "isbn": "9780062662835",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062662835-M.jpg",
        "description": "Ever since she got pregnant freshman year, Emoni Santiago has had to make tough decisions. The one place she can let go is the kitchen. When a culinary arts class offers a trip to Spain, Emoni fights for her dream.",
        "pageCount": 400
    },
    {
        "id": "mock-230",
        "title": "Dear Martin",
        "author": "Nic Stone",
        "publishedYear": 2017,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Punchy, thought-provoking examination of police brutality, racial profiling, and affirmative action debates through an Ivy League-bound student's letters to Dr. Martin Luther King Jr.",
        "interestConnection": "Journal letters to Martin Luther King Jr., debate team championships, prep school microaggressions, and moral resilience.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Police shooting of best friend during traffic dispute", "Unjust arrest and handcuffing"],
        "readingLevel": "Grade 8-11 / 720L",
        "genre": "Contemporary Social Realism",
        "isbn": "9781101939499",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781101939499-M.jpg",
        "description": "Justyce McAllister is top of his class and headed for the Ivy League, but none of that matters to the police officer who unjustly handcuffs him. Justyce begins writing letters to Dr. Martin Luther King Jr. to make sense of his world.",
        "pageCount": 224
    },
    {
        "id": "mock-231",
        "title": "Dear Justyce",
        "author": "Nic Stone",
        "publishedYear": 2020,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Eye-opening companion novel examining the school-to-prison pipeline and youth detention centers through letters from an incarcerated teenager.",
        "interestConnection": "Letters from juvenile detention, math brilliance, systemic injustice critique, and brotherly rehabilitation.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "None", "themes": "Mature" },
        "contentWarnings": ["Juvenile detention center realities", "Gang coercion and firearm violence in flashback"],
        "readingLevel": "Grade 8-11 / 740L",
        "genre": "Social Justice / Contemporary",
        "isbn": "9781984829665",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781984829665-M.jpg",
        "description": "Quan Banks is serving time in a juvenile detention facility for an officer's death he didn't commit. Writing letters to his friend Justyce, Quan confronts the broken systems that trapped him.",
        "pageCount": 288
    },
    {
        "id": "mock-232",
        "title": "Aristotle and Dante Discover the Secrets of the Universe",
        "author": "Benjamin Alire Sáenz",
        "publishedYear": 2012,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Printz Honor and Pura Belpré winner: a lyrical, tender exploration of Mexican-American boyhood, masculinity, swimming, family healing, and first love in 1987 El Paso.",
        "interestConnection": "1987 El Paso, swimming lessons at pool, pickup truck stargazing, Vietnam veteran father healing, and tender friendship.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Car hit-and-run heroics (broken legs saving friend)", "Homophobic attack on friend"],
        "readingLevel": "Grade 7-10 / 510L",
        "genre": "Lyrical YA / Coming of Age",
        "isbn": "9781442408920",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781442408920-M.jpg",
        "description": "Aristotle is an angry teen with a brother in prison. Dante is a know-it-all with an unusual way of looking at the world. When they meet at a swimming pool, they forge a bond that teaches them the secrets of the universe.",
        "pageCount": 368
    },
    {
        "id": "mock-233",
        "title": "Aristotle and Dante Dive into the Waters of the World",
        "author": "Benjamin Alire Sáenz",
        "publishedYear": 2021,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Deeply moving sequel set against the backdrop of the 1980s AIDS epidemic, examining community activism, grief, vulnerability, and adult love.",
        "interestConnection": "1980s AIDS crisis awareness, high school graduation, poetry, loving family support, and road trips.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Moderate", "themes": "Mature" },
        "contentWarnings": ["AIDS crisis deaths in community", "Father passing from illness"],
        "readingLevel": "Grade 8-12 / 560L",
        "genre": "Lyrical YA / LGBTQ+",
        "isbn": "9781534496194",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781534496194-M.jpg",
        "description": "In the highly anticipated sequel, Ari and Dante must navigate what it means to build a relationship in a world that doesn't always welcome them, while confronting loss and forging their futures.",
        "pageCount": 544
    },
    {
        "id": "mock-234",
        "title": "Heartstopper: Volume 1",
        "author": "Alice Oseman",
        "publishedYear": 2018,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Utterly wholesome, comforting graphic novel exploring rugby, British grammar school, coming out, and supportive, gentle friendship.",
        "interestConnection": "Graphic novel, British grammar school, rugby team, drumming, dog walk dates, and wholesome romance.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Past bullying for being outed at school resolved supportively"],
        "readingLevel": "Grade 6-9 / 450L",
        "genre": "Graphic Novel / Romance",
        "isbn": "9781338617436",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781338617436-M.jpg",
        "description": "Charlie Spring is an openly gay year 10 student who gets assigned to sit next to rugby player Nick Nelson. An unlikely friendship quickly blossoms into something more in this sweet graphic novel.",
        "pageCount": 288
    },
    {
        "id": "mock-235",
        "title": "Radio Silence",
        "author": "Alice Oseman",
        "publishedYear": 2016,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tender celebration of platonic friendship, sci-fi podcast fandom, escaping university pressure, and embracing artistic passions over academic perfectionism.",
        "interestConnection": "Sci-fi podcast Universe City, fan art creation, university academic pressure, platonic boy-girl friendship, and authenticity.",
        "maturityScores": { "violence": "None", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Emotional parental academic pressure", "Depression and panic attacks"],
        "readingLevel": "Grade 8-11 / 750L",
        "genre": "Contemporary YA",
        "isbn": "9780008147884",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780008147884-M.jpg",
        "description": "Frances Janvier is a study machine focused solely on getting into Cambridge. When she meets Aled, the shy creator behind her favorite viral sci-fi podcast, she finds true friendship and the courage to be herself.",
        "pageCount": 416
    },
    {
        "id": "mock-236",
        "title": "Solitaire",
        "author": "Alice Oseman",
        "publishedYear": 2014,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Wry, Catcher in the Rye-esque debut novel exploring teenage apathy, clinical depression, blog culture, and finding reasons to care.",
        "interestConnection": "Blogging cynicism, school prank group Solitaire, ice-skating, brotherly care for Charlie Spring, and depression.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Depression and suicidal ideation discussed critically", "School arson prank"],
        "readingLevel": "Grade 9-12 / 760L",
        "genre": "Contemporary YA / Mental Health",
        "isbn": "9780007559220",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780007559220-M.jpg",
        "description": "Tori Spring isn't interested in making friends or caring about anything. But when a mysterious school group called Solitaire starts pulling dangerous pranks, Tori gets pulled into solving who is behind it.",
        "pageCount": 400
    },
    {
        "id": "mock-237",
        "title": "Loveless",
        "author": "Alice Oseman",
        "publishedYear": 2020,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Landmark coming-of-age novel celebrating aromantic and asexual identity, Shakespeare theatre society, and the enduring power of platonic soulmates.",
        "interestConnection": "First year at British university, Shakespeare stage production, discovering aro-ace identity, and platonic soulmates.",
        "maturityScores": { "violence": "None", "language": "Moderate", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Internalized confusion and anxiety over not feeling romantic attraction"],
        "readingLevel": "Grade 8-12 / 780L",
        "genre": "Contemporary YA / Aro-Ace",
        "isbn": "9780008244125",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780008244125-M.jpg",
        "description": "Georgia has never been in love, never had a crush, and never kissed anyone. Arriving at university, she sets out to find romance, only to realize that platonic love is the greatest love of all.",
        "pageCount": 448
    },
    {
        "id": "mock-238",
        "title": "I Was Born for This",
        "author": "Alice Oseman",
        "publishedYear": 2018,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Insightful look at boyband super-fandom, anxiety of fame, online celebrity parasocial relationships, and humanizing idols.",
        "interestConnection": "Boyband The Ark concert tour, fan fiction writer, hotel lobby stakeouts, panic attacks in spotlight, and friendship.",
        "maturityScores": { "violence": "None", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Celebrity panic attack in front of crowd", "Anxiety disorder"],
        "readingLevel": "Grade 8-11 / 760L",
        "genre": "Contemporary YA / Fandom",
        "isbn": "9780008244095",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780008244095-M.jpg",
        "description": "For Angel Rahimi, life centers on The Ark, a pop-rock boyband. For Jimmy Kaga-Ricci, being The Ark’s frontman means living with debilitating anxiety. When their worlds collide, they both discover reality.",
        "pageCount": 400
    },
    {
        "id": "mock-239",
        "title": "All the Bright Places",
        "author": "Jennifer Niven",
        "publishedYear": 2015,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Deeply emotional story of two teens meeting at their high school bell tower who partner to map the oddities of Indiana, exploring bipolar disorder and healing.",
        "interestConnection": "Indiana road trip wanderings, Virginia Woolf quotes, poetry, healing from sister's passing, and bipolar empathy.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Bipolar depression crisis and death by suicide of protagonist"],
        "readingLevel": "Grade 9-12 / 830L",
        "genre": "Contemporary YA / Mental Health",
        "isbn": "9780385755917",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385755917-M.jpg",
        "description": "Theodore Finch is fascinated by death, while Violet Markey is grieving the loss of her sister. Paired together on a school project to discover the wonders of Indiana, they learn to see beauty in the world.",
        "pageCount": 400
    },
    {
        "id": "mock-240",
        "title": "Holding Up the Universe",
        "author": "Jennifer Niven",
        "publishedYear": 2016,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tender novel pairing a girl known for a viral weight struggle with a boy hiding prosopagnosia (face blindness), discovering mutual acceptance.",
        "interestConnection": "Face blindness (prosopagnosia), high school choir, self-worth, secret letters in lockers, and true empathy.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Cruel high school prank incident", "Grief over deceased parent"],
        "readingLevel": "Grade 8-11 / 760L",
        "genre": "Contemporary YA",
        "isbn": "9780385755924",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385755924-M.jpg",
        "description": "Jack Masselin has face blindness: he can't recognize anyone, even his brothers. When a reckless prank entangles him with Libby Strout, the two discover that someone finally sees them for who they are.",
        "pageCount": 400
    },
    {
        "id": "mock-241",
        "title": "Five Feet Apart",
        "author": "Rachael Lippincott",
        "publishedYear": 2018,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Moving medical drama following two teenagers with cystic fibrosis who must stay six feet apart to prevent cross-infection, exploring resilience and love.",
        "interestConnection": "Cystic fibrosis hospital ward, medical treatment routine, lung transplant hope, art sketches, and star-crossed love.",
        "maturityScores": { "violence": "None", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Chronic illness medical procedures", "Hospital emergency surgeries"],
        "readingLevel": "Grade 8-11 / 790L",
        "genre": "Medical Contemporary YA",
        "isbn": "9781534437333",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781534437333-M.jpg",
        "description": "Stella Grant has cystic fibrosis and lives by strict medical rules: stay at least six feet away from anyone else with the condition. But Will Newman is tired of clinical trials and wants to live on his terms.",
        "pageCount": 288
    },
    {
        "id": "mock-242",
        "title": "She Drives Me Crazy",
        "author": "Kelly Quindlen",
        "publishedYear": 2021,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Fun, high-energy enemies-to-lovers rom-com pairing a basketball player with the head cheerleader after a fender bender forces them to carpool.",
        "interestConnection": "High school basketball, cheerleading competition, fake dating trope, carpool banter, and romantic comedy.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Sports rivalry arguments", "Minor car fender bender"],
        "readingLevel": "Grade 7-10 / 720L",
        "genre": "Enemies-to-Lovers Rom-Com",
        "isbn": "9781250208927",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250208927-M.jpg",
        "description": "After an embarrassing basketball loss and a fender-bender in the parking lot, Scottie and her arch-nemesis cheerleader Irene are forced to carpool, concocting a fake dating scheme to win back Scottie’s ex.",
        "pageCount": 304
    },
    {
        "id": "mock-243",
        "title": "Last Night at the Telegraph Club",
        "author": "Malinda Lo",
        "publishedYear": 2021,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "National Book Award winner: a vivid historical novel set in 1954 San Francisco Chinatown, exploring rocket science dreams, Red Scare paranoia, and discovering queer identity.",
        "interestConnection": "1950s San Francisco Chinatown, aerospace engineering dreams, Red Scare McCarthyism, Telegraph Club, and courage.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["McCarthyite FBI intimidation of immigrant families", "Police raid on gay bar in 1950s"],
        "readingLevel": "Grade 9-12 / 850L",
        "genre": "Historical YA / LGBTQ+",
        "isbn": "9780525555254",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780525555254-M.jpg",
        "description": "Seventeen-year-old Lily Hu loves aerospace engineering. When she meets Kathleen, their secret trips to a hidden lesbian bar called the Telegraph Club coincide with the anti-communist Red Scare.",
        "pageCount": 416
    },
    {
        "id": "mock-244",
        "title": "A Scatter of Light",
        "author": "Malinda Lo",
        "publishedYear": 2022,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Lush summer coming-of-age story in the San Francisco Bay Area about astronomy, fine art, grandparents, and self-discovery during the summer of marriage equality.",
        "interestConnection": "Astronomy star observations, wood carving art, Bay Area summer, grandmother artist home, and coming of age.",
        "maturityScores": { "violence": "None", "language": "Moderate", "romance": "Moderate", "themes": "Moderate" },
        "contentWarnings": ["Underage drinking at party", "Parental divorce conflict"],
        "readingLevel": "Grade 9-12 / 820L",
        "genre": "Contemporary YA",
        "isbn": "9780525555285",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780525555285-M.jpg",
        "description": "Aria Tang West is sent to spend the summer before college with her eccentric artist grandmother in California, where working with her grandmother’s gardener opens up new worlds of art and desire.",
        "pageCount": 336
    },
    {
        "id": "mock-245",
        "title": "The Grace Year",
        "author": "Kim Liggett",
        "publishedYear": 2019,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Lord of the Flies meets The Handmaid's Tale: sixteen-year-old girls are banished to a remote island to survive their 'grace year' and rid themselves of forbidden allure.",
        "interestConnection": "Island survival, patriarchal dystopia, poisonous poacher traps, female solidarity vs rivalry, and resistance.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Poacher hunting of exile girls", "Poisoning and survival injuries on island"],
        "readingLevel": "Grade 9-12 / 780L",
        "genre": "Dystopian Survival YA",
        "isbn": "9781250145444",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250145444-M.jpg",
        "description": "In Garner County, girls are banished on their sixteenth year to survive the wild and purge their dangerous magic. Tierney James dreams of a society where women don't turn against one another.",
        "pageCount": 416
    },
    {
        "id": "mock-246",
        "title": "Sadie",
        "author": "Courtney Summers",
        "publishedYear": 2018,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Unflinching, Edgar Award-winning thriller alternating between a girl hunting down her sister's killer and a true-crime radio podcast host tracking her footsteps.",
        "interestConnection": "Radio podcast transcripts, sister vengeance trek, tracking a predator, stutter representation, and raw emotional power.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "None", "themes": "Mature" },
        "contentWarnings": ["Child abuse and predatory behavior (addressed with sensitivity, not depicted graphically)", "Murder investigation"],
        "readingLevel": "Grade 9-12 / 730L",
        "genre": "YA Crime Mystery / Podcast",
        "isbn": "9781250105714",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250105714-M.jpg",
        "description": "Sadie’s little sister Mattie has been murdered. Refusing to wait for the police, Sadie hits the road to hunt down the killer, while radio host West McCray launches a podcast tracking Sadie’s trail.",
        "pageCount": 320
    },
    {
        "id": "mock-247",
        "title": "Project Nemesis",
        "author": "Brendan Reichs",
        "publishedYear": 2017,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Addictive sci-fi mystery where every year on her birthday, Min is murdered by a man in a suit—only to wake up in the woods completely uninjured.",
        "interestConnection": "Bizarre birthday murders, simulated reality mystery, black eye anomaly, Idaho mountain town, and apocalyptic secret.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Recurring violent deaths reversed by reset simulation"],
        "readingLevel": "Grade 8-11 / 760L",
        "genre": "Sci-Fi Mystery Thriller",
        "isbn": "9780515155662",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780515155662-M.jpg",
        "description": "Every two years on her birthday, Min Wilder is murdered by a mysterious man in black. Hours later, she wakes up in the woods unharmed. She discovers her classmate Noah is experiencing the same nightmare.",
        "pageCount": 448
    },
    {
        "id": "mock-248",
        "title": "Ace of Spades",
        "author": "Faridah Àbíké-Íyímídé",
        "publishedYear": 2021,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Gossip Girl meets Get Out: an anonymous texter named Aces targets the only two Black students at an elite private academy to ruin their futures.",
        "interestConnection": "Elite private boarding academy, anonymous cyber bully Aces, classical musician prodigy, institutional racism thriller, and mystery.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Targeted racist institutional bullying and blackmail", "Outing without consent"],
        "readingLevel": "Grade 9-12 / 780L",
        "genre": "Dark Academia Thriller",
        "isbn": "9781250800817",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250800817-M.jpg",
        "description": "At Niveus Private Academy, Devon and Chiamaka are chosen as senior prefects. But when an anonymous texter named Aces reveals their deepest secrets to the whole school, they must fight to survive.",
        "pageCount": 432
    },
    {
        "id": "mock-249",
        "title": "None Shall Sleep",
        "author": "Ellie Marney",
        "publishedYear": 2020,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Silence of the Lambs for YA: two teenage FBI consultants interview an incarcerated sociopath to help track a new juvenile serial killer.",
        "interestConnection": "FBI Behavioral Science Unit, interviewing incarcerated serial killer, forensic deduction, psychological chess match, and suspense.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "None", "themes": "Mature" },
        "contentWarnings": ["Serial killer forensic profiling", "Mind manipulation by sociopathic inmate"],
        "readingLevel": "Grade 9-12 / 810L",
        "genre": "Psychological Thriller",
        "isbn": "9780316498685",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316498685-M.jpg",
        "description": "In 1982, the FBI recruits two teenage trauma survivors to interview convicted juvenile serial killers for behavioral insight, matching wits with the charming, dangerous sociopath Simon Gutmunsson.",
        "pageCount": 400
    },
    {
        "id": "mock-250",
        "title": "The Agathas",
        "author": "Kathleen Glasgow & Liz Lawson",
        "publishedYear": 2022,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Fun Agatha Christie-inspired coastal whodunit where two mismatched teen girls use Hercule Poirot and Miss Marple deduction methods to clear an innocent boy.",
        "interestConnection": "Agatha Christie mystery methods, coastal California mansions, mismatched teen detectives, clearing framed suspect, and clues.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Murder of high school student", "Domestic abuse in tutor's home"],
        "readingLevel": "Grade 8-11 / 750L",
        "genre": "YA Mystery Whodunit",
        "isbn": "9780593431115",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780593431115-M.jpg",
        "description": "When popular Brooke Donovan disappears, her former best friend Alice and quiet tutor Iris team up, using the novels of Agatha Christie to investigate the real killer when police target the wrong boy.",
        "pageCount": 416
    },
    {
        "id": "mock-251",
        "title": "Girl in Pieces",
        "author": "Kathleen Glasgow",
        "publishedYear": 2016,
        "recommendedAgeMin": 15,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Intense, raw, yet deeply empathetic portrayal of self-harm recovery, residential treatment, art as salvation, and piecing oneself back together.",
        "interestConnection": "Artistic recovery, hospital treatment center, moving to Arizona, independent coffee shop job, and healing from trauma.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Self-harm (cutting) recovery depicted honestly", "Parental abuse and homelessness backstory"],
        "readingLevel": "Grade 10-12 / 740L",
        "genre": "Realistic / Mental Health YA",
        "isbn": "9781101934715",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781101934715-M.jpg",
        "description": "Seventeen-year-old Charlotte Davis is in pieces. At a residential treatment center, she learns to cope with her pain through art, slowly piecing together a fragile new life in Arizona.",
        "pageCount": 416
    },
    {
        "id": "mock-252",
        "title": "You'd Be Home Now",
        "author": "Kathleen Glasgow",
        "publishedYear": 2021,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tender, honest family drama exploring the opioid crisis through the eyes of the overlooked younger sister trying to keep her family whole.",
        "interestConnection": "Sibling love, family rehabilitation, opioid crisis reality, middle child invisibility, and learning personal boundaries.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Opioid addiction and overdose aftermath", "Car crash with casualty in prologue"],
        "readingLevel": "Grade 9-12 / 760L",
        "genre": "Contemporary Social Realism",
        "isbn": "9780593381441",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780593381441-M.jpg",
        "description": "After a fatal car crash exposes her brother Joey’s opioid addiction, sixteen-year-old Emmy is expected to watch over him 24/7, struggling to find her own identity amidst family upheaval.",
        "pageCount": 400
    },
    {
        "id": "mock-253",
        "title": "How to Make Friends with the Dark",
        "author": "Kathleen Glasgow",
        "publishedYear": 2019,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Gripping, gut-wrenching look at sudden parental loss, the foster care system, and learning how to navigate overwhelming grief without losing your soul.",
        "interestConnection": "Sudden grief processing, navigating foster care system, grandmother genealogy secrets, and emotional resilience.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "None", "themes": "Mature" },
        "contentWarnings": ["Sudden brain aneurysm death of single mother", "Foster group home struggles"],
        "readingLevel": "Grade 9-12 / 770L",
        "genre": "Contemporary YA / Grief",
        "isbn": "9781101934753",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781101934753-M.jpg",
        "description": "Sixteen-year-old Tiger Tolliver and her mother are a team of two. When her mother dies suddenly of a brain aneurysm, Tiger is thrust into foster care, fighting to survive in the dark.",
        "pageCount": 432
    }
]

print(f"Group 3 Part A loaded: {len(GROUP_3_A)} books")
