# Group 2 Part B: Transition / Early YA (Ages 12-15) - Books mock-161 to mock-207 (47 books)

GROUP_2_B = [
    {
        "id": "mock-161",
        "title": "The Vanishing Stair",
        "author": "Maureen Johnson",
        "publishedYear": 2019,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Tense boarding school sequel following Stevie's return to Ellingham Academy, unearthing secret passages, hidden diary ciphers, and cold case evidence.",
        "interestConnection": "Boarding school mystery, secret underground passages, cold case ciphers, Sherlockian deduction, and Vermont blizzards.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Murder suspect confrontation", "Poison investigation"],
        "readingLevel": "Grade 7-10 / 720L",
        "genre": "Boarding School Mystery",
        "isbn": "9780062338082",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062338082-M.jpg",
        "description": "Stevie Bell thought she had solved the mystery of Ellingham Academy, but her parents pulled her out. Making a pact with a politician gets her back on campus to solve the newly opened cold case.",
        "pageCount": 400
    },
    {
        "id": "mock-162",
        "title": "The Hand on the Wall",
        "author": "Maureen Johnson",
        "publishedYear": 2020,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Masterful trilogy finale resolving the 1936 Ellingham kidnapping and contemporary murders during a devastating mountain blizzard.",
        "interestConnection": "Blizzard trapped on mountain, final cold case reveal, secret ballroom, solving the riddle, and friendship loyalty.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Mountain blizzard hypothermia danger", "Arson attempt on historic mansion"],
        "readingLevel": "Grade 7-10 / 730L",
        "genre": "Boarding School Mystery Finale",
        "isbn": "9780062338112",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062338112-M.jpg",
        "description": "A massive blizzard traps Stevie Bell and her friends at Ellingham Academy with the killer on the loose. Stevie races against freezing conditions to unmask Truly Devious once and for all.",
        "pageCount": 416
    },
    {
        "id": "mock-163",
        "title": "One of Us Is Lying",
        "author": "Karen M. McManus",
        "publishedYear": 2017,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "The Breakfast Club meets Agatha Christie: four diverse high schoolers in detention are investigated for murder when the school gossip founder dies.",
        "interestConnection": "High school detention, murder mystery, gossip app secrets, four suspect perspectives, and clearing innocent names.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Fatal peanut oil allergic reaction in detention (poisoning)", "Cyberbullying gossip app"],
        "readingLevel": "Grade 8-11 / 730L",
        "genre": "YA Mystery Thriller",
        "isbn": "9781524714680",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781524714680-M.jpg",
        "description": "Five students walk into detention at Bayview High: the brain, the beauty, the criminal, the athlete, and the creator of the school’s notorious gossip app. Only four leave alive.",
        "pageCount": 368
    },
    {
        "id": "mock-164",
        "title": "One of Us Is Next",
        "author": "Karen M. McManus",
        "publishedYear": 2020,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Twisty technological sequel exploring truth-or-dare SMS games, digital privacy, sisterhood, and high school blackmail.",
        "interestConnection": "Truth or Dare SMS game, tech repair shop sleuth, cyber blackmail, teen secrets, and sister teamwork.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Dangerous stunt accident", "Cyberbullying texts"],
        "readingLevel": "Grade 8-11 / 740L",
        "genre": "YA Mystery Thriller",
        "isbn": "9780525707967",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780525707967-M.jpg",
        "description": "A year after Simon's death, someone starts a game of Truth or Dare via anonymous text across Bayview High. If you take Truth, your darkest secret is revealed. Dare could turn deadly.",
        "pageCount": 384
    },
    {
        "id": "mock-165",
        "title": "Two Can Keep a Secret",
        "author": "Karen M. McManus",
        "publishedYear": 2019,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Atmospheric small-town mystery exploring homecoming murder traditions, amusement park thrill rides, and twin sleuthing.",
        "interestConnection": "Echo Ridge theme park Fright Farm, homecoming queen disappearances, grandmother secrets, and twin detectives.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Unsolved missing teen cases", "Hit and run accident mystery"],
        "readingLevel": "Grade 8-11 / 750L",
        "genre": "YA Mystery Thriller",
        "isbn": "9781524714727",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781524714727-M.jpg",
        "description": "Ellery and her twin brother Ezra move to their grandmother's sleepy Vermont town, where their aunt went missing seventeen years ago and a new homecoming queen candidate has just vanished.",
        "pageCount": 336
    },
    {
        "id": "mock-166",
        "title": "The Inheritance Games",
        "author": "Jennifer Lynn Barnes",
        "publishedYear": 2020,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Knives Out meets Cinderella: a penniless high schooler inherits forty-eight billion dollars from a stranger and must navigate his mansion of riddles and hostile disinherited grandsons.",
        "interestConnection": "Billion-dollar inheritance, eccentric mansion with secret doors, anagram puzzles, bowling alleys, and four clever grandsons.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Attempted shooting sniper incident outside estate", "Family inheritance hostility"],
        "readingLevel": "Grade 7-10 / 710L",
        "genre": "Puzzle Mystery YA",
        "isbn": "9781368052405",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781368052405-M.jpg",
        "description": "Avery Grambs has a plan for a better future: survive high school and win a scholarship. But when billionaire Tobias Hawthorne dies and leaves her his entire fortune, she must move into Hawthorne House to claim it.",
        "pageCount": 384
    },
    {
        "id": "mock-167",
        "title": "The Hawthorne Legacy",
        "author": "Jennifer Lynn Barnes",
        "publishedYear": 2021,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Page-turning sequel uncovering Avery's biological connections, bomb shelters, secret treehouses, and paternity ciphers.",
        "interestConnection": "Hawthorne island estate, DNA paternity mystery, buried bomb shelter, puzzle codes, and brother rivalry.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Car explosion attempt by unknown assailant"],
        "readingLevel": "Grade 7-10 / 720L",
        "genre": "Puzzle Mystery YA",
        "isbn": "9781368052412",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781368052412-M.jpg",
        "description": "Avery thought she knew why she inherited billions, but new clues suggest Toby Hawthorne may still be alive. As DNA mysteries deepen, someone will stop at nothing to remove Avery permanently.",
        "pageCount": 368
    },
    {
        "id": "mock-168",
        "title": "The Final Gambit",
        "author": "Jennifer Lynn Barnes",
        "publishedYear": 2022,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Thrilling conclusion where Avery must survive just a few more weeks to inherit her fortune while playing one final high-stakes chess match against an old rival.",
        "interestConnection": "Chess grandmaster puzzles, philanthropic fortune distribution, final Hawthorne riddle, and hostage rescue.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Kidnapping hostage crisis resolved through wits"],
        "readingLevel": "Grade 7-10 / 730L",
        "genre": "Puzzle Mystery YA Finale",
        "isbn": "9781368053273",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781368053273-M.jpg",
        "description": "To inherit billions, Avery just needs to survive a few more weeks in Hawthorne House. But an unexpected visitor brings one last puzzle with deadly stakes for everyone she cares about.",
        "pageCount": 384
    },
    {
        "id": "mock-169",
        "title": "The Naturals",
        "author": "Jennifer Lynn Barnes",
        "publishedYear": 2013,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Criminal Minds for teens: gifted teenagers recruited by the FBI to solve cold cases using micro-expressions, profiling, and probability math.",
        "interestConnection": "FBI teen profilers, reading micro-expressions, lie detection, cold case files, and solving serial killer clues.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Serial killer crime scene analysis", "Mother missing person cold case"],
        "readingLevel": "Grade 7-10 / 700L",
        "genre": "Psychological FBI Thriller",
        "isbn": "9781423168317",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781423168317-M.jpg",
        "description": "Seventeen-year-old Cassie Hobbes has a natural gift for reading people. Recruited by an elite FBI program of gifted teens, Cassie must profile cold cases until a copycat killer makes it personal.",
        "pageCount": 320
    },
    {
        "id": "mock-170",
        "title": "Killer Instinct (The Naturals)",
        "author": "Jennifer Lynn Barnes",
        "publishedYear": 2014,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tense psychological thriller exploring deceptive charm, sociopathic manipulation, and team loyalty under FBI pressure.",
        "interestConnection": "Psychological profiling, courtroom testimony, juvenile facility investigation, and mental mind games.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Serial murder investigation", "Hostage peril"],
        "readingLevel": "Grade 7-10 / 710L",
        "genre": "Psychological FBI Thriller",
        "isbn": "9781423168331",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781423168331-M.jpg",
        "description": "When a murder resembles the work of an incarcerated serial killer—who happens to be profiler Dean's father—the Naturals are brought in to consult, testing Dean's sanity and the team's trust.",
        "pageCount": 384
    },
    {
        "id": "mock-171",
        "title": "Five Survive",
        "author": "Holly Jackson",
        "publishedYear": 2022,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Claustrophobic, heart-stopping survival mystery where six teens trapped in an RV by an unseen sniper must figure out which one of them holds the secret he wants.",
        "interestConnection": "Trapped in RV during road trip, sniper cat-and-mouse game, countdown timer, confessions under duress, and survival.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Sniper gunfire shooting out tires and gas tank", "Hostage duress"],
        "readingLevel": "Grade 8-11 / 760L",
        "genre": "Survival Thriller",
        "isbn": "9780593374160",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780593374160-M.jpg",
        "description": "Six friends head on spring break in a thirty-one-foot RV. In the middle of nowhere, their tires are shot out. A sniper in the dark gives them eight hours to reveal which of them is hiding a deadly secret.",
        "pageCount": 400
    },
    {
        "id": "mock-172",
        "title": "As Good as Dead",
        "author": "Holly Jackson",
        "publishedYear": 2021,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Gripping, morally complex finale where Pip turns from investigator to target of an online stalker, facing dark ethical dilemmas to protect herself.",
        "interestConnection": "Online stalker mystery, headless duck chalk drawings, serial killer investigation, and moral justice.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Stalking threats and intimidation", "Cover-up of a crime in self-defense"],
        "readingLevel": "Grade 9-12 / 800L",
        "genre": "YA Thriller Finale",
        "isbn": "9780593374184",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780593374184-M.jpg",
        "description": "Pip Fitz-Amobi is heading to college, but she is haunted by her last investigation. When anonymous messages asking 'Who will look for you when you're the one who disappears?' escalate, Pip becomes the prey.",
        "pageCount": 464
    },
    {
        "id": "mock-173",
        "title": "Firekeeper's Daughter",
        "author": "Angeline Boulley",
        "publishedYear": 2021,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Printz Award-winning groundbreaking thriller: an unenrolled Indigenous teen goes undercover with the FBI to protect her community from lethal meth labs.",
        "interestConnection": "Ojibwe culture and traditions, hockey culture, chemistry science expertise, FBI undercover informant, and justice.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Methamphetamine epidemic in community", "Fatal overdose of friend", "Attempted sexual assault (interrupted/thwarted)"],
        "readingLevel": "Grade 9-12 / 780L",
        "genre": "Indigenous YA Crime Thriller",
        "isbn": "9781250766564",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250766564-M.jpg",
        "description": "Eighteen-year-old Daunis Fontaine has never felt like she fully fits in. When she witnesses a shocking murder, Daunis agrees to go undercover for the FBI to investigate a deadly new drug tearing through her tribe.",
        "pageCount": 496
    },
    {
        "id": "mock-174",
        "title": "Warrior Girl Unearthed",
        "author": "Angeline Boulley",
        "publishedYear": 2023,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Compelling heist and museum ethics novel exploring NAGPRA, repatriation of Indigenous ancestral remains, and missing Indigenous women.",
        "interestConnection": "Museum artifact repatriation, Sugar Island summer internship, museum heist, stolen ancestors, and twin sleuthing.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Black-market trading of Indigenous ancestral remains", "Missing Indigenous women issue"],
        "readingLevel": "Grade 8-12 / 790L",
        "genre": "Indigenous YA Mystery / Heist",
        "isbn": "9781250766588",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250766588-M.jpg",
        "description": "Perry Firekeeper-Birch has always been the laid-back twin. But during a summer internship at the tribal museum, she discovers an unscrupulous collector is hoarding ancestral remains and plans a daring heist.",
        "pageCount": 400
    },
    {
        "id": "mock-175",
        "title": "Stargirl",
        "author": "Jerry Spinelli",
        "publishedYear": 2000,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Tender celebration of radical non-conformity, ukulele songs, random acts of kindness, and resisting middle school peer pressure to blend in.",
        "interestConnection": "Ukulele playing, pet rat Cinnamon, marching band cheerleading, peer conformity vs authenticity, and first love.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Shunning and silence treatment by high school peer group"],
        "readingLevel": "Grade 5-8 / 590L",
        "genre": "Realistic Fiction Classic",
        "isbn": "9780440416777",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780440416777-M.jpg",
        "description": "Stargirl Caraway arrives at Mica High with a ukulele strapped to her back and a pet rat in her bag. The student body is enchanted, until their adoration turns into shunning when she refuses to conform.",
        "pageCount": 186
    },
    {
        "id": "mock-176",
        "title": "Tangerine",
        "author": "Edward Bloor",
        "publishedYear": 1997,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Gripping, darkly funny mystery about family lies, sinkholes, high school soccer brotherhood, and seeing the truth despite being visually impaired.",
        "interestConnection": "Soccer goaltending, muck fires and sinkholes, visually impaired hero with thick goggles, sibling sociopathy, and citrus groves.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Abusive older brother athletic favoritism", "Sinkhole school collapse"],
        "readingLevel": "Grade 6-9 / 680L",
        "genre": "Sports Mystery / YA Classic",
        "isbn": "9780152057800",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780152057800-M.jpg",
        "description": "Legally blind Paul Fisher moves to bizarre Tangerine County, Florida, where underground muck fires burn constantly and sinkholes swallow schools. Joining the tough Tangerine Middle soccer team helps him confront his family's dark secret.",
        "pageCount": 312
    },
    {
        "id": "mock-177",
        "title": "The Boy Who Harnessed the Wind",
        "author": "William Kamkwamba & Bryan Mealer",
        "publishedYear": 2009,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Inspiring true story of a fourteen-year-old Malawian boy who taught himself physics from library books to build a windmill out of junkyard scraps, bringing electricity and irrigation to his village.",
        "interestConnection": "Junkyard engineering, building a windmill from bicycle parts, physics experiments, drought survival, and African innovation.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Famine and starvation crisis in village during drought"],
        "readingLevel": "Grade 5-8 / 910L",
        "genre": "Memoir / Science Nonfiction",
        "isbn": "9780147510426",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780147510426-M.jpg",
        "description": "When a terrible drought struck his tiny village in Malawi, fourteen-year-old William Kamkwamba was forced to drop out of school. Refusing to surrender, he used library books and scrap metal to build an operating windmill.",
        "pageCount": 304
    },
    {
        "id": "mock-178",
        "title": "Undefeated: Jim Thorpe and the Carlisle Indian School Football Team",
        "author": "Steve Sheinkin",
        "publishedYear": 2017,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Thrilling narrative nonfiction exploring how Native American athletes revolutionized American football, outsmarted Ivy League titans, and overcame systemic boarding school prejudice.",
        "interestConnection": "Jim Thorpe athletic genius, early football rule innovations, pop warner plays, Carlisle Indian School history, and Olympic gold.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Indian boarding school assimilation policies", "Stripping of Olympic medals"],
        "readingLevel": "Grade 6-9 / 940L",
        "genre": "Sports Narrative Nonfiction",
        "isbn": "9781596439542",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781596439542-M.jpg",
        "description": "In 1912, an underdog football team from the Carlisle Indian Industrial School, coached by Pop Warner and led by super-athlete Jim Thorpe, defeated powerhouse Harvard and changed American sports forever.",
        "pageCount": 288
    },
    {
        "id": "mock-179",
        "title": "Bomb: The Race to Build—and Steal—the World's Most Dangerous Weapon",
        "author": "Steve Sheinkin",
        "publishedYear": 2012,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "Newbery Honor and Sibert Medal nonfiction thriller reading like a spy novel, detailing Manhattan Project physicists, KGB espionage, and Norwegian heavy water commando raids.",
        "interestConnection": "Manhattan Project, nuclear physics, Soviet espionage, Norwegian ski commando sabotage, and Oppenheimer biography.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Atomic bomb devastation of Hiroshima and Nagasaki discussed historically"],
        "readingLevel": "Grade 6-9 / 920L",
        "genre": "Historical Spy Nonfiction",
        "isbn": "9781596434875",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781596434875-M.jpg",
        "description": "In December 1938, a chemist in a German laboratory made a discovery that would change the world: the splitting of a uranium atom. This is the story of the scientists and spies who raced to build the atomic bomb.",
        "pageCount": 272
    },
    {
        "id": "mock-180",
        "title": "The Port Chicago 50",
        "author": "Steve Sheinkin",
        "publishedYear": 2014,
        "recommendedAgeMin": 11,
        "recommendedAgeMax": 15,
        "whyAppropriate": "National Book Award finalist detailing the WWII naval explosion disaster in California and the 50 Black sailors who refused to return to unsafe ammunition loading under segregation.",
        "interestConnection": "WWII homefront explosion, civil rights military mutiny trial, Thurgood Marshall legal defense, and courageous moral stand.",
        "maturityScores": { "violence": "Moderate", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Massive munition port explosion disaster", "Military court-martial mutiny trial"],
        "readingLevel": "Grade 6-9 / 950L",
        "genre": "Civil Rights History / Nonfiction",
        "isbn": "9781596437968",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781596437968-M.jpg",
        "description": "On July 17, 1944, a massive explosion rocked the Port Chicago naval base near San Francisco, killing hundreds of Black sailors loading munitions. When 50 surviving men refused to resume work under unsafe conditions, they were charged with mutiny.",
        "pageCount": 208
    },
    {
        "id": "mock-181",
        "title": "Most Dangerous",
        "author": "Steve Sheinkin",
        "publishedYear": 2015,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "National Book Award finalist about Daniel Ellsberg, the secret history of the Vietnam War, the Pentagon Papers leak, and freedom of the press.",
        "interestConnection": "Pentagon Papers whistleblower, photocopier espionage, Vietnam War secrets, Watergate burglary connection, and press freedom.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Vietnam War combat realities discussed in political context"],
        "readingLevel": "Grade 7-10 / 990L",
        "genre": "Political Espionage Nonfiction",
        "isbn": "9781596439528",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781596439528-M.jpg",
        "description": "Daniel Ellsberg had top-secret security clearance, access to highest-level war documents, and a crisis of conscience. Risking life in prison, he smuggled 7,000 pages of the Pentagon Papers to the press.",
        "pageCount": 384
    },
    {
        "id": "mock-182",
        "title": "Fallout: Spies, Superbombs, and the Ultimate Cold War Showdown",
        "author": "Steve Sheinkin",
        "publishedYear": 2021,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Nail-biting Cold War history tracking the Cuban Missile Crisis, U-2 spy plane shootdowns, KGB hollow nickel codes, and close-call nuclear brinkmanship.",
        "interestConnection": "Cuban Missile Crisis, U-2 spy plane reconnaissance, JFK and Khrushchev diplomacy, hollow coin microfilm, and submarine crisis.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Nuclear war brinkmanship tension"],
        "readingLevel": "Grade 7-10 / 960L",
        "genre": "Cold War History Nonfiction",
        "isbn": "9781250149015",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781250149015-M.jpg",
        "description": "The Cuban Missile Crisis brought humanity to the brink of nuclear catastrophe. Sheinkin tracks the spies, pilots, and leaders in Washington and Moscow during the thirteen days that shook the planet.",
        "pageCount": 352
    },
    {
        "id": "mock-183",
        "title": "Stamped: Racism, Antiracism, and You",
        "author": "Jason Reynolds & Ibram X. Kendi",
        "publishedYear": 2020,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Accessible, energetic historical remix analyzing how racist ideas were constructed and disseminated, empowering youth to identify and dismantle bias.",
        "interestConnection": "American history remix, conversational tone, identifying segregationist/assimilationist/antiracist ideas, and youth agency.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Historical racism and slavery ideologies dissected critically"],
        "readingLevel": "Grade 7-10 / 1000L",
        "genre": "History / Social Science",
        "isbn": "9780316453691",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316453691-M.jpg",
        "description": "This is NOT a history book—it's a book about the here and now. Jason Reynolds translates complex historical scholarship into a conversational roadmap of how racist ideas were made and can be unmade.",
        "pageCount": 320
    },
    {
        "id": "mock-184",
        "title": "Starfish",
        "author": "Lisa Fipps",
        "publishedYear": 2021,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Printz Honor verse novel tackling fat-shaming, body sovereignty, swimming therapy, and standing up for your right to take up space.",
        "interestConnection": "Novel in verse, swimming pool liberation, starfish metaphor, great therapy sessions, and dog rescue.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Maternal emotional fat-shaming and bullying"],
        "readingLevel": "Grade 5-8 / 690L",
        "genre": "Novel in Verse / Body Positivity",
        "isbn": "9781984814500",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781984814500-M.jpg",
        "description": "Ever since she wore a whale swimsuit at her fifth birthday party, Ellie has been bullied about her weight. With the help of her therapist, her dad, and swimming, she learns to claim her space like a starfish.",
        "pageCount": 256
    },
    {
        "id": "mock-185",
        "title": "Genesis Begins Again",
        "author": "Alicia D. Williams",
        "publishedYear": 2019,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Newbery Honor and Coretta Scott King Honor book addressing internalized colorism, family eviction, singing Billie Holiday jazz, and self-love.",
        "interestConnection": "Colorism reflection, jazz singing Billie Holiday, middle school choir solo, eviction resilience, and self-worth.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Internalized colorism self-harm rituals (scrubbing skin with bleach thwarts)", "Father alcoholism and gambling debt evictions"],
        "readingLevel": "Grade 5-8 / 710L",
        "genre": "Realistic Fiction",
        "isbn": "9781481465809",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781481465809-M.jpg",
        "description": "Genesis keeps a list of ninety-six things she hates about herself, starting with her dark skin. When her family moves to a new neighborhood, a choir teacher helps her discover her voice and self-worth.",
        "pageCount": 384
    },
    {
        "id": "mock-186",
        "title": "A Monster Calls",
        "author": "Patrick Ness",
        "publishedYear": 2011,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Carnegie Medal-winning masterpiece about an ancient yew tree monster guiding a boy through the harrowing, guilt-ridden stages of his mother's terminal cancer.",
        "interestConnection": "Ancient yew tree monster, dark parables about human paradox, processing grief, nightmare clock, and emotional honesty.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mature" },
        "contentWarnings": ["Maternal terminal cancer and passing", "Destruction of room in rage"],
        "readingLevel": "Grade 6-9 / 730L",
        "genre": "Magical Realism / Grief",
        "isbn": "9780763660659",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780763660659-M.jpg",
        "description": "At seven minutes past midnight, thirteen-year-old Conor wakes to find a monster at his bedroom window—an ancient yew tree that demands Conor speak the truth he fears most.",
        "pageCount": 224
    },
    {
        "id": "mock-187",
        "title": "The Knife of Never Letting Go",
        "author": "Patrick Ness",
        "publishedYear": 2008,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Tense, breathlessly paced sci-fi thriller about a world where all male thoughts are broadcast aloud in a cacophony called 'The Noise', exploring truth and censorship.",
        "interestConnection": "Broadcasting all thoughts aloud ('The Noise'), telepathic talking dog Manchee, silent girl discovery, swamp pursuit, and corruption.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Violent pursuit by corrupt town army", "Tragic loss of animal companion"],
        "readingLevel": "Grade 7-10 / 810L",
        "genre": "Dystopian Sci-Fi",
        "isbn": "9780763645762",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780763645762-M.jpg",
        "description": "Todd Hewitt is the only boy left in Prentisstown, where everyone can hear everyone else's thoughts in an overwhelming Noise. When he discovers a patch of total silence, he finds a girl and must run for his life.",
        "pageCount": 496
    },
    {
        "id": "mock-188",
        "title": "The Ask and the Answer",
        "author": "Patrick Ness",
        "publishedYear": 2009,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Nuanced exploration of totalitarian tyranny versus insurgent terrorism, showing how young people get manipulated by opposing extremist factions.",
        "interestConnection": "Rebel resistance vs authoritarian mayor, bomb attacks, medical healing ward, moral compromise, and loyalty.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Terrorist bomb explosions by resistance", "Torture and metal branding bands"],
        "readingLevel": "Grade 8-11 / 820L",
        "genre": "Dystopian Sci-Fi",
        "isbn": "9780763648374",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780763648374-M.jpg",
        "description": "Separated from Viola, Todd is forced into labor by the tyrannical Mayor Prentiss, while Viola joins an insurgent group known as the Answer, pulling the two friends onto opposing sides of a brutal conflict.",
        "pageCount": 544
    },
    {
        "id": "mock-189",
        "title": "Monsters of Men",
        "author": "Patrick Ness",
        "publishedYear": 2010,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Carnegie Medal-winning conclusion examining the terrible machinery of war, indigenous alien rights, empathy, and making peace.",
        "interestConnection": "Three-way warfare, indigenous Spackle alien perspectives, peace negotiations, and ultimate self-sacrifice.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["War casualties and artillery bombardments"],
        "readingLevel": "Grade 8-11 / 830L",
        "genre": "Dystopian Sci-Fi Finale",
        "isbn": "9780763656652",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780763656652-M.jpg",
        "description": "As three armies march into a devastating war on New World, Todd and Viola must decide whether to join the fight or sacrifice everything to build an impossible bridge to peace.",
        "pageCount": 624
    },
    {
        "id": "mock-190",
        "title": "Illuminae",
        "author": "Amie Kaufman & Jay Kristoff",
        "publishedYear": 2015,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Groundbreaking epistolary sci-fi told via hacked emails, schematics, military transcripts, and a rogue AI questioning the logic of human life.",
        "interestConnection": "Hacked file dossier, rogue AI AIDAN, dreadnought space pursuit, biotech virus outbreak, and teenage hackers.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Planetary mining colony bombardment", "Bioweapon contagion rage virus on ship"],
        "readingLevel": "Grade 8-11 / 790L",
        "genre": "Multimedia Epistolary Sci-Fi",
        "isbn": "9780553499117",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780553499117-M.jpg",
        "description": "Told through hacked documents, interview transcripts, and medical reports, Kady and Ezra must escape a rival megacorporation's warship, an airborne plague, and their fleet's rogue artificial intelligence.",
        "pageCount": 608
    },
    {
        "id": "mock-191",
        "title": "Gemina",
        "author": "Amie Kaufman & Jay Kristoff",
        "publishedYear": 2016,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Die Hard on a space jump station: an elite hit squad infiltrates Heimdall station and two mismatched teens use brains and ventilation shafts to resist.",
        "interestConnection": "Space station assault, ventilation duct guerrilla warfare, alien lamptrey parasites, wormhole physics, and banter.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Mercenary team tactical execution of station crew", "Alien predator attacks"],
        "readingLevel": "Grade 8-11 / 800L",
        "genre": "Multimedia Epistolary Sci-Fi",
        "isbn": "9780553499155",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780553499155-M.jpg",
        "description": "Station Heimdall is preparing for the arrival of the refugee fleet when an elite black-ops team takes over. The station director's pampered daughter and a gang member must team up to survive.",
        "pageCount": 672
    },
    {
        "id": "mock-192",
        "title": "Obsidio",
        "author": "Amie Kaufman & Jay Kristoff",
        "publishedYear": 2018,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Thrilling conclusion bringing all six survivors back to Kerenza IV for a high-stakes planetary reclamation against corporate tyranny.",
        "interestConnection": "Planetary rebellion, hacking orbital satellites, mech walker combat, found family, and exposing corporate war crimes.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Occupied labor camp suppression", "Urban guerrilla war"],
        "readingLevel": "Grade 8-11 / 810L",
        "genre": "Multimedia Epistolary Sci-Fi Finale",
        "isbn": "9780553499193",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780553499193-M.jpg",
        "description": "Kady, Ezra, Hanna, and Nik are on the verge of returning to Kerenza IV with the remnants of the refugee fleet. To expose BeiTech’s crimes, they must lead an underground insurgency.",
        "pageCount": 624
    },
    {
        "id": "mock-193",
        "title": "Aurora Rising",
        "author": "Amie Kaufman & Jay Kristoff",
        "publishedYear": 2019,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Guardians of the Galaxy meets Star Trek: a squad of academy misfits rescue an ancient girl out of cryo-sleep who might trigger an ancient galactic extinction event.",
        "interestConnection": "Space academy misfits squad, cryo-freeze time jump, sarcastic alien warrior, telekinetic powers, and galactic heist.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Space combat skirmishes", "Ancient biological hive menace"],
        "readingLevel": "Grade 7-10 / 750L",
        "genre": "Sci-Fi Space Opera",
        "isbn": "9781524720964",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781524720964-M.jpg",
        "description": "Top academy graduate Tyler Jones is stuck with the leftovers no one else wanted for his first patrol squad. But when he rescues a girl out of cryo-sleep who has been lost for two centuries, the galaxy erupts in pursuit.",
        "pageCount": 480
    },
    {
        "id": "mock-194",
        "title": "Aurora Burning",
        "author": "Amie Kaufman & Jay Kristoff",
        "publishedYear": 2020,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Fast-paced space adventure examining alien hive minds, family lineage secrets, loyalty among outcasts, and sacrifice.",
        "interestConnection": "Space fleet dogfights, ancient alien weapon, telepathic abilities, undercover disguise, and family secrets.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Space combat and plant-like hive assimilation threat"],
        "readingLevel": "Grade 7-10 / 760L",
        "genre": "Sci-Fi Space Opera",
        "isbn": "9781524720995",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781524720995-M.jpg",
        "description": "Squad 312 is on the run from the entire galaxy. As the ancient Ra'haam threatens to consume all sentient life, Tyler and his crew must travel to the heart of an alien empire to unlock Aurora's powers.",
        "pageCount": 512
    },
    {
        "id": "mock-195",
        "title": "Nyxia",
        "author": "Scott Reintgen",
        "publishedYear": 2017,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Ender's Game meets The Hunger Games: an underprivileged teen from Detroit is recruited by a mega-corporation to compete for mining rights on an alien planet.",
        "interestConnection": "Shapeshifting alien mineral Nyxia, zero-gravity combat simulations, spaceship competition, Detroit loyalty, and tech training.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Cutthroat elimination corporate trials on spaceship"],
        "readingLevel": "Grade 7-10 / 720L",
        "genre": "Sci-Fi Competition Thriller",
        "isbn": "9780399556791",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399556791-M.jpg",
        "description": "Emmett Atwater is recruited by the Babel Corporation to travel to an alien planet to mine Nyxia, a versatile shapeshifting substance. But first he must win a ruthless competition against nine other teens.",
        "pageCount": 384
    },
    {
        "id": "mock-196",
        "title": "Nyxia Unleashed",
        "author": "Scott Reintgen",
        "publishedYear": 2018,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Tense landing on planet Magnidia where recruits discover the indigenous alien Adamites are civilized, forcing a moral stand against corporate exploitation.",
        "interestConnection": "Alien planet Magnidia, indigenous Adamite diplomacy, corporate sabotage, underground mining tunnels, and alliance.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Corporate exploitation and armed skirmishes on alien world"],
        "readingLevel": "Grade 7-10 / 730L",
        "genre": "Sci-Fi Thriller",
        "isbn": "9780399556838",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780399556838-M.jpg",
        "description": "Emmett and his crew arrive on planet Magnidia, only to find that Babel has kept dark secrets about the indigenous Adamites and the deadly price of harvesting Nyxia.",
        "pageCount": 400
    },
    {
        "id": "mock-197",
        "title": "Feed",
        "author": "M.T. Anderson",
        "publishedYear": 2002,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Eerily prophetic satire of hyper-consumerism, targeted digital feeds wired directly into brains, ecological decay, and resisting algorithmic addiction.",
        "interestConnection": "Brain internet feed implants, targeted corporate marketing satire, hacker rebellion, moon vacation, and intellectual resistance.",
        "maturityScores": { "violence": "Mild", "language": "Moderate", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Brain implant hacking malfunctions", "Ecological degradation"],
        "readingLevel": "Grade 8-11 / 770L",
        "genre": "Cyberpunk Satire Classic",
        "isbn": "9780763622596",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780763622596-M.jpg",
        "description": "In a future where internet 'feeds' are hardwired directly into the brains of seventy-three percent of Americans, Titus meets Violet, a girl who questions the algorithm and wants to live without the feed.",
        "pageCount": 304
    },
    {
        "id": "mock-198",
        "title": "Across the Universe",
        "author": "Beth Revis",
        "publishedYear": 2011,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Locked-room murder mystery aboard a generation ship hurtling through space, exploring authoritarian social control and scientific truths.",
        "interestConnection": "Generation starship Godspeed, cryo-frozen passenger sabotage, futuristic social hierarchy, space murder mystery, and planet landing.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "Mild", "themes": "Moderate" },
        "contentWarnings": ["Cryo-chamber unplugging murders investigated", "Mind-altering sedatives in water supply"],
        "readingLevel": "Grade 7-10 / 690L",
        "genre": "Sci-Fi Mystery",
        "isbn": "9781595144676",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781595144676-M.jpg",
        "description": "Seventeen-year-old Amy is cryogenically frozen for a three-hundred-year space voyage. When her chamber is unplugged fifty years too early, she discovers a killer is sabotaging the sleepers.",
        "pageCount": 416
    },
    {
        "id": "mock-199",
        "title": "These Broken Stars",
        "author": "Amie Kaufman & Meagan Spooner",
        "publishedYear": 2013,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Titanic in space meets Lost: a luxury spaceliner crashes on an abandoned terraformed world where an heiress and a soldier uncover whispers in the mist.",
        "interestConnection": "Luxury spaceliner disaster, survival on alien planet, military hero escorting tech heiress, terraforming anomaly, and telepathic whispers.",
        "maturityScores": { "violence": "Mild", "language": "Mild", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Spaceliner crash casualties in opening", "Hallucinatory whispers"],
        "readingLevel": "Grade 7-10 / 740L",
        "genre": "Sci-Fi Survival Romance",
        "isbn": "9781423171027",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781423171027-M.jpg",
        "description": "Luxury starship Icarus suddenly plummets out of hyperspace and crashes into an uncharted planet. The only survivors are Lilac, the daughter of the galaxy's richest man, and Tarver, a young war hero.",
        "pageCount": 384
    },
    {
        "id": "mock-200",
        "title": "Iron Widow",
        "author": "Xiran Jay Zhao",
        "publishedYear": 2021,
        "recommendedAgeMin": 14,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Fierce, revolutionary sci-fi combining giant mecha combat (Pacific Rim) with Chinese history (Empress Wu Zetian), defying patriarchal sacrifices.",
        "interestConnection": "Giant mecha Chrysalises, psychic spirit pressure, Empress Wu Zetian inspiration, vengeance for sister, and polyamory.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Moderate", "themes": "Moderate" },
        "contentWarnings": ["Brutal foot-binding trauma references", "Pilot spirit-drain deaths in mechas"],
        "readingLevel": "Grade 9-12 / 820L",
        "genre": "Mecha Sci-Fi / Alternate History",
        "isbn": "9780735269934",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780735269934-M.jpg",
        "description": "In Huaxia, boys pilot giant mechas called Chrysalises by draining the life force of girl concubines. Eighteen-year-old Zetian volunteers with one goal: assassinate the pilot who killed her sister.",
        "pageCount": 400
    },
    {
        "id": "mock-201",
        "title": "Six Crimson Cranes",
        "author": "Elizabeth Lim",
        "publishedYear": 2021,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Enchanting East Asian fairy tale retelling of The Wild Swans, focusing on familial devotion, sewing starthread nets, and holding your silence for loved ones.",
        "interestConnection": "The Wild Swans fairy tale remix, enchanted crane brothers, mute princess quest, origami dragon paper bird, and dragon king.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Brothers transformed into cranes by curse", "Vow of silence with fatal stakes"],
        "readingLevel": "Grade 6-9 / 720L",
        "genre": "Asian Folklore YA Fantasy",
        "isbn": "9780593300916",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780593300916-M.jpg",
        "description": "Shiori is the only princess of Kiata who possesses forbidden magic. When her stepmother banishes her and turns her six brothers into cranes, Shiori must remain mute to save their lives.",
        "pageCount": 464
    },
    {
        "id": "mock-202",
        "title": "The Dragon's Promise",
        "author": "Elizabeth Lim",
        "publishedYear": 2022,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Breathtaking sequel descending into the underwater Dragon Realm, exploring duty, keeping impossible promises, and magical diplomacy.",
        "interestConnection": "Underwater dragon palace, returning dragon pearl, demonic possession, magic tapestry, and court loyalty.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Demon pearl dark corruption", "Underwater peril"],
        "readingLevel": "Grade 6-9 / 730L",
        "genre": "Asian Folklore YA Fantasy",
        "isbn": "9780593300947",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780593300947-M.jpg",
        "description": "Shiori made a deathbed promise to return the dragon pearl to its rightful owner. Journeying into the treacherous underwater kingdom of dragons, she uncovers a conspiracy that threatens both realms.",
        "pageCount": 448
    },
    {
        "id": "mock-203",
        "title": "Spin the Dawn",
        "author": "Elizabeth Lim",
        "publishedYear": 2019,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Mulan meets Project Runway: a determined young woman poses as a boy to compete as imperial tailor, weaving magical dresses of the sun, moon, and stars.",
        "interestConnection": "Imperial tailor competition, sewing magic with sunlight and starlight, disguised as brother, and mythical beasts.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Court competition sabotage", "Desert sandstorm perils"],
        "readingLevel": "Grade 6-9 / 700L",
        "genre": "Silk Road Fantasy",
        "isbn": "9780525646990",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780525646990-M.jpg",
        "description": "Maia Tamarin poses as a boy to take her ailing father's place in a deadly competition to become the imperial tailor, embarking on a quest to sew three magical dresses woven from the sun, moon, and stars.",
        "pageCount": 400
    },
    {
        "id": "mock-204",
        "title": "Dry",
        "author": "Neal Shusterman & Jarrod Shusterman",
        "publishedYear": 2018,
        "recommendedAgeMin": 12,
        "recommendedAgeMax": 16,
        "whyAppropriate": "Terrifyingly realistic eco-thriller exploring the collapse of modern society in Southern California when the taps completely run dry during the 'Tap-Out'.",
        "interestConnection": "Severe water crisis 'The Tap-Out', neighborhood breakdown, water desalination quest, survival caravan, and ecological warning.",
        "maturityScores": { "violence": "Moderate", "language": "Mild", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Civil unrest over bottled water", "Dehydration delirium", "Wildfire threat"],
        "readingLevel": "Grade 7-10 / 790L",
        "genre": "Ecological Disaster Thriller",
        "isbn": "9781481481946",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781481481946-M.jpg",
        "description": "When California's drought escalates and the taps suddenly run dry, suburban neighborhoods turn into war zones in hours. Alyssa must lead her little brother across an unforgiving landscape to find water.",
        "pageCount": 400
    },
    {
        "id": "mock-205",
        "title": "Roxy",
        "author": "Neal Shusterman & Jarrod Shusterman",
        "publishedYear": 2021,
        "recommendedAgeMin": 13,
        "recommendedAgeMax": 17,
        "whyAppropriate": "Creative, hard-hitting allegorical novel personifying prescription medications and illicit narcotics as gods playing a high-stakes bet with human lives.",
        "interestConnection": "Personified medications (Roxy/Oxycodone, Addison/Adderall), high school soccer injury, party culture, and chemical dependence warning.",
        "maturityScores": { "violence": "Moderate", "language": "Moderate", "romance": "Mild", "themes": "Mature" },
        "contentWarnings": ["Opioid addiction and prescription drug misuse allegories", "Overdose hospital emergency"],
        "readingLevel": "Grade 8-11 / 820L",
        "genre": "Allegorical Social Realism",
        "isbn": "9781481498661",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781481498661-M.jpg",
        "description": "Roxy and Addison are godlike beings who take the form of medications. When they place a bet on two siblings trying to cope with pain and academic pressure, the game turns into a fight for survival.",
        "pageCount": 400
    },
    {
        "id": "mock-206",
        "title": "Heat",
        "author": "Mike Lupica",
        "publishedYear": 2006,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Heartwarming Little League baseball story about a Cuban-American pitching prodigy whose team reaches the championship while hiding that his father has passed away.",
        "interestConnection": "Little League World Series, 80-mph fastball, Bronx neighborhood, Yankee Stadium dreams, and protective older brother.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Brothers hiding father's passing to stay out of foster system"],
        "readingLevel": "Grade 5-7 / 940L",
        "genre": "Sports Fiction / Family",
        "isbn": "9780142407578",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780142407578-M.jpg",
        "description": "Twelve-year-old Michael Arroyo has a pitching arm that could lead his team to the Little League World Series. But rival coaches demand his Cuban birth certificate, which Michael cannot produce.",
        "pageCount": 240
    },
    {
        "id": "mock-207",
        "title": "Travel Team",
        "author": "Mike Lupica",
        "publishedYear": 2004,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Inspiring sports classic about an undersized basketball player cut from the elite travel team, who forms a ragtag squad with his estranged father as coach.",
        "interestConnection": "Underdog basketball, point guard court vision, travel team tryouts, father-son redemption, and buzzer-beaters.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Father recovery from past alcoholism discussed and reconciled"],
        "readingLevel": "Grade 5-7 / 930L",
        "genre": "Sports Fiction Classic",
        "isbn": "9780142404621",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780142404621-M.jpg",
        "description": "Danny Walker is the best passer in town, but when tryouts arrive, the coach cuts him for being too short. Danny's dad, an NBA legend, forms a second team of misfits to prove everyone wrong.",
        "pageCount": 288
    }
]

print(f"Group 2 complete: {len(GROUP_2_B)} books in part B")
