# Group 1: Middle Grade / Tween (Ages 10-12) - Books mock-26 to mock-114 (89 books)

GROUP_1 = [
    {
        "id": "mock-26",
        "title": "Holes",
        "author": "Louis Sachar",
        "publishedYear": 1998,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Masterfully woven story of friendship, family curses, and justice at a juvenile detention camp with humor and heart.",
        "interestConnection": "Mystery, buried treasure, juvenile detention adventure, humorous destiny, and true friendship.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Camp Green Lake harsh conditions", "Yellow-spotted lizards danger"],
        "readingLevel": "Grade 5-7 / 660L",
        "genre": "Mystery / Adventure",
        "isbn": "9780440414803",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780440414803-M.jpg",
        "description": "Stanley Yelnats is under a curse that began with his no-good-dirty-rotten-pig-stealing-great-great-grandfather. Sent to Camp Green Lake, he must dig a hole five feet deep every single day.",
        "pageCount": 233
    },
    {
        "id": "mock-27",
        "title": "Wonder",
        "author": "R.J. Palacio",
        "publishedYear": 2012,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Profound, empathy-building novel about kindness, facial differences, and peer acceptance from multiple perspectives.",
        "interestConnection": "Starting middle school, overcoming bullying, kindness, family love, and multiple character viewpoints.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Verbal peer bullying", "Medical surgery discussions"],
        "readingLevel": "Grade 4-6 / 790L",
        "genre": "Realistic Fiction",
        "isbn": "9780375869020",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780375869020-M.jpg",
        "description": "August Pullman was born with a facial difference that prevented him from going to a mainstream school—until now. Starting fifth grade at Beecher Prep, all he wants is to be treated as ordinary.",
        "pageCount": 315
    },
    {
        "id": "mock-28",
        "title": "Hatchet",
        "author": "Gary Paulsen",
        "publishedYear": 1987,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Celebrated survival narrative emphasizing patience, resilience, self-reliance, and respect for nature.",
        "interestConnection": "Wilderness survival, bush plane crash, crafting tools, Canadian wilderness, and mental toughness.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Plane pilot heart attack", "Wilderness injury and animal attacks"],
        "readingLevel": "Grade 5-8 / 1020L",
        "genre": "Survival Adventure",
        "isbn": "9781416936473",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781416936473-M.jpg",
        "description": "Thirteen-year-old Brian Robeson is on his way to visit his father in a small single-engine plane when the pilot suffers a fatal heart attack. Brian crashes into the Canadian north woods with only a hatchet.",
        "pageCount": 195
    },
    {
        "id": "mock-29",
        "title": "The Mysterious Benedict Society",
        "author": "Trenton Lee Stewart",
        "publishedYear": 2007,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Delightful celebration of gifted children using intellect, empathy, and observation rather than superpowers to thwart mind control.",
        "interestConnection": "Riddles, puzzle-solving tests, undercover orphan agents, secret institute, and eccentric mentors.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Mind-sweeping technology threat", "Secret academy danger"],
        "readingLevel": "Grade 5-7 / 890L",
        "genre": "Mystery / Adventure",
        "isbn": "9780316003957",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316003957-M.jpg",
        "description": "Dozens of children respond to a peculiar newspaper ad, but only four gifted kids pass the ingenious tests. Their mission: go undercover at the Learning Institute for the Very Enlightened.",
        "pageCount": 512
    },
    {
        "id": "mock-30",
        "title": "Bridge to Terabithia",
        "author": "Katherine Paterson",
        "publishedYear": 1977,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Newbery Medal classic on imaginary worlds, deep platonic friendship, artistic expression, and navigating unexpected grief.",
        "interestConnection": "Imaginary kingdom, running races, artistic friendship, tree rope swings, and childhood imagination.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Tragic accidental death of best friend"],
        "readingLevel": "Grade 5-7 / 810L",
        "genre": "Classic Coming of Age",
        "isbn": "9780064401845",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780064401845-M.jpg",
        "description": "Jess Aarons wants to be the fastest runner in the fifth grade until new girl Leslie Burke outpaces everyone. They become inseparable and create an imaginary secret kingdom called Terabithia.",
        "pageCount": 163
    },
    {
        "id": "mock-31",
        "title": "The Westing Game",
        "author": "Ellen Raskin",
        "publishedYear": 1978,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Brilliant Newbery puzzle mystery challenging readers to decipher word games, financial clues, and character motives.",
        "interestConnection": "Billionaire will inheritance, word puzzles, suspicious heirs, bomb clues, and detective teamwork.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Eccentric millionaire murder mystery setting", "Small indoor firework explosions"],
        "readingLevel": "Grade 5-8 / 750L",
        "genre": "Puzzle Whodunit",
        "isbn": "9780142401200",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780142401200-M.jpg",
        "description": "Sixteen unlikely heirs are summoned to the reading of Samuel W. Westing's will. Paired into unlikely duos, they compete in an intricate game to win a two-hundred-million-dollar fortune.",
        "pageCount": 182
    },
    {
        "id": "mock-32",
        "title": "Number the Stars",
        "author": "Lois Lowry",
        "publishedYear": 1989,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Gentle yet gripping introduction to WWII Holocaust history, focusing on Danish bravery, resistance, and protecting neighbors.",
        "interestConnection": "World War II Denmark, heroic resistance smuggling, secret escape to Sweden, and childhood courage.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Nazi patrol interrogation tension", "Historical wartime peril"],
        "readingLevel": "Grade 4-6 / 670L",
        "genre": "Historical Fiction",
        "isbn": "9780547577098",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780547577098-M.jpg",
        "description": "Ten-year-old Annemarie Johansen lives in Copenhagen during the German occupation of Denmark. When the Nazis begin rounding up Jewish citizens, Annemarie's family hides her best friend Ellen.",
        "pageCount": 160
    },
    {
        "id": "mock-33",
        "title": "Bud, Not Buddy",
        "author": "Christopher Paul Curtis",
        "publishedYear": 1999,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Newbery and Coretta Scott King award winner following a resilient boy's quest for his father during the Great Depression with jazz and humor.",
        "interestConnection": "Great Depression, jazz musicians, suitcase treasures, funny survival rules, and family search.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Orphan shelter foster family cruelty", "Depression era poverty"],
        "readingLevel": "Grade 4-6 / 950L",
        "genre": "Historical Fiction",
        "isbn": "9780439402002",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780439402002-M.jpg",
        "description": "Ten-year-old Bud Caldwell hits the road in 1936 Flint, Michigan, searching for the father he never knew. His only clues are flyers of a legendary jazz band leader.",
        "pageCount": 245
    },
    {
        "id": "mock-34",
        "title": "New Kid",
        "author": "Jerry Craft",
        "publishedYear": 2019,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "First graphic novel to win the Newbery Medal. Honest, funny exploration of fitting in at a prestigious private school and microaggressions.",
        "interestConnection": "Graphic novel, middle school comics art, code-switching, cartooning, and friendship struggles.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Subtle racial microaggressions depicted and analyzed"],
        "readingLevel": "Grade 4-7 / 600L",
        "genre": "Graphic Novel / Realistic",
        "isbn": "9780062691194",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062691194-M.jpg",
        "description": "Jordan Banks loves drawing cartoons, but his parents enroll him in Riverdale Academy Day School, where he is one of the few kids of color in his grade.",
        "pageCount": 256
    },
    {
        "id": "mock-35",
        "title": "Amulet: The Stonekeeper",
        "author": "Kazu Kibuishi",
        "publishedYear": 2008,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Visually stunning fantasy graphic novel with brave siblings entering an alternate steampunk universe to save their mother.",
        "interestConnection": "Graphic novel, glowing magical stone amulet, steampunk walking house, arachnid monsters, and sibling courage.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Fantasy monster tentacle abductions", "Car accident in prologue"],
        "readingLevel": "Grade 4-6 / 500L",
        "genre": "Graphic Novel / Fantasy",
        "isbn": "9780439846813",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780439846813-M.jpg",
        "description": "After a family tragedy, Emily and Navin move with their mother to their great-grandfather's mysterious old house, where their mother is kidnapped by a monstrous tentacled creature.",
        "pageCount": 192
    },
    {
        "id": "mock-36",
        "title": "Smile",
        "author": "Raina Telgemeier",
        "publishedYear": 2010,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Autobiographical graphic novel navigating middle school dental trauma, self-esteem, peer dynamics, and finding real friends.",
        "interestConnection": "Graphic novel, braces and dental surgery, middle school crush drama, earthquake, and girl scouts.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "Mild", "themes": "Mild" },
        "contentWarnings": ["Dental accident injury and headgear anxiety"],
        "readingLevel": "Grade 4-6 / 410L",
        "genre": "Graphic Novel / Memoir",
        "isbn": "9780545132060",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780545132060-M.jpg",
        "description": "Raina just wants to be a normal sixth grader until a severe fall knocks out her two front teeth, kicking off an exhausting journey of braces, surgery, headgear, and friend drama.",
        "pageCount": 224
    },
    {
        "id": "mock-37",
        "title": "El Deafo",
        "author": "Cece Bell",
        "publishedYear": 2014,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Newbery Honor graphic memoir about childhood hearing loss, turning a bulky hearing aid into a superhero persona, and true friendship.",
        "interestConnection": "Graphic novel, deaf superhero alter-ego, Phonic Ear superpower, school dynamics, and funny bunny characters.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Meningitis illness backstory", "Social exclusion feelings"],
        "readingLevel": "Grade 4-6 / 420L",
        "genre": "Graphic Novel / Memoir",
        "isbn": "9781419712173",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781419712173-M.jpg",
        "description": "Starting at a new school with a bulky Phonic Ear hearing aid strapped to her chest is tough, until Cece discovers it gives her the superpower to hear her teacher anywhere in the school.",
        "pageCount": 248
    },
    {
        "id": "mock-38",
        "title": "Wings of Fire: The Dragonet Prophecy",
        "author": "Tui T. Sutherland",
        "publishedYear": 2012,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Epic dragon fantasy series exploring destiny, peaceful rebellion against endless war, and inter-tribal cooperation.",
        "interestConnection": "Dragon tribes, prophecy, aerial battles, magical powers, gladiator arena escape, and loyalty.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Dragon fantasy gladiator combat"],
        "readingLevel": "Grade 4-7 / 740L",
        "genre": "Epic Fantasy",
        "isbn": "9780545349239",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780545349239-M.jpg",
        "description": "Clay and four other dragonets have been raised under a mountain to fulfill a mysterious prophecy that will end the war among the dragon tribes of Pyrrhia, but they want freedom.",
        "pageCount": 336
    },
    {
        "id": "mock-39",
        "title": "Fablehaven",
        "author": "Brandon Mull",
        "publishedYear": 2006,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Richly imagined secret preserve for mythological creatures where curiosity and rule-following carry real consequences.",
        "interestConnection": "Secret fairy sanctuary, magical milk, witch curses, troll encounters, and courageous siblings.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Magical creature peril", "Grandparents turned into statues"],
        "readingLevel": "Grade 5-7 / 700L",
        "genre": "Magical Fantasy",
        "isbn": "9781416947202",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781416947202-M.jpg",
        "description": "Kendra and her brother Seth go to stay with their eccentric grandfather, only to discover his sprawling estate is a secret sanctuary for mythical creatures on the brink of extinction.",
        "pageCount": 368
    },
    {
        "id": "mock-40",
        "title": "The Land of Stories: The Wishing Spell",
        "author": "Chris Colfer",
        "publishedYear": 2012,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Clever, imaginative modern fairy tale adventure examining the complex motivations behind classic villains and heroes.",
        "interestConnection": "Classic fairy tale portal, magical wishing spell quest, Evil Queen backstory, and witty sibling banter.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Fairy tale peril with witches and wolves"],
        "readingLevel": "Grade 4-7 / 720L",
        "genre": "Fairy Tale Adventure",
        "isbn": "9780316201568",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316201568-M.jpg",
        "description": "Twins Alex and Conner Bailey receive a cherished book of fairy tales from their grandmother, only to find themselves pulled into a world where fairy tales are real and dangerous.",
        "pageCount": 464
    },
    {
        "id": "mock-41",
        "title": "Skandar and the Unicorn Thief",
        "author": "A.F. Steadman",
        "publishedYear": 2022,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Fresh, elemental fantasy turning gentle unicorn myths into ferocious winged predators bonded to teenage riders.",
        "interestConnection": "Fierce winged unicorns, elemental magic exams, island academy, secret shadow magic, and racing.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Elemental magic clashes", "Wild unicorn predator threats"],
        "readingLevel": "Grade 5-7 / 780L",
        "genre": "Fantasy Adventure",
        "isbn": "9781665912730",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9781665912730-M.jpg",
        "description": "Skandar Smith dreams of becoming a unicorn rider, bonding with a ferocious winged beast and taking to the skies. But just as his dream is in reach, a shadowy villain steals the island’s most powerful unicorn.",
        "pageCount": 400
    },
    {
        "id": "mock-42",
        "title": "Nevermoor: The Trials of Morrigan Crow",
        "author": "Jessica Townsend",
        "publishedYear": 2017,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Enchanting, whimsical fantasy tackling self-worth, overcoming blamed superstition, and finding belonging in an eccentric magical society.",
        "interestConnection": "Magical trials, giant talking cat hotelier, curse redemption, whimsical steampunk society, and mysterious benefactor.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Cursed child superstition themes", "Shadow hound chase"],
        "readingLevel": "Grade 5-7 / 790L",
        "genre": "Whimsical Fantasy",
        "isbn": "9780316508889",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316508889-M.jpg",
        "description": "Morrigan Crow is cursed, blamed for all local misfortunes and doomed to die on Eventide. But when the hour arrives, an eccentric man named Jupiter North whisks her away to the secret city of Nevermoor.",
        "pageCount": 480
    },
    {
        "id": "mock-43",
        "title": "The One and Only Ivan",
        "author": "Katherine Applegate",
        "publishedYear": 2012,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Newbery Medal winner inspired by a true story about animal captivity, artistic expression, empathy, and keeping promises.",
        "interestConnection": "Gorilla artist, mall circus rescue, animal communication, gentle elephant friend, and liberation.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Animal neglect in roadside mall circus", "Aging elephant illness"],
        "readingLevel": "Grade 4-6 / 570L",
        "genre": "Animal Fiction / Empathy",
        "isbn": "9780061992254",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780061992254-M.jpg",
        "description": "Ivan is an easygoing silverback gorilla who has lived for 27 years behind the glass walls of his enclosure at a shopping mall. When a baby elephant named Ruby arrives, Ivan decides he must save her.",
        "pageCount": 320
    },
    {
        "id": "mock-44",
        "title": "Pax",
        "author": "Sara Pennypacker",
        "publishedYear": 2016,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Poignant, dual-perspective exploration of the bond between a boy and his pet fox, the collateral damage of war, and healing.",
        "interestConnection": "Boy and fox bond, wilderness trek, war impact on wildlife, amputee veteran mentor, and survival.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Wartime military mobilization", "Injuries to animals from landmines"],
        "readingLevel": "Grade 5-7 / 760L",
        "genre": "Animal Fiction / Adventure",
        "isbn": "9780061992254",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062377012-M.jpg",
        "description": "Pax and Peter have been inseparable ever since Peter rescued him as a kit. But when Peter’s father enlists in the military and Peter is forced to leave Pax behind, Peter treks 300 miles to reunite with his fox.",
        "pageCount": 288
    },
    {
        "id": "mock-45",
        "title": "Because of Winn-Dixie",
        "author": "Kate DiCamillo",
        "publishedYear": 2000,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 12,
        "whyAppropriate": "Heartwarming Newbery Honor story about community connection, grief, forgiving parents, and the transformative love of a rescued dog.",
        "interestConnection": "Rescued stray dog, southern small town eccentrics, library friends, preacher father, and overcoming loneliness.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Parental abandonment discussion (mother left family)"],
        "readingLevel": "Grade 4-6 / 610L",
        "genre": "Realistic Fiction",
        "isbn": "9780763616052",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780763616052-M.jpg",
        "description": "Ten-year-old India Opal Buloni goes down to the local supermarket for some groceries and comes home with a big, suffering dog she names Winn-Dixie, whose infectious charm helps her make friends.",
        "pageCount": 192
    },
    {
        "id": "mock-46",
        "title": "The War That Saved My Life",
        "author": "Kimberly Brubaker Bradley",
        "publishedYear": 2015,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Newbery Honor triumph of courage, dealing with disability (clubfoot), escaping domestic neglect, and finding love during the London evacuation.",
        "interestConnection": "World War II British countryside, horse riding, clubfoot resilience, evacuee children, and healing.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Moderate" },
        "contentWarnings": ["Abusive mother in opening chapters", "Blitz bombing air raids"],
        "readingLevel": "Grade 5-7 / 580L",
        "genre": "Historical Fiction",
        "isbn": "9780147510488",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780147510488-M.jpg",
        "description": "Ten-year-old Ada has never left her one-room apartment because her mother is ashamed of her twisted foot. When her brother is evacuated from London during WWII, Ada sneaks away with him to find freedom.",
        "pageCount": 320
    },
    {
        "id": "mock-47",
        "title": "Inside Out & Back Again",
        "author": "Thanhhà Lại",
        "publishedYear": 2011,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "National Book Award winner written in free verse, capturing the refugee experience from Saigon to Alabama with humor, heartbreak, and resilience.",
        "interestConnection": "Verse novel, Saigon papaya tree, fleeing war on refugee ship, learning English, and immigrant humor.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Fall of Saigon wartime evacuation", "Schoolyard bullying"],
        "readingLevel": "Grade 4-6 / 800L",
        "genre": "Historical Novel in Verse",
        "isbn": "9780061962790",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780061962790-M.jpg",
        "description": "For all the ten years of her life, Hà has only known Saigon: the thrills of its markets, the joy of its traditions, and the beauty of her very own papaya tree. But now the Vietnam War has reached her home.",
        "pageCount": 272
    },
    {
        "id": "mock-48",
        "title": "Esperanza Rising",
        "author": "Pam Muñoz Ryan",
        "publishedYear": 2000,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Pura Belpré winner celebrating labor dignity, perseverance through tragedy, and Mexican immigrant camp community support.",
        "interestConnection": "Mexican ranch life, Great Depression farmworker camp, labor strikes, crocheting wisdom, and resilience.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Bandit attack in opening chapter", "Valley fever illness"],
        "readingLevel": "Grade 5-7 / 750L",
        "genre": "Historical Fiction",
        "isbn": "9780439120425",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780439120425-M.jpg",
        "description": "Esperanza thought she'd always live a privileged life on her family's ranch in Mexico. But a sudden tragedy forces Esperanza and her mother to flee to California and settle in a Mexican farm labor camp.",
        "pageCount": 262
    },
    {
        "id": "mock-49",
        "title": "Brown Girl Dreaming",
        "author": "Jacqueline Woodson",
        "publishedYear": 2014,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 14,
        "whyAppropriate": "Newbery Honor and National Book Award-winning memoir in verse about growing up African American in the 1960s and 70s, finding one's voice through storytelling.",
        "interestConnection": "Civil Rights movement, free verse poetry, finding a writer's voice, southern roots, and family love.",
        "maturityScores": { "violence": "Mild", "language": "Clean", "romance": "None", "themes": "Mild" },
        "contentWarnings": ["Jim Crow segregation historical realities"],
        "readingLevel": "Grade 5-8 / 990L",
        "genre": "Memoir in Verse",
        "isbn": "9780147515827",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780147515827-M.jpg",
        "description": "Raised in South Carolina and New York, Jacqueline Woodson always felt halfway home in each place. In vivid poems, she shares what it was like to grow up as an African American in the 1960s and 1970s.",
        "pageCount": 352
    },
    {
        "id": "mock-50",
        "title": "The Phantom Tollbooth",
        "author": "Norton Juster",
        "publishedYear": 1961,
        "recommendedAgeMin": 10,
        "recommendedAgeMax": 13,
        "whyAppropriate": "Timeless witty masterpiece of wordplay, mathematical puns, curiosity, and learning to appreciate every moment in life.",
        "interestConnection": "Puns, idioms taken literally, watchdog Tock, Dictionopolis vs Digitopolis, and rescuing Rhyme & Reason.",
        "maturityScores": { "violence": "None", "language": "Clean", "romance": "None", "themes": "None" },
        "contentWarnings": [],
        "readingLevel": "Grade 5-7 / 1000L",
        "genre": "Fantasy / Wordplay Classic",
        "isbn": "9780394820378",
        "coverUrl": "https://covers.openlibrary.org/b/isbn/9780394820378-M.jpg",
        "description": "For Milo, everything's a bore. When a mysterious tollbooth appears in his room, he drives through in his toy car into the Lands Beyond, discovering how miraculous learning can be.",
        "pageCount": 256
    }
]

print(f"Group 1 part A loaded: {len(GROUP_1)} books")
